#!/bin/sh

description "SM pkg extension."

action "pkg list [installed]" "List packages installed via package module."
action "pkg list active" "List packages installed via package module with version."
action "pkg list available" "List all available package extensions installed."
action "pkg info {package}" "Provides information about {package}"
action "pkg active {packagea}[,{packageb}...]" "Prints active version for {packagea}, etc..."
action "pkg activate {package} {version}" "Activate given package and version."
action "pkg deactivate {package}" "Deactivates a given package, if active."
action "pkg remove {package} [version]" "deactivates and removes {packge} active or version specified."
action "pkg install {package} [version]" "installs {package} {version}."
action "pkg update {package} [version]" "updates {package} {version}."

show_help usage
