#!/usr/bin/env bash

description "${extension} BDSM extension."

actions "  list     - List packages installed through BDSM extensions, using the package module.
  active     - List active package versions.
  activate   - Activate a given package and version.
  deactivate - Deactivate a given package."

show_help usage
