#!/usr/bin/env bash

modules ext/templates ext/time project

if template_exists "bdsm/bdsmrc"
then
  if file_exists "$HOME/.bdsmrc"
  then
    timestamp_set

    log "An existing $HOME/.bdsmrc file was found."
    log "Reinaming it as ${HOME}/.bdsmrc.${timestamp} in order to preserve it."
    log "Please examine the file and if it is not needed, remove it."

    move_file "$HOME/.bdsmrc" to "$HOME/.bdsmrc.$timestamp"
  fi

  #
  # TODO: Move this into the project module and call as a function.
  #       bdsmrc_install, this does *not* belong here.
  #
  # TODO: Read project, repository_url and environment from defaults file.
  #       ~/.bdsm/project/config/defaults
  #

  true  "${repository_url:="username/repository"}"

  install_template "bdsm/bdsmrc" to "$HOME/.bdsmrc"

  seed_template "$HOME/.bdsmrc" \
    project "$project" \
    repository_url "$repository_url" \
    environment "$environment"
else
  fail "The template bdsm/bdsmrc is missing."
fi
