#!/usr/bin/env bash

if array_is_nonempty extension_args
then
  if path_exists "${extensions_development_path}/${extension_args[0]}"
  then
    enter "${extensions_development_path}/${extension_args[0]}"

    os_open "$PWD"
  else
    error "Failed to open '${extension_args[0]}'; it appears to not be installed."
  fi
else
  fail "You must specify at least one extension name."
fi
