#!/usr/bin/env bash

if (( ${#extension_args[@]} == 0 ))
then
  fail "You must specify at least one extension name."
fi

for extension in "${extensions[@]}"
do
  remove_paths "$extensions_path/$extension/"
done

succeed "Removed extensions: ${extensions}"
