#!/usr/bin/env bash

if array_is_nonempty extension_args
then
  if path_exists "${extensions_development_path}/${extension_args[0]}"
  then
    printf "${extensions_development_path}/${extension_args[0]}"
  else
    printf "." # Stay put!
    error "Failed to edit '${extension_args[0]}'; it appears to not be installed."
  fi
else
  fail "You must specify at least one extension name."
fi

