#!/bin/sh

database_extension_setup()
{
  local extension="${1}" module="${2}" path="${3}"
  shift || fail "Extension must be given as the first parameter."
  shift || fail "Module must be given as the second parameter."
  shift || fail "Path must be given as the third parameter."

  enter "${path}"

  ensure_paths_exist "modules/${module}" "bin/${module}"

  # Setup modules/package/{functions,initialize,cli}
  for file in functions initialize cli
  do
    write '#!/bin/sh' to "modules/${module}/${file}"
  done

  write "\n${module}_cli\n" append to "modules/${module}/cli"

  # setup bin/package/{...}
  for action in help initialize
  do
    write '#!/bin/sh' to "bin/${module}/${action}"
    chmod_files 0755 "bin/${module}/${action}"
  done

  write "
description \"Extension for managing ${extension} (${website_url}).\"

action \"initialize\" \"Initialize ${extension} database.\"

show_help usage
" append to "bin/${module}/help"

  for action in initialize
  do
    write "\n${module}_${action}\n" append to "bin/${module}/${action}"
  done
}

