#!/usr/bin/env bash

set +o nounset
set +o noclobber

while (( $# > 0 ))
do
  token="$1"
  shift
  case "$token" in # TODO: extension detection "did you mean"

    --help)
      extension_args=("core" "help" "$@")
      break
      ;;

    -v|--version)
      extension_args=("core" "version" "$@")
      break
      ;;

    --trace)
      true ${trace_flag:=0} $(( trace_flag++ ))
      enable_trace
      ;;

    --debug)
      true ${debug_flag:=0} $(( debug_flag++ ))
      enable_debug
      ;;

    --)
      extension_args=("$@") # Stop processing arguments.
      break
      ;;

    -*)
      error "Unknown flag '${token}'"
      ;;
    *)
      extension_args=("${token:-core} $@")
      break
      ;;
  esac
done

