#!/usr/bin/env bash

enter $bdsm_path
git submodule update extensions/internal
internal_revision_old=$(git submodule extensions/internal | cut -c 2-8)
enter $bdsm_path/extensions/internal/
git pull origin master
enter $bdsm_path
internal_revision_new=$(git submodule extensions/internal | cut -c 2-8)

if [[ "$internal_revision_old" != "$internal_revision_new" ]]
then
  touch CHANGELOG
  git submodule summary | cat - CHANGELOG | tee CHANGELOG.new
  mv CHANGELOG.new CHANGELOG
fi
