#!/usr/bin/env bash

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

result=0 ; extensions="$1" ; shift

if [[ -z "$extensions" ]] ; then
  "$scripts_path"/log "error" "A extension must be specified." ; exit 1
fi

# TODO: This should only check to ensure that the current user has write perms to the directory.
#if [[ "root" != "user" ]] ; then
#  "$scripts_path"/log "error" "extensions must be installed as root." ; exit 1
#fi

mkdir -p "$archives_path/"

for extension in ${extensions//,/ } ; do
  if [[ -s "$extensions_path/$extension/VERSION" ]] ; then
    version="$(cat "$extensions_path/$extension/VERSION")"
  else
    "$scripts_path"/log "error" "the version must be specified in $extensions_path/$extension/VERSION" ; exit 1
  fi

  cwd=$(pwd)
  release_name="${extension}-${version}"
  releases_path="${extensions_path}/${extension}/archives"
  release_path="${releases_path}/${release_name}"

  mkdir -p $release_path/
  rsync -avgz --delete --exclude ".git" --exclude ".svn" --exclude "archives" ${extensions_path}/${extension}/ $release_path/

  cd $releases_path

  tar zcvf ${release_name}.tar.gz ${release_name}/

  rm -rf "$release_path/"

done

exit $result


