#!/usr/bin/env bash

#
# BDSM system module DSL functions
#
init_scripts_path()
{
  if [[ $UID -eq 0 ]] ; then
    case "$MACHTYPE" in
      *darwin*)
        # For now stick with say, /usr/local/bin
        printf "${prefix_path}/bin"
        ;;
      *linux-gnu*|*)
        if [[ -d "/etc/init.d" ]] ; then
          printf "/etc/init.d"
        elif [[ -d "/etc/rc.d" ]] ; then
          printf "/etc/rc.d"
        else
          fail "Unknown init scripts directory (/etc/init.d or /etc/rc.d not found)."
        fi
        ;;
    esac

  else
    printf "$HOME/.init.d/"
  fi
}

# TODO: OS type functions.
