#!/usr/bin/env bash

running_pid=$(ps auxww | grep "[t]hin" | awk '/'$application.thin.$socket'.sock/{print $2}')
$scripts_path/log "info" "running_pid: $running_pid"

if [ -f "$pid_dir/$pid_file" ]; then
  pid_file_pid=$(cat $pid_dir/$pid_file)
fi
$scripts_path/log "info" "pid_file_pid: $pid_file_pid"


if [ -n "$pid_file_pid" ] && [ "$pid_file_pid" -gt 0 ]; then
  $scripts_path/log "info" "Stopping thin application $application running on socket $socket."
  /usr/bin/thin stop -P $pid_dir/$pid_file -t 5

fi

if [ -n "$running_pid" ] && [ "$running_pid" -gt 0 ] && ["$running_pid" != "$pid_file_pid" ] ; then
  $scripts_path/log "info" "Sending SIGQUIT to thin $application on sock $socket."
  kill -QUIT $running_pid 2>/dev/null; true
  sleep 5
fi

log "we will now ensure the thin has quit (killing both just in case there are two running from some mishap)"

for pid in $running_pid $pid_file_pid ; do
  $scripts_path/log "info" "Force killing $1 to ensure it has stopped."
  kill -9 $pid 2>/dev/null; true
done
