#!/usr/bin/env bash

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

result=0 ; services="$1" ; shift
releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
if [[ -z "$services" ]] ; then
  "$scripts_path"/log "error" "A service must be specified." ; exit 1
fi
# TODO: Should we allow user installs?...
if [[ "root" != "user" ]] ; then
  "$scripts_path"/log "error" "Services must be installed as root." ; exit 1
fi

if [[ -z "$service" ]] ; then
  $scripts_path/log "error" "A service must be specified to edit." ; exit 1
else
  if [[ ! -d "$services_path/service" ]] ; then
    rsync -avgz "$services_path/service/templates/" "$services_path/$service/"
    cd "$services_path/$service/"
    ${EDITOR:-vi} .
  else
    "$scripts_path"/log "error" "Service $service already exists in $services_path/$service!." ; exit 1
  fi
fi

exit $?
