#!/usr/bin/env bash

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

result=0 ; services="$1" ; shift
if [[ -z "$services" ]] ; then
  "$scripts_path"/log "error" "A service must be specified." ; exit 1
fi

releases_url="${releases_url:-$($scripts_path/db "$config_path/bdsm" "releases_url")}"
service_url="${service_url:-$($scripts_path/db "$config_path/bdsm" "service_url")}"
# TODO: Should we allow user installs?...
if [[ "root" != "user" ]] ; then
  "$scripts_path"/log "error" "Services must be installed as root." ; exit 1
fi

for service in ${services//,/ } ; do
  if [[ -d "$services_path/$service" ]] ; then
    rm -rf "$services_path/$service"
  else
    "$scripts_path"/log "error" "$services_path/$service" ; result=1
  fi

  if [[ -d "$services_path/$service/" ]] ; then
    rm -rf "$services_path/$service/"
    "$scripts_path"/log "info" "$service removed."
  else
    "$scripts_path"/log "info" "$service is already non-existant."
  fi
done

exit $result
