#!/usr/bin/env bash

command_exists()
{
  local _name="${1:-}"
  [[ -n "${_name}" ]] || fail "No function name given."
  command -v "${_name}" > /dev/null 2>&1
}

is_a_function()
{
  local _name="${1:-}"
  [[ -n "${_name}" ]] || fail "No function name given."
  declare -f "${_name}" >/dev/null 2>&1
}

