#!/usr/bin/env bash

source $extension_scripts_path/initialize

if [[ -z "$master_pid" ]] ; then
  echo -e "Nginx is not running, starting."
  nginx -t -c /etc/nginx/nginx.conf
else
  echo -e "Restarting Nginx, pid $master_pid."
  kill -HUP $master_pid
fi
