#!/usr/bin/env bash

true \
  "${releases_url:=$(hash_file "$config_path/bdsm" "releases_url")}"\
  "${extension_url:=$(hash_file "$config_path/bdsm" "extension_url")}" \
  "${extensions_repository_url:=$(hash_file "$config_path/bdsm" "extensions_repository_url")}" \
  ${remote:="origin"} \
  ${branch:="master"}

extensions_src_path="${src_path}/extensions"

ensure_paths_exist "${extensions_src_path}"

enter "${extensions_src_path}"

