#!/usr/bin/env bash

http://www.rabbitmq.com/releases/rabbitmq-server/v1.7.0/rabbitmq-server-1.7.0.zip

gnodename",

# "RabbitMQ Erlang node name",
# "The Erlang node name for this server.  The default is rabbit.",
# default: "rabbit"

gaddress",
# "RabbitMQ server IP address",
# "IP address to bind.  The default is any.",
# default: "0.0.0.0"

gport",
# "RabbitMQ server port",
# "TCP port to bind.  The default is 5672.",
# default: "5672"

glogdir",
# "RabbitMQ log directory",
# "Path to the directory for log files.  The default is /var/log/rabbitmq.",
# default: "/var/log/rabbitmq"

gmnesiadir",
# "RabbitMQ Mnesia database directory",
# "Path to the directory for Mnesia database files.  The default is /var/lib/rabbitmq/mnesia.",
# default: "/var/lib/rabbitmq/mnesia"

gcluster",
# "RabbitMQ clustering",
# "Whether to activate clustering.  The default is no.",
# default: "no"

gcluster_config",
# "RabbitMQ clustering configuration file",
# "Path to the clustering configuration file, if cluster is yes.  The default is /etc/rabbitmq/rabbitmq_cluster.config.",
# default: "/etc/rabbitmq/rabbitmq_cluster.config"

# "RabbitMQ cluster disk nodes",
# "Array of member Erlang nodenames for the disk-based storage nodes in the cluster.  The default is [].",
gcluster_disk_nodes",

gerlang_cookie",
# "RabbitMQ Erlang cookie",
# "Access cookie for clustering nodes.  There is no default."

[<%= @node[:rabbitmq][:cluster_disk_nodes].map{|n| "\'#{n}\'"}.join(',') %>].

