#!/bin/sh

typeset version_pattern _ignored_args _token index

version_pattern="[[:digit:]]##.[[:digit:]]##.[[:digit:]]##"

#TODO: merge this code to extension_cli

_ignored_args=()

for (( index=1 ; index <= ${#extension_args[@]} ; index++ ))
do
  _token="${extension_args[$index]}"
  if [[ -n "${ZSH_VERSION}" ]]
  then setopt extended_glob ; else shopt -s extglob ; fi

  case "${_token}" in
    (--trace)
      export trace_flag=1
      enable_trace
      ;;

    (head|master)
      extension_action="head"
      ;;

    # With the event of begin able to call functions from bin files on the
    # command line this can no longer be done here. ~ Wayne
    # (${version_pattern}) # x.y.z
    #   # TODO: Set env vars instead of calling the method.
    #   version="${_token}"
    #   extension_action="version"
    #   ;;

    (latest|release)
      extension_action="latest"
      ;;

    *)
      _ignored_args+=("${_token}")
      ;;
  esac
done

extension_args=( "${_ignored_args[@]}" )

extension_cli

