#!/bin/sh

true \
  "${src_path:="${sm_path}/src"}" \
  "${md5_path:="${sm_path}/md5"}" \
  "${archives_path:="${sm_path}/archives"}" \
  "${archive_format:=tar.gz}" \
  "${package_name:=${extension}}" \
  "${repository_url:="git://github.com/sm/sm"}"

[[ -n "$extensions_url" ]] || __sm.config.read sm defaults extensions_url
[[ -n "$releases_url"   ]] || __sm.config.read sm defaults releases_url

true \
  ${remote:="origin"} \
  ${branch:="master"}

__sm.version # Load the BDSM framework version.

user="$USER"

extensions_src_path="${src_path}/extensions"

export source_path
