#!/usr/bin/env bash

description "BDSM Extension manager."

action "update repository" \
  "Update main BDSM Extension repository from remote (git)."

action "install" \
  "install named extension"

action "create" \
  "create a new extension from the default template in the current directory."

action "list available" \
  "List extensions available in the main repository."

action "list" \
  "List all installed extensions."

action "list installed" \
  "List all installed extensions."

action "update {name {...}}" \
  "update extension(s) {name {...}}"

action "update all" \
  "update all installed extensions"

resource "http://bdsm.beginrescueend.com/extensions/"

show_help usage

