#!/bin/sh

internal_time_initialize()
{
  [[ -n "${timestamp:-}" ]] || __sm.timestamp.set
}

__sm.timestamp.set()
{
  typeset -g timestamp
  timestamp="$( __sm.timestamp.show.new $1 )"
}

__sm.timestamp.show.new()
{
  # Set the format to either the first parameter, if nonempty or to the
  # iso-something format ;) otherwise. Use the date command with the format
  # string and print the result to the STDOUT of the calling environment.
  typeset _format
  _format="${1:-"%Y-%m-%dT%H:%M:%S"}"
  date +"${_format}"
}

__sm.timestamp.show.current()
{
  printf "${timestamp}\n"
}
