#!/usr/bin/env bash

#
# user$ bdsm extend github <local ext name> <github username>/<github repo name>
#

name=${extension_args[0]}
extension_uri="git://github.com/${extension_args[1]}.git"
extension_src_path=$extensions_src_path

fetch_extensions_git_repository "${extension_uri}"
extension_install "${name}" "${extension_uri//\//_}"
