#!/usr/bin/env bash

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

if [[ "root" = $(whoami) ]] ; then
  echo "Must be run as the project user."
  exit 1
fi

for dir in config log pids sockets "public/assets" tmp  ; do
  mkdir -p "$project_path/shared/$dir"
done

touch $project_path/shared/config/database.yml

touch $project_path/.bash_profile

if ! awk "/^project/" "$HOME/.bash_profile" ; then
  echo "export project=\"$(user)\"" >> $HOME/.bdsmrc
fi

if ! awk "/^environment/" "$HOME/.bash_profile" ; then
  echo "export environment=\"production\"" >> $HOME/.bdsmrc
fi

if ! awk "/^RAILS_ENV/" "$HOME/.bash_profile" ; then
  echo "export RAILS_ENV=\"\$environment\"" >> $HOME/.bdsmrc
fi

if ! awk '/current\/\.bdsmrc/' "$HOME/.bash_profile" ; then
  echo 'if [[ -d $HOME/current ]] && [[ -f $HOME/current/.bdsmrc ]] ; then source $HOME/current/.bdsmrc ; fi' >> $HOME/.bash_profile
fi

if ! awk '/current\/\.rvmrc/' "$HOME/.bash_profile" ; then
  echo 'if [[ -d $HOME/current ]] && [[ -f $HOME/current/.rvmrc ]] ; then source $HOME/current/.rvmrc ; fi' >> $HOME/.bash_profile
fi
cp $HOME/.bash_profile $HOME/.bashrc

if [[ ! -s "$HOME/.rvm/scripts/rvm" ]] ; then
  mkdir -p ~/.rvm/src ; cd ~/.rvm/src
  if [[ -d rvm/.git ]] ; then
    cd rvm
    git reset --hard HEAD
    git pull origin master
    ./install
  else
    git clone git://github.com/wayneeseguin/rvm.git && cd rvm && ./install
  fi
fi

if [[ ! -s "$project_path/shared/config/database.yml" ]] ; then
  echo -e "${environment}: &defaults\n  adapter: ${database_server:-postgresql}\n  username: $project\n  password: '$project'\n  database: ${project}_${environment}\n  pool: 5\n  timeout: 5000" >> "$project_path/shared/config/database.yml"
fi

if [[ -s $project_path/shared/$project/.rvmrc ]] ; then source $project_path/shared/$project/.rvmrc ; fi

if [[ ! -z "$database_server" ]] ; then
  if [[ "postgresql" = "$database_server" ]] ; then
    gem install pg --no-rdoc --no-ri
  elif [[ "mysql" = "$database_server" ]] ; then
    gem install mysql --no-rdoc --no-ri
  else
    gem install sqlite --no-rdoc --no-ri
  fi
fi

