#!/bin/sh

ext_help()
{
  modules ext/help

  description "BDSM extension ext management"

  action "ext" "List installed ext."
  action "ext known" "List extension ext that can be installed."
  action_separator
  action "ext install all" "Install all extension ext found on the known list."
  action "ext install {name}" "Install extension {name} found on the known list."
  action "ext install {name} {uri}" "Install extension {name} from the given {uri}."
  action "ext add" "Shortcut for install."
  action_separator
  action "ext update all" "Update all extension ext using remembered uris."
  action "ext update {name}" "Update extension {name} using remembered uri."
  action "ext up" "Shortcut for update."
  action_separator
  action "ext uninstall {name}" "Remove extension {name}."
  action "ext del" "Shortcut for uninstall."
  action_separator
  action "ext help" "Show this help."

  show_help usage
}

ext_list()
{
  local extensions COLUMNS=80

  if extensions_in "${exts_system_path}"
  then
    log "exts: #system"
    echo ${found_extensions[@]} | xargs -s ${COLUMNS} | xargs -I '{}' echo "  - {}"
  else
    log "# No single system extensions (exts) are currently installed."
  fi

  if [[ "${exts_system_path}" != "${exts_user_path}" ]]
  then
    if extensions_in "${exts_user_path}"
    then
      log "exts: #user"
      echo ${found_extensions[@]} | xargs -s ${COLUMNS} | xargs -I '{}' echo "  - {}"
    else
      log "# No single user extensions (exts) are currently installed."
    fi
  fi
}

ext_list_known()
{
  local COLUMNS=80

  printf "# %18s | %s\n" "Extension name" "Repository"

  while read line
  do
    printf "%20s   %s\n" "${line/=*}" "${line/*=}"
  done < "${sm_path}/core/cli/config/known_ext"
}

ext_install()
{
  local _name _names="${1:-}" _uri=${2:-}
  shift || fail "No ext name was given."

  _names=(${_names//,/ })
  _extension_namespace="${exts_user_path#${sm_path}\/}"
  _extension_namespace="${_extension_namespace#${user_sm_path}\/}"

  for _name in ${_names[@]}
  do
    log_step "Installing ${_name} in ${_extension_namespace//\// }" \
      extension_install "${_name}" ${_uri}
  done
}

extension_install()
{
  local _name="${1:-}"
  shift || fail "No extension name was given."

  local _uri="${1:-}"
  shift || _uri=$( awk -F= "/^${_name}=/ {print \$2 }" < "${sm_path}/core/cli/config/known_ext" | tail -n 1 )

  [[ -n "${_uri}" ]] ||
    error "uri not given and cannot find ${_name} in known extensions."

  local _version="head"
  if [[ "${_name}" == *:* ]]
  then
    _version="${_name/*:}"
  fi

  local _identifier="$(scm_identifier "${_uri}")"

  if fetch_uri "${_uri}" "${src_path}/${_identifier}" "$@"
  then
    versionedfs add \
      path "${exts_user_path}" name "${_name}" version "${_version}" \
      source "${src_path}/${_identifier}"

    versionedfs add \
      path "${exts_user_path}" name "${_name}" version "${_version}"
  else
    return $?
  fi
}

ext_install_all()
{
  local _ext _name _uri COLUMNS=80
  while read _ext
  do
    [[ "${line}" != \#* ]] || continue
    _name="${_ext/=*}"
    _uri="${_ext/*=}"
    exts_install "${_name}" "${_uri}" --on-fail true
  done < "${sm_path}/core/cli/config/known_exts"
}

ext_update()
{
  local _name _uri
  (( $# > 0 )) ||
    error "Cannot update extension ext without name."

  for _name in "$@"
  do
    if [[ ! -d "${exts_user_path}/active/${_name}" ]]
    then
      if [[ -d "${exts_system_path}/active/${_name}" ]]
      then
        error "Extension ${_name} is in system exts and cannot be updated."
      else
        error "Extension ${_name} does not exist."
      fi
    fi

    if [[ ! -s "${exts_user_path}/active/${_name}/.uri" ]]
    then
      warn "Extension ${_name} does not contain stored uri."
      continue
    fi

    _uri=$( cat "${exts_user_path}/active/${_name}/.uri" )

    if [[ -z "${_uri}" ]]
    then
      warn "Extension ${_name} does not contain stored uri."
    else
      ext_install "${_name}" "${_uri}"
    fi
  done
}

ext_update_all()
{
  local _name _entries
  shopt -s nullglob
  _entries=(
  "${exts_user_path}"/*
  )
  shopt -u nullglob

  for _name in  "${_entries[@]}"
  do
    [[ -d "${sets_user_path}/active/${_name}"  ]] || continue

    case "${_name##*/}" in
      (\*)
        error "No extensions found for update."
        ;;
      (*)
        ext_update "${_name##*/}"
        ;;
    esac
  done
}

ext_uninstall()
{
  local _name="$1"
  case "${_name}" in
    */*|.|..)
      error "Please specify a valid extension name."
      ;;
  esac

  if [[ ! -d "${exts_user_path}/active/${_name}" ]]
  then
    if [[ -d "${exts_system_path}/active/${_name}" ]]
    then
      error "Extension ${_name} is in system exts and cannot be uninstalled."
    else
      error "Extension ${_name} does not exist."
    fi
  fi

  versionedfs remove \
    path "${exts_user_path}" name "${_name}"
}

ext_check_availability()
{
  local _ext _line _args=($@)

  # TODO: refactor this to take argument of uri to check instead.
  #       provide check_known_exts_availability or some such to wrap this.
  while read _ext
  do
    case "$line" in
      (^#)
        true # Skipt comment lines
        ;;
      (*)
        while read _line
        do
          [[ "${_line}" == Status* ]] || continue
          echo "${_ext/=*}" "${_line/*:}"
          break
        done < <(curl -s --head https://github.com/sm/sm_"${_ext/=*}")
        ;;
    esac
  done < "${sm_path}/core/cli/config/known_ext"
}

