#!/usr/bin/env zsh

process2_start()
{
  log step "Starting $1" \
    process2 start \
    name $1 \
    timeout 10 \
    command "$@"
}

process2_stop()
{
  log step "Stoping $1" \
    process2 stop \
    name $1 \
    timeout 10
}

process2_restart()
{
  log step "Stoping $1" \
    process2 stop \
    name $1 \
    timeout 10
  log step "Starting $1" \
    process2 start \
    name $1 \
    timeout 10 \
    command "$@"
}

process2_running()
{
  log step "$1 ..."
  if
    process2 running name $1
  then
    log_step_message="$1 running."
    log step succ
  else
    typeset _status=$?
    log_step_message="$1 not running"
    log step fail
    return ${_status}
  fi
}

process2_shedule()
{
  log step "Adding to cron every 5 minutes check $1"
  if echo "*/5 * * * * cd \"$PWD\" ; \"$(which sm)\" process2 start $*" | cron edit group $1
  then log step succ
  else
    typeset _status=$?
    log step fail
    return ${_status}
  fi
}

process2_unshedule()
{
  log step "Removing from cron checking $1" \
    cron remove group $1
}

process2_sheduled()
{
  log step "$1 ..."
  if cron group $1 | grep "" >/dev/null
  then
    log_step_message="$1 sheduled."
    log step succ
  else
    typeset _status=$?
    log_step_message="$1 not sheduled"
    log step fail
    return ${_status}
  fi
}
