#!/bin/sh

# ## directory\_get()
#
#
#
# Code Walkthrough
path_get()
{
  local initial_pwd="$PWD" _source="${1:-}" _target="${2:-}"

  shift || fail "source path must be the first parameter to path_get()."
  shift || fail "target path must be the second parameter to path_get()."

  if rm -rf "${_target}" > /dev/null 2>&1
  then
    if cp -fR ${_source} "${_target}" >/dev/null 2>&1
    then
      echo "$(cd "${_source}"; pwd)" > "${_target}/.uri"
    else
      fetch_error copy_failed from=${_source} to=${_target}
    fi
  else
    fetch_error cannot_remove path=${_target}
  fi
}
