#!/bin/sh

package_extension_setup()
{
  local extension="${1:-}" module="${2:-}" path="${3:-}" ${language:=shell}
  shift || fail "Cannot setup package extension; no extension name given."
  shift || fail "Cannot setup package extension; no module name given."
  shift || fail "Cannot setup package extension; no path given."

  for action in install uninstall update activate deactivate
  do
    write "${action}=${module}_${action}()" append to "${path}/actions.map"
  done
}

