#!/usr/bin/env bash

# Load System Configuration, if it exists.
[[ -s "/etc/bdsmrc" ]] && . /etc/bdsmrc

# Load User Configuration, if it exists.
[[ -s "$HOME/.bdsmrc" ]] && . "$HOME/.bdsmrc"

# The default prefix is /usr/local,
# this should be set to where BDSM is installed to in /etc/bdsmrc
prefix="${prefix:-/usr/local}"

[[ "$prefix" = "$HOME" ]] \
  && { : "${bdsm_path:="${prefix}bdsm"}" } \
  || { : "${bdsm_path:="${prefix}/bdsm"}" }

{ : "${modules_path:="${bdsm_path}/modules"}" }

# Load DSL and initialize BDSM core itself, manually.
source "${PWD}/modules/bash/core/dsl"

mkdir -p log tmp

# Load fundamental Module DSL's
for module in logging trace filesystem core ; do
  for file in dsl initialize ; do
    source "${PWD}/modules/bash/${module}/${file}"
  done
done

source_files "${PWD}/extensions/core/modules/bash/dsl" \
  "${PWD}/extensions/core/modules/bash/initialize" \
  "${PWD}/extensions/core/modules/bash/cli" \
  "${PWD}/extensions/core/bin/install"

