#!/usr/bin/env bash

source ./scripts/bash/bdsm

source_files \
  scripts/functions \
  scripts/initialize

directories=$(bin scripts config extensions)

(
  cd "${bdsm_path}"
  ensure_paths_exist "${directories[@]}"
)

copy_directories_to "${bdsm_path}" \
  "${directories[@]}"

copy_files_to "${bdsm_path}/" \
  LICENCE \
  VERSION \
  README

ensure_files_exist \
  "${config_path}/user" \
  "${config_path}/db"

remove_files \
  "${prefix}/bin/bdsm"

link \
  "${bin_path}/bdsm" \
  "${prefix}/bin/bdsm"

