#!/usr/bin/env bash
#
# Badass Delectable Scripting Management (BDSM) Framework
#
# Copyright (c) 2009-2011 Wayne E. Seguin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Record this early on.
initial_pwd="$PWD"

# Path to load everything from.
sm_path="$PWD"
modules_path="${sm_path}/core/sm/modules"

export initial_pwd sm_path modules_path

# Basic options parsing.
. "${modules_path}/shell/core/cli"

# Initialize BDSM.
. "${modules_path}/shell/core/initialize"
