#!/usr/bin/env zsh
#
# S{cripting,ystem,tack} Management (SM) Framework (Core)
#
# Copyright (c) 2009-2011 Wayne E. Seguin
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit # exit on errors in early stage before logging is initialized
set -o nounset # do not allow unset variables processing

initial_pwd="$PWD"
sm_path="$PWD"
__sm_modules_path="${sm_path}/core/sm/shell"

export initial_pwd sm_path __sm_modules_path initial_pwd

. "${__sm_modules_path}/core/cli"
. "${__sm_modules_path}/core/initialize"
