#!/bin/bash

hosts="$*"
if [[ -z "$hosts" ]] ; then
  echo "hosts must be specified."
  exit 1
fi

set -x

for host in $hosts ; do

  echo "Syncing to $host"

  rsync -avgz --delete --exclude ".git" --exclude "site/" --exclude "test/" --exclude "logo/" --exclude "gems/" --exclude "release/" --exclude "releases/" ./ $host:/usr/local/src/bdsm/ &&
  ssh $host 'cd /usr/local/src/bdsm && ./install'
done
exit $?
