#!/usr/bin/env bash

list_help()
{
  log "

Usage:

  bdsm extension list <action>

Actions:

  installed - List installed extensions
  available - List available extensions
  help      - Show this help text

"
}

list_installed()
{
  extensions=($(extensions_installed))

  if array_is_nonempty extensions
  then
    log "${extensions[*]}"
  else
    log "# No extensions currently installed."
  fi
}

list_available()
{
  if ! directory_exists "${extensions_src_path}"
  then
    fetch_extensions_repository
  fi

  extensions=($(extensions_available))

  if array_is_nonempty extensions
  then
    log "${extensions[*]}"
  else
    log "No extensions found (in '${src_path}'). Run 'bdsm extensions clone' to make them available. "
  fi
}

modules extensions

extension_action=${extension_args[0]}

case "$extension_action" in
  installed)
    list_installed
  ;;

  available)
    list_available
  ;;

  help|usage)
    list_help
  ;;

  *)
    list_installed
  ;;
esac
