#!/usr/bin/env bash

install_path="${bdsm_path}"
modules core/install

action="${extension_args[0]}"

case "${action}" in

  head)
    update_internal_extensions "wayneeseguin"
    ;;

  version) # x.y.z
    NIY
#    install_release
    ;;

  latest)
    NIY
#    fetch_version
#    install_release
    ;;

  *)
    if [[ -f "${action}" ]]
    then
      NYI #local file installation
    else
      update_internal_extensions "${action:-wayneeseguin}"
    fi
    ;;
esac

