#!/usr/bin/env bash

log()
{
  printf "$*\n"
  return $?
}

error()
{
  printf "\n\nERROR: $*\n\n"
}

warn()
{
  printf "\n\nWARNING: $*\n\n"
}

debug()
{
  [[ ${debug_flag:-0} -eq 1 ]] && printf "DEBUG: $*\n"
}

succeed() {
  log "\n$*\n"
  exit 0
}

fail() {
  error "$*"
  backtrace
  exit 1
}

backtrace()
{
  local _source _function _line

  printf "%s\n" "Call Trace:"

  for (( index = 1 ; index < ${#FUNCNAME[@]} ; ++index )) ; do
    # sourcefile=${BASH_SOURCE[${n}]//*\/}
    # sourcefile=$(basename ${BASH_SOURCE[${n}]})
    # line="${LINENO} > "
    _source="${BASH_SOURCE[${index}]##${bdsm_path}}"
    _function="${FUNCNAME[${index}]:+${FUNCNAME[${index}]}()}"
    _line=${BASH_LINENO[$(( index - 1 ))]}

    printf "%5d. " "$((${#FUNCNAME[@]} - index ))" 1>&2
    printf "%55s" "${_source##$PWD\/} " 1>&2
    printf "%20s" "${_function} : ${_line}" 1>&2
    printf "%10s\n" "${_function} : ${_line}" 1>&2
  done
}
