#!/usr/bin/env bash

log()
{
  printf "%s\n" "$*"
  return $?
}

error()
{
  printf "\n\nERROR: %s\n\n" "$*"
}

warn()
{
  printf "\n\nWARNING: %s\n\n" "$*"
}

debug()
{
  (( debug_flag == 1 )) && printf "DEBUG: %s\n" "$*"
}

succeed() {
  log "\n$*\n"
  exit 0
}

fail() {
  error "$*"
  backtrace
  exit 1
}

