#!/usr/bin/env bash

log()
{
  printf "$*\n"
  return $?
}

error()
{
  printf "\n\nERROR: $*\n\n"
}

warn()
{
  printf "\n\nWARNING: $*\n\n"
}

debug()
{
  (( debug_flag == 1 )) && printf "DEBUG: $*\n"
}

succeed() {
  log "\n$*\n"
  exit 0
}

fail() {
  error "$*"
  backtrace
  exit 1
}

