#!/usr/bin/env zsh

__sm_variables_file_read()
{
  eval "$1=\"\$(cat \"\${2:-\$1}\")\""
}

__sm_variables_file_write()
{
  eval "echo \"\$$1\"" > "${2:-$1}"
}

__sm_variables_file_read_one()
{
  eval "${2//-/_}=\"\$(sed '/^$2=/! d; s/^$2=//' < \"\$1\")\""
}

__sm_variables_file_read_many()
{
  typeset __sm_variables_file
  __sm_variables_file="$1"
  shift

  for name
  do
    __sm_variables_file_read_one "${__sm_variables_file}" "$name"
  done
}

__sm_variables_file_read_all()
{
  typeset __sm_variables_file
  __sm_variables_file="$1"
  shift

  while read name
  do
    __sm_variables_file_read_one "${__sm_variables_file}" "$name"
  done \
    < <( awk -F= '{print $1}' < "${__sm_variables_file}" )
  # n+1 read is slow but it's the only safe one
}

__sm_variables_file_write_one()
{
    eval "sed -i '/^$1=/ s/^.*$/$1='\"\${${1//-/_}}\"'/' \"\${__sm_variables_file}\""
}

__sm_variables_file_write_many()
{
  typeset __sm_variables_file
  __sm_variables_file="$1"
  shift

  while
    (( $# ))
  do
    __sm_variables_file_write_one "${__sm_variables_file}" "$1"
    shift
  done
}
