#!/usr/bin/env bash

echo -e "
Usage
  $0 {install,setup,start,stop,help}
Actions
  install  - Install the sinatra gem.
  setup    - Place the config.sinatra template in $current_path/config/config.sinatra
  start    - Startup sinatra.
  stop     - Stop sinatra.
  help     - Display this help text.
"
exit $?
