#!/bin/sh

# TODO: Rework this into a 1.0.0 module API

step()
{
  local name
  name="$1"

  (( $# )) && shift || __sm.log.fail "Cannot take step as no step name given;"\
    "step [name] <- missing name."

  start_step "$name"

  if command exists before_step
  then
    before_step "$name" "$@"
  fi

  "$name" "$@"

  if command exists after_step
  then
    after_step "$name" "$@"
  fi
}

steps()
{
  for step in $@
  do
    step "${step}"
  done
}

api_steps_initialize()
{
  steps_started=()
}

start_step()
{
  steps_started+=( "$1" )
}

retreat()
{
  local step

  if [[ -z "${steps_started}" ]]
  then
    steps_started=( "$@" )
  fi

  while [[ -n "${steps_started}" ]]
  do
    array pop steps_started step
    if command exists "fail_${step}"
    then
      "fail_${step}"
    fi

    if command exists after_step
    then
      after_step "fail_${step}"
    fi
  done
}

