#!/bin/sh

#
# # Array Module
#
:
ext_array_initialize()
{
  if [[ -n "${ZSH_VERSION:-}" ]]
  then
    __array_start=1
  else
    __array_start=0
  fi
}

# Examples
#
#     user$ cat $HOME/test
#     the_array=(1 2 3 4 5)
#     if array_is_nonempty the_array
#     then
#       log "the array is not empty."
#     else
#       log "the array is empty."
#     fi
#
#     the_array=()
#     if array_is_nonempty the_array
#     then
#       log "the array is not empty."
#     else
#       log "the array is empty."
#     fi
#
#     user$ $HOME/test
#     the array is not empty.
#     the array is empty.
#
# ### Code Walkthrough

array_is_nonempty()
{
  trace_filter array
  local _array_name="${1:-}"
  shift || fail "Array name was not given."

  eval "(( \${#${_array_name}[@]} > 0 ))"
}

# Examples
#
#     user$ the_array=()
#     user$ array_is_empty the_array
#     user$ echo $?
#     0
#
#     user$ the_array=(1 2 3 4 5)
#     user$ array_is_empty the_array
#     user$ echo $?
#     1
#
# ### Code Walkthrough
array_is_empty()
{
  trace_filter array
  local _array_name="${1:-}"
  shift || fail "Array name was not given."
  eval "(( \${#${_array_name}[@]} == 0 ))"
}

# Examples
#
#     user$ the_array=(1 2 3 4 5)
#     user$ array_length the_array
#     5
#
# ### Code Walkthrough
array_length()
{
  trace_filter array
  local _array_name="${1:-}" _length
  shift || fail "Array name was not given."
  eval "_length=\${#${_array_name}[@]}"
  printf ${_length}
  return 0
}

# Examples
#
#     $ the_array=(one two three four five)
#     $ array_last_element the_array
#     five
#
# ### Code Walkthrough
array_last_element()
{
  trace_filter array
  local _array_name="${1:-}" _length _element
  shift || fail "Array name was not given."

  eval "_length=\${#${_array_name}[@]}"
  eval "_element=\"\${${_array_name}[${_length}]}\""

  printf "%{_element}"
}

# Examples
#
#     $ the_array=(one two three four five)
#     $ array_first_element the_array
#     one
#
# ### Code Walkthrough
array_first_element()
{
  trace_filter array
  local _array_name="${1:-}" _element _array_length

  shift || fail "Array name was not given."

  eval "_array_length=\"\${#${_array_name}[@]}\""
  (( _array_length )) || return 1
  eval "_element=\"\${${_array_name}[0]}\""

  printf "${_element}"
}

# Examples
#
#     $ the_array=(1 2 3 4 5)
#     $ array_push the_array 6
#     $ array_join the_array # print the contents of the array, space-separated.
#     1 2 3 4 5 6
#
# ### Code Walkthrough
array_push()
{
  trace_filter array
  local _array_name="${1:-}"
  shift || fail "Array name not given."

  if eval "(( \${#${_array_name}[@]} > 0 ))"
  then
    local _element _elements=("$@")

    (( ${#_elements[@]} )) || fail "No elements were given."

    for _element in "${_elements[@]}"
    do
      eval "${_array_name}+=(\"\${_element}\")"
    done
  fi
}

# Examples
#
#     user$ the_array=(1)
#     user$ array_append the_array 2 3 4 5
#     user$ array_join the_array # print the contents of the array.
#     space separated.
#     1 2 3 4 5
#
# ### Code Walkthrough
array_append()
{
  trace_filter array
  local _array_name="${1:-}"
  shift || fail "No array name was given."

  local _element _elements=("$@")

  (( ${#_elements[@]} )) || fail "No elements were given."

  for _element in "${_elements[@]}"
  do
    eval "${_array_name}+=(\"\${_element}\")}"
  done
}

# Examples
#
#     user$ cat $HOME/test
#     #!/bin/sm
#
#     modules array
#
#     my_array=(1 2 3 4)
#     echo ${my_array[@]}
#     array_pop my_array my_var
#     echo :$my_var:${my_array[@]}:
#
#     user$ $HOME/test
#     1 2 3 4
#     :4:1 2 3:
#
# ### Code Walkthrough
array_pop()
{
  trace_filter array

  local _array_name="${1:-}" temp_array=() index _variable="${2:-}"

  shift || fail "Array name was not given."

  eval "(( \${#${_array_name}[@]} ))" ||
    fail "Array '${_array_name}' was empty."

  variable_is_empty _variable ||
    eval "${_variable}=\${${_array_name}[\${#${_array_name}[@]}-1]}"

  eval "unset ${_array_name}[\${#${_array_name}[@]}-1]"
  #TODO: check if this one is required:
  eval "${_array_name}=( \"\${${_array_name}[@]}\" ) "
}

# Examples
#
#     user$ cat $HOME/test
#     #!/bin/sm
#     modules ext/array
#
#     my_array=(1 2 3 4)
#     echo ${my_array[@]}
#     array_shift my_array
#     echo ${my_array[@]}
#
#     user$ $HOME/test
#     1 2 3 4
#     1
#     2 3 4
#
# ### Code Walkthrough
array_shift()
{
  trace_filter array
  local _array_name="${1:-}" temp_array=() index _variable="${2:-}"
  shift || fail "Array name was not given."

  variable_is_empty _variable || eval "${_variable}=\${${_array_name}[0]}"

  unset "${_array_name}[0]"
  eval "${_array_name}=( \"\${${_array_name}[@]}\" ) "
}

# Examples
#
#     $ the_array=(2 3 4 5)
#     $ array_unshift 1
#     user$ array_join the_array # print contents of the array, space-separated.
#     1 2 3 4 5
#
#     $ the_array=(4 5)
#     $ array_unshift 3 2 1
#     user$ array_join the_array # print contents of the array, space-separated.
#     1 2 3 4 5
#
# ### Code Walkthrough
array_unshift()
{
  trace_filter array
  local _array_name="${1:-}"
  shift || fail "Array name was given."

  local _elements=("$@")

  (( ${#_elements[@]} )) || fail "No elements were given."

  eval "${_array_name}=(\"${_elements[@]}\" \"\${${_array_name}[@]}\")"
}

# Examples
#
#     $ the_array=(1 2 3 4 5)
#     $ array_join the_array
#     1 2 3 4 5
#
#     $ array_join the_array '.'
#     1.2.3.4.5
#
# ### Code Walkthrough
array_join()
{
  trace_filter array
  local _array_name="${1:-}"
  shift || fail "Array name was not given."
  local IFS=${1:-' '}
  eval "printf \"\${${_array_name}[*]}\""
}

# Examples
#
#     $ the_array=(billie bob joe)
#     $ array_largest the_array
#     billie
#
# ### Code Walkthrough
array_largest()
{
  trace_filter array
  local _array_name="${1:-}" _index _largest=""
  shift || fail "No array variable name was given."

  eval "
  for (( _index=0 ; _index < \${#${_array_name}[@]} ; _index++ ))
  do
    if (( \${#${_array_name}[\${_index}]} > \${#_largest} ))
    then
      _largest=\${${_array_name}[\${_index}]}
    fi
  done
  "
  printf "%s" "${_largest}"
}

# Examples
#
#     user$ cat $HOME/test
#     #!/bin/sm
#     modules ext/array
#
#     arr=(c a d e f b h j i )
#     array_sort_desc arr
#     array_join arr
#     echo
#
#     user$ $HOME/test
#     j i h f e d c b a
#
# ### Code Walkthrough
array_sort_desc()
{
  trace_filter array
  local _array_name="${1:-}" _index _largest=""
  shift || fail "Array variable name was not given."

  eval "${_array_name}=(\$(
  echo \"\${${_array_name}[@]}\" | sed -e 's/\s/\n/g' | sort -r
  ))"
}

# Examples
#
#     user$ cat $HOME/test
#     #!/bin/sm
#     modules ext/array
#
#     arr=(c a d e f b h j i )
#     array_sort_asc arr
#     array_join arr
#     echo
#
#     user$ $HOME/test
#     a b c d e f h i j
#
# ### Code Walkthrough
array_sort_asc()
{
  trace_filter array
  local _array_name="${1:-}" _index _largest=""

  shift || fail "Array variable name was not given."

  eval "${_array_name}=(\$(
  echo \"\${${_array_name}[@]}\" | tr ' ' \"\n\" | sort
  ))"
}

# Examples
#
#     user$ cat $HOME/test
#     #!/bin/sm
#     modules ext/array
#
#     arr=(a a a b b c c c c d d d d d d)
#     array_unique arr
#     array_join arr
#     echo
#
#     user$ $HOME/test
#     a b c d
#
# ### Code Walkthrough
array_unique()
{
  trace_filter array
  local _array_name="${1:-}" _index _largest=""
  shift || fail "Array variable name was not given."

  eval "${_array_name}=(\$(
  echo \" \${${_array_name}[@]} \" |
  awk -v RS=' ' -v ORS=' ' '!(\$0 in a){a[\$0];print}'
  ))"
}

# Examples
#
#     user$ cat $HOME/test
#     #!/bin/sm
#     modules ext/array
#
#     the_array=()
#     printf "($(array_join the_array))"
#     if array_is_even the_array
#     then
#       echo " has an even number of elements."
#     else
#       echo " has an odd number of elements."
#     fi
#
#     the_array=(1)
#     printf "($(array_join the_array))"
#     if array_is_even the_array
#     then
#       echo " has an even number of elements."
#     else
#       echo " has an odd number of elements."
#     fi
#
#     the_array=(1 2 3 4)
#     printf "($(array_join the_array))"
#     if array_is_even the_array
#     then
#       echo " has an even number of elements."
#     else
#       echo " has an odd number of elements."
#     fi
#
#     the_array=(1 2 3 4 5)
#     printf "($(array_join the_array))"
#     if array_is_even the_array
#     then
#       echo " has an even number of elements."
#     else
#       echo " has an odd number of elements."
#     fi
#
#     user$ "$HOME/test"
#     () has an even number of elements.
#     (1) has an odd number of elements.
#     (1 2 3 4) has an even number of elements.
#     (1 2 3 4 5) has an odd number of elements.
#
# ### Code Walkthrough
array_is_even()
{
  trace_filter array
  local _array_name="${1:-}"
  shift || fail "Array name was not given."

  eval "(( ( \${#${_array_name}[@]} % 2 ) == 0 ))"
}

