#!/bin/sh

ext_defaults_initialize()
{
  settings_search_path_cache=()
  # This line needs to be commented to allow settings read from smrc.
  #settings_search_path_append=()
}

# Examples
#
#     user$ read_default "version" prefix "package" # extension is nginx, for example.
#     user$ echo $package_version
#     1.0.0
#
# ### Notes
#
# read_default respects a tiered default file scheme,
#
#   "/etc/sm/${extension}/defaults"
#   "$HOME/.sm/${extension}/defaults"
#   "${extension_config_path}/defaults"
#
#
#
read_default()
{
  trace_filter read_config

  local key token _args=() _extension=${extension}

  key="${1:-}"

  shift || fail "key to read must be given as first parameter."

  while (( $# > 0 ))
  do
    token="$1"
    shift
    case "$token" in
      for)
        _extension="$1"
        shift
        ;;
      *)
        _args+=( "$token" )
      ;;
    esac
  done

  read_config "${_extension}" defaults "${key}" "${_args[@]}"
}

read_config()
{
  trace_filter read_config

  local key variable token value prefix _file _temp \
    _extension="${1:-}" _config_file="${2:-}" key="${3:-}"

  shift || fail "extension name must be given as the first parameter."
  shift || fail "config file name must be given as the second parameter."
  shift || fail "key name must be given as the third parameter."

  while (( $# > 0 ))
  do
    token="$1"
    shift
    case "$token" in
      into|as)
        variable="$1"
        shift || fail "variable name must be given after keywords 'into|as'"
        ;;
      prefix)
        prefix="$1"
        shift || fail "prefix must be given after keyword 'prefix'"
        ;;
      *)
        variable="$token"
        break
      ;;
    esac
  done

  if [[ -z "${variable}" ]]
  then
    if [[ -n "${prefix}" ]]
    then
      true "${variable:="${prefix:-}_$key"}"
    else
      true "${variable:="$key"}"
    fi
  fi

  # Run search in the same process to initialize cache variables.
  settings_search ${_extension} "${_config_file}" > /dev/null

  for _file in  $( settings_search ${_extension} "${_config_file}" )
  do
    if ! file is empty "${_file}"
    then
      _temp="$(hash file read key "${key}" from "${_file}")"

      if [[ -n "${_temp}" ]]
      then
        value="${_temp}"
      fi
    fi
  done

  eval "${variable}=\"${value}\""
}

settings_search()
{
  trace_filter settings_search

  local extension=$1 setting=$2 _path paths

  paths=( "/etc/sm/${extension}" "$HOME/.sm/${extension}" ) # Standard paths

  if extension_path "${extension}"
  then
    paths+=( "${extension_path}/config" )
  fi

  for _path in "${settings_search_path_append[@]}"
  do # Additional paths
    settings_search_path_update "${_path}"
    paths+=( "${_path}/${extension}" )
  done

  for _path in "${paths[@]}"
  do # Print existing paths.
    if paths exist "${_path}" && ! file is empty "${_path}/${setting}"
    then
      printf "${_path}/${setting}\n"
    fi
  done
}

settings_search_path_update()
{
  local path=$1 _uri

  if string contains "${settings_search_path_cache[*]}" "${path}"
  then
    return 0
  fi

  if files exist "${path}/.uri" && ! file is empty "${_path}/.uri"
  then
    read -r _uri < "${path}/.uri"
    fetch_uri "${_uri}" "${path}" >&2
  fi

  settings_search_path_cache+=( "${path}" )
}

