#!/usr/bin/env bash

if array_is_nonempty extension_args
then
  for extension in "${extension_args[@]}"
  do
    extension_package "${extension}"
  done
else
  error "You must specify at least one extension name for packaging."
fi
