#!/usr/bin/env bash

if (( ${#extension_args[@]} == 0 ))
then
  error "You must specify at least one extension name for packaging."
fi

for extension in "${extension_args[@]}"
do
  extension_publish "${extension}"
done

