#!/usr/bin/env bash

echo -e "

Usage

  bdsm <service> <action> <<arguments>>

Examples

  (as root:)
  bdsm service add nginx

  bdsm nginx install
  bdsm nginx setup
  bdsm nginx stop
  bdsm nginx start
  bdsm nginx restart
  bdsm nginx reload
  ...

  bdsm service add rails
  bdsm service add unicorn
  ...

  (as a user:)
  bdsm deploy

  bdsm rails setup --database postgresql --repo git@github.com/wayneeseguin/bdsm_docs.git --server unicorn
  bdsm rails migrate
  bdsm rails logtail
  bdsm rails console
  bdsm rails dbconsole
  ...

  bdsm unicorn install
  bdsm unicorn setup
  bdsm unicorn start
  bdsm unicorn stop
  bdsm unicorn restart
  bdsm unicorn increase
  bdsm unicorn decrease
  ...

Notes

  [service] is required, default may be set in ~/.bdsmrc
  [action] is required as a command line parameter

  [project] is required as an environment variable
   - if non root, otherwise defaults to the current user name if not set

  [project|environment|repository|service]
   - may be exported as environment varaibles
   - or set in the ~/.bdsmrc
   - or specified as for example --project X

  prerequisites:
   - git
   - curl
   - rsync
   - ruby OR prereqs for rvm (preferred)

  http://bdsm.beginrescueend.com/
  https://www.pivotaltracker.com/projects/26822

"

exit 0
