#!/usr/bin/env bash

[[ "$trace_flag" -eq 1 ]] && set -o xtrace

result=0
extensions="$*"

true \
  "${releases_url:=$(hash_file "$config_path/bdsm" "releases_url")}"\
  "${extension_url:=$(hash_file "$config_path/bdsm" "extension_url")}"
