#!/usr/bin/env bash

[[ "$trace_flag" -eq 1 ]] && set -o xtrace

result=0
extensions="$*" ; shift

true \
  "${releases_url:=$(db "$config_path/bdsm" "releases_url")}"\
  "${extension_url:=$(db "$config_path/bdsm" "extension_url")}"
