#!/bin/sh

#
# SM Process API
#
# process start name <name> timeout <timeout> command <command> [params...]
# process stop name <name> timeout <timeout>
# process is running name <name>
# process restart name <name> timeout_start <timeout> timeout_stop <timeout> command <command> [params...]
# process status <pid>
# process lock </path/to/myprocess.lock>
# process send signal <signal> pid <pid>
#   where <signal> is one of (all upper or lower case):
#     kill,quit,term,usr2,usr2,ttin,ttou,winch,hup
#     OR a hyphen followed by a number ex: "-15"
#
process()
{
  trace_filter process || set -o xtrace
  typeset _command _token _name _timeout_start _timeout_stop _pid _signal _lock_path
  typeset -a __process_commands _command_arr

  __process_commands=(
    "start"
    "stop"
    "restart"
    "running=is running"
    "pid=pid read"
    "status"
    "send signal=signal"
    "lock=lockfile lock"
  )

  if __sm.command.detect "$*" "${__process_commands[@]}"
  then
    _command="${__sm_command_dotted}"
    shift "${__sm_command_words}"
  else
    __sm.log.fail "No command given.\nUsage:  \nprocess <command> ..."
  fi

  case "${_command}" in
    (status)
      _pid=$1
      shift || __sm.log.fail "Process pid must be given after 'status'"
      ;;
    (signal)
      _signal=$1
      shift || __sm.log.fail "Signal must be given after 'signal' command"
      ;;
    (lockfile.lock)
      _lock_path=$1
      shift || __sm.log.fail "Signal must be given after 'signal' command"
      ;;
  esac

  while (( $# ))
  do
    _token="$1" && shift
    case ${_token} in
      (name)
        _name="$1"
        shift || __sm.log.fail "Process name must be given after keyword '${_token}'"
        ;;
      (timeout)
        case "${_command}" in
          (start) _timeout_start="$1" ;;
          (stop)  _timeout_stop="$1"  ;;
          (*) __sm.log.fail "Keyword '${_token}' can not be used with '${_command}'." ;;
        esac
        shift || __sm.log.fail "Timeout must be given after keyword '${_token}'"
        ;;
      (timeout_start)
        _timeout_start="$1"
        shift || __sm.log.fail "Start timeout must be given after keyword '${_token}'"
        ;;
      (timeout_stop)
        _timeout_stop="$1"
        shift || __sm.log.fail "Stop timeout must be given after keyword '${_token}'"
        ;;
      (pid)
        _pid=$1
        shift || __sm.log.fail "Process pid must be given after 'status'"
        ;;
      (command)
        _command_arr=( "$@" )
        shift $# || __sm.log.fail "Command must be given after keyword '${_token}'"
        ;;
      (*)
        __sm.log.fail "Unknown token '${_token}'"
        ;;
    esac
  done

  case "${_command}" in
    (start)
      [[ -n "${_name}"          ]] || __sm.log.fail "Name must be given for '__sm.process.${_command}'."
      [[ -n "${_timeout_start}" ]] || __sm.log.fail "Start timeout must be given for '__sm.process.${_command}'."
      __sm.array.is.nonempty _command_arr || __sm.log.fail "Command must be given for '__sm.process.${_command}'."

      if __sm.process.${_command} "${_name}" "${_timeout_start}" "${_command_arr[@]}"
      then return 0
      else return $?
      fi
      ;;
    (stop)
      [[ -n "${_name}"          ]] || __sm.log.fail "Name must be given for '__sm.process.${_command}'."
      [[ -n "${_timeout_stop}"  ]] || __sm.log.fail "Stop timeout must be given for '__sm.process.${_command}'."

      if __sm.process.${_command} "${_name}" "${_timeout_stop}"
      then return 0
      else return $?
      fi
      ;;
    (restart)
      [[ -n "${_name}"          ]] || __sm.log.fail "Name must be given for '__sm.process.${_command}'."
      [[ -n "${_timeout_start}" ]] || __sm.log.fail "Start timeout must be given for '__sm.process.${_command}'."
      [[ -n "${_timeout_stop}"  ]] || __sm.log.fail "Stop timeout must be given for '__sm.process.${_command}'."
      __sm.array.is.nonempty _command_arr || __sm.log.fail "Command must be given for '__sm.process.${_command}'."

      if __sm.process.${_command} "${_name}" "${_timeout_start}" "${_timeout_stop}" "${_command_arr[@]}"
      then return 0
      else return $?
      fi
      ;;
    (is.running|pid.read)
      [[ -n "${_name}" ]] || __sm.log.fail "Name must be given for '__sm.process.${_command}'."
      if __sm.process.${_command} "${_name}"
      then return 0
      else return $?
      fi
      ;;
    (status)
      [[ -n "${_pid}" ]] || __sm.log.fail "Process pid must be given for '__sm.process.${_command}'."
      if __sm.process.${_command} "${_pid}"
      then return 0
      else return $?
      fi
      ;;
    (signal)
      [[ -n "${_pid}" ]] || __sm.log.fail "Process pid must be given for '__sm.process.${_command}'."
      [[ -n "${_signal}" ]] || __sm.log.fail "Signal must be given for '__sm.process.${_command}'."
      if __sm.process.${_command} "${_signal}" "${_pid}"
      then return 0
      else return $?
      fi
      ;;
    (lockfile.lock)
      [[ -n "${_lock_path}" ]] || __sm.log.fail "Lockfile must be given for '__sm.process.${_command}'."
      if __sm.process.${_command} "${_lock_path}"
      then return 0
      else return $?
      fi
      ;;
    (*)
      __sm.log.fail "Process2 API command '${_command}' s not handled."
      ;;
  esac
}
