#!/usr/bin/env bash

#
# BDSM templates module DSL functions
#

template_exists()
{
  local _template="${extension_templates_path}/${_template}.template"

  [[ -s "${_template}" ]]
}

install_template()
{
  local _name _target _source

  while [[ $# -gt 0 ]] ; do
    token="${1}" ; shift

    case "${token}" in
      to)
         _target="$1" ; shift
        ;;
      from) # TODO: finish this part.
         _source="$1" ; shift
        ;;

      *)
        if [[ -z "${_name}" ]] ; then
          _name="$token"
        elif [[ -z "${_target}" ]] ; then
          _target="$token"
          break # When we have a target we are done.
          # An alternative idea would be to allow an array of multiple targets
          # to symlink to...
        fi
        ;;
    esac
  done

  local _template="${extension_templates_path}/${_name}.template"

  ensure_paths_exist "$(dirname "${_target}")"

  if [[ -f "${_template}" ]] ; then
    if [[ -d "${_target}" ]] ; then
      if [[ -d "${_target}/${_name}" ]] ; then
        fail "${_target}/${_name} is a directory, cannot install template ${_name}"
      else
        cp -f "${_template}" "${_target}/${_name}"
      fi
    else
      cp -f "${_template}" "${_target}"
    fi
  else
    fail "Template missing: #{_template}"
  fi
}

