#!/bin/sh

process()
{
  local _command _token

  while (( $# ))
  do
    _token="$1" && shift
    case "${_token}" in
      (on)
        _subcommand="$1"
        case "${_subcommand}"
        (exit)
      (*)
        ;;
    esac
  done
}

