.\"   $Id$
.\"
.\"   Man page for the bdsm project.
.\"
.\"   $Log$
.\"

.TH SM 1 "2011 August 17" "SM Framework"

.SH SYNOPSIS
.B sm
[cli] smrc [install]

.SH DESCRIPTION
SM action to update or generate ~/.smrc file

.SH Actions
.TP 13
.B smrc
Install/update smrc template file in ~/.smrc.
.TP 13
.B smrc install
Force install smrc template file into ~/.smrc (no update).
