#!/bin/sh

package_extension_setup()
{
  local extension="${1:-}" module="${2:-}" path="${3:-}" ${language:=shell}
  shift || fail "No extension name given."
  shift || fail "No module name given."
  shift || fail "No path given."

  for action in install uninstall update activate deactivate
  do
    files write append string "${action}=${module}_${action}()" to "${path}/map"
  done
}

