#!/bin/sh

find_starting_action()
{
  trace_filter action_completion
  extensions_path="$1" extension="$2"
  shift || fail "Cannot detect extension existence;"\
    " No extension path was given."
  shift || fail "Cannot detect extension existence;"\
    " No extension name was given."

  local _action_params=("$@") _action_path _new_action_path
  local _rest_params=() _param_temp _action_params_length

  local _actions_root="${extensions_path}/${extension}/actions"
  local _actions_map="${extensions_path}/${extension}/actions.map"
  local _modules_root="${extensions_path}/${extension}/modules"
  local _actions_cache=() _found_actions=()

  initialize_filesystem_cache
  initialize_actions_map_cache
  initialize_modules_actions_cache

  if (( ${#_actions_cache[@]} ))
  then
    _action_path="${_action_params[*]}"
    _action_path="${_action_path// //}"
    if action_cache_find_matching starting "${_action_path}"
    then
      local _candidate
      for _candidate in "${_found_actions[@]}"
      do
        _candidate="${_candidate%%=*}"
        printf "${_candidate//\// }\n"
      done
      return 0
    fi
  fi
  return 1
}

show_extension_names()
{
  extensions_path="$1"
  shift || fail "no path given"
  local _params=($@) _patern=${_params[$((${#_params[@]} - 1 ))]}
  for extension in ${extensions_path}/*
  do
    extension="${extension##*/}"
    case "${extension##*/}" in
      (\*) continue ;; #skip empty dirs
      (.*) continue ;; #skip hidden stuff
      (${_patern}*) printf "${extension}\n" ;;
    esac
  done
  return 1
}

extension_action_completion()
{
  trace_filter action_completion
  local _extension_found=0 _action_found=0

  {
    if in_search_paths detect_extension_existence "${extension_args[@]}"
    then
      _extension_found=1
      log_search extension "$extension" "$extensions_path"
      if find_starting_action "$extensions_path" "${extension_args[@]}"
      then
        _action_found=1
      fi
    fi

    if (( ! _action_found )) && (( ${#extension_args[@]} <= 1 ))
    then
      in_search_paths show_extension_names "unused" "${extension_args:-}" || true
    fi

    if (( ! _action_found )) &&
      in_cli_path find_starting_action "${extension_args[@]}"
    then
      _action_found=1
    fi

    if (( _action_found ))
    then
      log_search action "$action" "${action_path##${sm_path}\/} params:${extension_args[@]}"
    fi
  } | sort -u
}
