#!/usr/bin/env bash

export PATH="/sbin:/usr/sbin:/usr/local/sbin:/opt/sbin:/opt/local:sbin:$PATH"
if [[ -s "/etc/bdsmrc" ]] ; then source "/etc/bdsmrc" ; fi

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

master_pid="$(ps auxww |  awk '/[n]ginx: master/{print $2}' | head -n 1)"
config_file="${config_file:-"/etc/nginx/nginx.conf"}"

