#!/bin/sh

#
# SM Framework Core Module ~ Array (array)
#
# API Version: 1.0.0
#
# array {command} {params...}
#
# where command is one of:
#
#   is empty
#   is nonempty
#   is even
#   length
#   last
#   first
#   push
#   pop
#   append
#   shift
#   unshift
#   join
#   largest
#   sort desc
#   sort asc
#   unique
#   start     # index of first element
#

array()
{
  trace_filter array || set -o xtrace
  typeset _command _subcommand _name _variable
  _command="$1"
  (( $# )) && shift || __sm.log.fail "Array command must be given as the first parameter."

  case "${_command}" in
    (is)
      _subcommand="$1" _name="$2"
      (( $# >= 2 )) && shift 2 || __sm.log.fail "subcommand and array name missing;"\
        " array is <empty,nonempty,even> {name}"
      case "${_subcommand}" in
        (empty)
          __sm.array.is.empty "${_name}"
          ;;
        (nonempty)
          __sm.array.is.nonempty "${_name}"
          ;;
        (even)
          __sm.array.is.even "${_name}"
          ;;
        (*)
          __sm.log.fail "Unknown '${_subcommand}'; array is <empty,nonempty,even> {name}"
          ;;
      esac
      ;;
    (length)
      _name="$1"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array length {name}"
      __sm.array.length "${_name}"
      ;;
    (last)
      _name="$1"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array last {name}"
      __sm.array.last "${_name}"
      ;;
    (first)
      _name="$1"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array first {name}"
      __sm.array.first "${_name}"
      ;;
    (push)
      _name="$1" _element="$2"
      (( $# >= 2 )) && shift 2 || __sm.log.fail "Array name or element missing:"\
        " array push {name} {element}"
      __sm.array.push "${_name}" "${_element}"
      ;;
    (pop)
      _name="$1" _variable="${2:-}"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array pop {name} [{variable}]"
      __sm.array.pop "${_name}" "${_variable}"
      ;;
    (append)
      _name="$1" _element="$2"
      (( $# >= 2 )) && shift 2 || __sm.log.fail "Array name or element missing:"\
        " array append {name} {element}"
      __sm.array.append "${_name}" "${_element}"
      ;;
    (shift)
      _name="$1" _variable="${2:-}"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array shift {name} [{variable}]"
      __sm.array.shift "${_name}" "${_variable}"
      ;;
    (unshift)
      _name="$1"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array unshift {name} [{variable}]"
      __sm.array.unshift "${_name}" "${_variable}"
      ;;
    (join)
      _name="$1" _separator="${2:-' '}"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array join {name} [separator]"
      __sm.array.join "${_name}" "${_separator}"
      ;;
    (largest)
      _name="$1"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array largest {name}"
      __sm.array.largest "${_name}"
      ;;
    (sort)
      _subcommand="$1" _name="$2"
      (( $# >= 2 )) && shift 2 || __sm.log.fail "sort direction and array name missing;"\
        " array sort <desc,asc> {name}."
      __sm.array.sort "${_name}" "${_subcommand}"
      ;;
    (unique)
      _name="$1"
      (( $# )) && shift || __sm.log.fail "Array name missing:  array unique {name}."
      __sm.array.unique "${_name}"
      ;;
    (start)
      echo ${__sm_array_start}
      ;;
    (*)
      __sm.log.fail "Unknown array command '${_command}'"
      ;;
  esac
}

