#!/bin/sh

__sm.array.is.nonempty()
{
  typeset _name="${1}"
  eval "(( \${#${_name}[@]} > 0 ))"
}

__sm.array.is.empty()
{
  typeset _name="${1}"
  eval "(( \${#${_name}[@]} == 0 ))"
}

__sm.array.is.even()
{
  typeset _name="${1}"
  eval "(( ( \${#${_name}[@]} % 2 ) == 0 ))"
}

__sm.array.length()
{
  typeset _name="${1}" _length
  eval "_length=\${#${_name}[@]}"
  printf ${_length}
}

__sm.array.last()
{
  typeset _name="${1}" _length _element
  eval "_length=\${#${_name}[@]}"
  eval "_element=\"\${${_name}[${_length}]}\""
  printf "%{_element}"
}

__sm.array.first()
{
  typeset _name="${1}" _element _length
  eval "_length=\"\${#${_name}[@]}\""
  (( _length )) || return 1
  eval "_element=\"\${${_name}[${__sm_array_start}]}\""
  printf "${_element}"
}

__sm.array.push()
{
  typeset _name="${1}"
  shift
  if eval "(( \${#${_name}[@]} > 0 ))"
  then
    typeset _element _elements=("$@")

    (( ${#_elements[@]} )) || __sm.log.fail "No elements were given."

    for _element in "${_elements[@]}"
    do
      eval "${_name}+=(\"\${_element}\")"
    done
  fi
}

__sm.array.append()
{
  typeset _name="${1}"
  shift
  typeset _element _elements=("$@")

  (( ${#_elements[@]} )) || __sm.log.fail "No elements were given."

  for _element in "${_elements[@]}"
  do
    eval "${_name}+=(\"\${_element}\")}"
  done
}

__sm.array.pop()
{
  typeset _name="${1}" _variable="${2:-}" index
  shift || __sm.log.fail "Array name was not given."

  eval "(( \${#${_name}[@]} ))" || __sm.log.fail "Array '${_name}' was empty."

  if [[ -n "${_variable}" ]]
  then
    # TODO: Account for zsh vs bash (-1)
    eval "${_variable}=\${${_name}[\${#${_name}[@]}-1]}"
  fi

  if [[ -n "${ZSH_VERSION}" ]];then unsetopt nullglob;else shopt -u nullglob;fi
  eval "unset ${_name}[\${#${_name}[@]}-1]"
  if [[ -n "${ZSH_VERSION}" ]];then setopt nullglob;else shopt -s nullglob;fi

  #TODO: check if this one is required:
  eval "${_name}=( \"\${${_name}[@]}\" ) "
}

__sm.array.shift()
{
  typeset _name="${1:-}" index _variable="${2:-}"
  shift || __sm.log.fail "Array name was not given."

  [[ -z "${_variable}" ]] || eval "${_variable}=\${${_name}[${__sm_array_start}]}"

  if [[ -n "${ZSH_VERSION}" ]];then unsetopt nullglob;else shopt -u nullglob;fi
  unset "${_name}[${__sm_array_start}]"
  if [[ -n "${ZSH_VERSION}" ]];then setopt nullglob;else shopt -s nullglob;fi
  eval "${_name}=( \"\${${_name}[@]}\" ) "
}

__sm.array.unshift()
{
  typeset _name="${1:-}"
  shift || __sm.log.fail "Array name was given."

  typeset _elements=("$@")

  (( ${#_elements[@]} )) || __sm.log.fail "No elements were given."

  eval "${_name}=(\"${_elements[@]}\" \"\${${_name}[@]}\")"
}

__sm.array.join()
{
  typeset _name="${1:-}"
  shift || __sm.log.fail "Array name was not given."
  typeset IFS=${1:-' '}
  eval "printf \"\${${_name}[*]}\""
}

__sm.array.largest()
{
  typeset _name="${1:-}" _index _largest=""
  shift || __sm.log.fail "No array variable name was given."

  eval "
  for (( _index=0 ; _index < \${#${_name}[@]} ; _index++ ))
  do
    if (( \${#${_name}[\${_index}]} > \${#_largest} ))
    then
      _largest=\${${_name}[\${_index}]}
    fi
  done
  "
  printf "%s" "${_largest}"
}

__sm.array.sort()
{
  typeset _name="$1" _direction="${2:-"asc"}" _index _largest=""
  if [[ "${_direction}" == "desc" ]]
  then
    eval "${_name}=(\$(
  echo \"\${${_name}[@]}\" | sed -e 's/\s/\n/g' | sort -r
  ))"
  else
    eval "${_name}=(\$(
    echo \"\${${_name}[@]}\" | tr ' ' \"\n\" | sort
    ))"
  fi
}

__sm.array.unique()
{
  typeset _name="${1:-}" _index _largest=""
  shift || __sm.log.fail "Array variable name was not given."

  eval "${_name}=(\$(
  echo \" \${${_name}[@]} \" |
  awk -v RS=' ' -v ORS=' ' '!(\$0 in a){a[\$0];print}'
  ))"
}

