#!/usr/bin/env bash

#
# BDSM project module initialization
#
# When run as root, we must ensure that project and project_path are set.
(( UID > 0 )) && { : "${project:="$USER"}" "${project_path:="$HOME"}" ; }

[[ -n "${project:-}" && -n "${project_path:-}" ]] && project_initialize

export project environment project_path shared previous_path release_path stage_path log_path

