#!/usr/bin/env bash

echo -e "
Usage
  $0 {install,setup,start,stop,restart,status,help}
Actions
  install  - Install the $service gem.
  setup    - Setup and Configure $service.
  start    - Start service.
  stop     - Stop service.
  restart  - Restart service.
  status   - Display service status.
  help     - Display this help text.
"
exit $?
