#!/usr/bin/env bash

param="${extension_action:-$extension_args}"

case "${param}" in
  head)
    install_head
    ;;

  version) # x.y.z
    install_release
    ;;

  latest)
    fetch_version
    install_release
    ;;

  *)
    install_remote "${param}"
    ;;
esac

