#!/usr/bin/env bash

modules package


# Ensure that default values are set.
true \
  "${prefix_path:="/usr/local"}" \
  "${archive_format:=tar.gz}" \
  "${package_name:=${extension}}"

true \
  "${bin_path:="${prefix_path}/bin"}" \
  "${source_path:="${prefix_path}/src"}"

export prefix_path bin_path source_path
