#!/usr/bin/env bash

show_help()
{
  local _help_command _token

  while [[ $# -gt 0 ]] ; do
    _token="$1" ; shift
    case "${_token}" in
      desc*|description)
        _help_command="description"
        ;;
      actions)
        _help_command="actions"
        ;;
      help|usage|*)
        _help_command="usage"
        ;;
    esac
  done

  ${help_command}
}

description() { help_description="$*" ; }

actions(){ help_actions="$*" ; }

notes() { help_notes="$*" ; }

dependencies() { help_dependencies="$*" ; }

resources() { help_resources="$*" ; }

usage()
{
  log "\nUsage\n\n    bdsm ${extension} <action> <<arguments>>\n"

  [[ -n "${help_description}" ]] && \
    log "\nDescription\n    BDSM ${help_description}"

  log "\nActions\n"
  [[ -n "${help_actions}" ]] && \
    log "${help_actions}\n"
  log "  help - Display this help text."

  [[ -n "${help_notes}" ]] && \
    log "\nNotes\n${help_notes}"

  [[ -n "${help_dependencies}" ]] && \
    log "\nDependencies\n${help_dependencies}"

  [[ -n "${help_resources}" ]] && \
    log "\nResources\n${help_resources}"

  [[ "${extension}" = "core" || "${extension}" = "<extension>" ]] && {
    log "\nExtensions Installed\n\n  $(installed_extensions)"
    log "\nExtensions Available\n\n  $(available_extensions)\n"
  }
}

