#!/bin/sh

modules help

description "SM Extension Manager."

action "create {name}" \
  "Create a named module. Use --language {name} to specify the language."

action "list" \
  "List all modules installed in the system."

action "docgen" \
  "Generate module documentation from the system-installed BDSM instance into content/modules/."

action "src" \
  "Prints out the modules source directory."

action "open" \
  "Opens the modules directory in the filesystem browser."

action "dsl" \
  "Prints out a summary listing of DSL functions, by module."

resource "http://bdsm.beginrescueend.com/modules/"

show_help usage

