#!/bin/sh

command()
{
  trace_filter command
  local _command _subcommand _token _user _code _flags=()

  while (( $# ))
  do
    _token="$1" && shift
    case "${_token}" in
      (exists)
        if builtin command -v "${1}" > /dev/null 2>&1
        then return 0 ; else return 1 ; fi
        ;;
      (is)
        _subcommand="$1"
        shift || fail "A command must follow keyword 'is'; <function>"
        case "${_subcommand}" in
          (function)
            if declare -f "$1" >/dev/null 2>&1
            then return 0 ; else return 1 ; fi
            ;;
            # (script)
            # (binary)
          (*)
            fail "Unknown command '${1}' following keyword 'is'"
            ;;
        esac
        ;;
      (run)
        case "$1" in
          (as)
            shift
            _user="$1"
            shift || fail "A user name or id must be specified after keyword 'as'"
            # TODO: Check to ensure user name/id exists on the system
            if su ${_flags[@]} "${_user}" -c "$*"
            then return 0 ; else return 1 ; fi
            ;;
          (*)
            _command="$1"
            shift
            if ${_command} $@
            then return 0 ; else return 1 ; fi
            ;;
        esac
        ;;
      (*)
        if [[ -z "${_command}" ]]
        then
          _command="${_token}"
        else
          _code+=("${_token}")
        fi
        ;;
    esac
  done
}
