#!/usr/bin/env bash

number_of_args=${#extension_args[@]}

for ((index=0 ; index < $number_of_args ; index++)) ; do

  token="${extension_args[$index]}"

  case "$token" in
    --trace)
      export trace_flag=1
      enable_trace
      ;;

    head|master)
      extension_action="head"
      ;;

    +([[:digit:]]).+([[:digit:]]).+([[:digit:]])) # x.y.z
      # TODO: Set env vars instead of calling the method.
      version="${token}"
      extension_action="version"
      ;;

    latest|release)
      extension_action="latest"
      ;;

    bdsmrc|help|usage|version|edit)
      true # allow action to run.
      ;;

    *)
      usage
      exit 1
      ;;
  esac
done
