#!/usr/bin/env bash

number_of_args=${#extension_args[@]}

for ((index=0 ; index < $number_of_args ; index++)) ; do

  token="${extension_args[$index]}"

  case "$token" in
    --trace)
      export trace_flag=1
      enable_trace
      ;;

    head|master)
      # TODO: Set env vars instead of calling the method.
      install_head
      ;;

    +([[:digit:]]).+([[:digit:]]).+([[:digit:]])) # x.y.z
      # TODO: Set env vars instead of calling the method.
      version="${token}"
      install_release
      ;;

    latest|release)
      # TODO: Set env vars instead of calling the method.
      fetch_version
      install_release
      ;;

    help|usage)
      usage
      exit 0
      ;;

    *)
      usage
      exit 1
      ;;
  esac
done
