#!/usr/bin/env bash

# Ensure that default values are set.
true \
  "${prefix_path:="/usr/local"}" \
  "${archive_format:=tar.gz}" \
  "${package_name:=${extension}}"

true \
  "${bin_path:="${prefix_path}/bin"}" \
  "${source_path:="${prefix_path}/src"}"

# Load the BDSM framework version.
[[ -s "$bdsm_path/VERSION" ]] && \
  VERSION="$(cat "$bdsm_path/VERSION")"

user="$USER"

export prefix_path bin_path source_path

