#!/usr/bin/env bash

# Ensure that default values are set.
true "${prefix_path:="/usr/local"}"

true \
  "${bin_path:="${prefix_path}/bin"}" \
  "${source_path:="${prefix_path}/src"}" \
  "${archive_format:=tar.gz}" \
  "${package_name:=${extension}}"

true \
  ${repository_url:="git://github.com/wayneeseguin/bdsm"} \
  "${releases_url:=$(hash_file "${config_path:="${bdsm_path}/config"}/defaults" "releases_url")}"

# Load the BDSM framework version.
bdsm_version

user="$USER"

export prefix_path bin_path source_path

modules system

