#!/usr/bin/env bash

first()
{
  local _array=("$@")
  (( ${#_array[@]} > 0 )) || fail "No arguments given."
  printf "%s" "${_array[0]}"
}

last()
{
  local _array=("$@")
  (( ${#_array[@]} > 0 )) || fail "No arguments given."
  printf "%s" "${_array[$((${#_array[@]} - 1))]}"
}

match()
{
  local _value="$1" _regex="$2"

  shopt -s extglob

  case "${_value}" in
    (${_regex}) return 0 ;;
    (*)         return 1 ;;
  esac
}

ensure_nonempty()
{
  local variable

  for variable in "$@"
  do
    eval "[[ -n \"\${${variable}}\" ]]" ||
      fail "${extension} ${action} Required variable '$variable' is not set."
  done
}

variable_is_nonempty()
{
  local _variable="${1:-}"

  [[ -n "${_variable}" ]] ||
    fail "Cannot check if variable is nonempty, no variable was given."

  eval "[[ -n \"\${${_variable}:-}\" ]]"
}

