#!/usr/bin/env bash


first()
{
  printf "%s" "$1"
}

match()
{
  local _value="$1" _regex="$2"

  shopt -s extglob

  case "${_value}" in
    ${_regex}) return 0 ;;
    *)        return 1 ;;
  esac
}

ensure_nonempty()
{
  local variable

  for variable in "$@" ; do
    if eval "[[ -z \"\${${variable}}\" ]]" ; then
      fail "${extension} ${action} Required variable '$variable' is not set."
    fi
  done
}

variable_is_nonempty()
{
  local _variable="${1:-}"

  [[ -n "${_variable}" ]] ||
    fail "Cannot check if variable is nonempty, no variable was given."

  eval "[[ -n \"\${${_variable}:-}\" ]]"
}

