#!/usr/bin/env bash


#
# BDSM variables module DSL functions
#
first()
{
  printf "$1"
}

match()
{
  local _value="$1" _regex="$2"

  shopt -s extglob

  case "${_value}" in
    ${_regex}) return 0 ;;
    *)        return 1 ;;
  esac
}

ensure_nonempty()
{
  local variable

  for variable in "$@" ; do
    if eval "[[ -z \"\${${variable}}\" ]]" ; then
      fail "${extension} ${action} Required variable '$variable' is not set."
    fi
  done
}

variable_is_nonempty() { eval "[[ -z \"\${${1}}\" ]]" ; }

