#!/usr/bin/env bash

echo -e "
Usage
  $0 {install,setup,start,stop,restart,status,help}
Actions
  install  - Install the $extension gem.
  setup    - Setup and Configure $extension.
  start    - Start extension.
  stop     - Stop extension.
  restart  - Restart extension.
  status   - Display extension status.
  help     - Display this help text.
"
exit $?
