#!/usr/bin/env bash

# Ensure that default values are set.
fhs_dirs=(bin etc include lib libexec sbin share man)

declare -a package_dependencies

true \
  "${source_path:="${sm_path}/src"}" \
  "${archives_path:="${sm_path}/archives"}" \
  ${static_flag:=0}

ensure_paths_exist "${active_path}"

for dir in ${fhs_dirs}
do
  ensure_paths_exist "${active_path}/${fhs_dirs}"
done

configure_flags=( --prefix="${install_path}" )

LDFLAGS="-L${active_path}/lib ${LDFLAGS:-}"
CFLAGS="-I${active_path}/include ${CFLAGS:-} "

export package_name packages_path package_name package_version archive_format \
  package_file package_url package_md5_url packages_path bin_path source_path \
  LDFLAGS CFLAGS package_default_version
