#!/usr/bin/env bash

set_ps4()
{
  export PS4=" > \${BASH_SOURCE##\${bdsm_path}\/} \${FUNCNAME[0]:+\${FUNCNAME[0]}()} \${LINENO} $ "
}

enable_trace()
{
  [[ ${trace_flag:-0} -eq 1 ]] || return 0

  export trace_flag
  set -o xtrace
}

enable_debug()
{
  [[ ${debug_flag:-0} -eq 1 ]] || return 0

  export debug_flag
  set -o verbose
}

enable_backtrace()
{
  trap backtrace ERR
}

backtrace()
{
  local _source _function _line _index
  printf "  %6s %6s %-20s %-55s\n" "Trace" "Line" "Function" "File" 1>&2
  for (( _index=1 ; _index < ${#FUNCNAME[@]} ; ++_index )) ; do
    _source="${BASH_SOURCE[${_index}]}"
    _function="${FUNCNAME[${_index}]:+${FUNCNAME[${_index}]}()}"
    _line=${BASH_LINENO[$(( _index - 1 ))]}

    printf "  %5d. %6s %-20s %-55s\n" \
      "$((${#FUNCNAME[@]} - _index ))" "${_line}" "${_function}" "${_source} " 1>&2
  done
}

