#!/usr/bin/env bash

set_ps4()
{
  export PS4=" > \${BASH_SOURCE##\${bdsm_path}\/} \${FUNCNAME[0]:+\${FUNCNAME[0]}()} \${LINENO} $ "
}

trace()
{
  local _option="${1:-on}"

  if [[ "${_option}" = "on" ]] ;then
    export trace_flag=1
    set -o xtrace
  else
    set +o xtrace
    export trace_flag=0
  fi
}

enable_trace()  { trace on ; }
disable_trace() { trace off ; }

debug()
{
  local _option="${1:-on}"

  if [[ "${_option}" = "on" ]] ;then
    export debug_flag=1
    set -o verbose
  else
    set +o verbose
    export debug_flag=0
  fi
}

enable_debug()      { debug on ; }
disable_debug()     { debug off ; }

enable_backtrace()  { trap backtrace ERR ; set -o errexit ; }
disable_backtrace() { set +o errexit trap - ERR ; }

backtrace()
{
  trace off

  local _source _function _line _index
  printf "Error Backtrace:\n  %6s %6s %-20s %-55s\n" "Trace" "Line" "Function" "File" 1>&2
  for (( _index=1 ; _index < ${#FUNCNAME[@]} ; ++_index )) ; do
    _source="${BASH_SOURCE[${_index}]}"
    _function="${FUNCNAME[${_index}]:+${FUNCNAME[${_index}]}()}"
    _line=${BASH_LINENO[$(( _index - 1 ))]}

    printf "  %5d. %6s %-20s %-55s\n" \
      "$((${#FUNCNAME[@]} - _index ))" "${_line}" "${_function}" "${_source} " \
      1>&2
  done

  trace on
}

