#!/bin/sh

cleanse_paths=( external completion modules bin extensions )
directories=( bin )
binaries=( sm sm-ll smp )
files=( LICENSE VERSION README.md )
aux_paths=( log tmp src )
configs=( user ) # TODO move this to /etc/sm/ and/or $HOME/.sm/

