#!/usr/bin/env bash

cleanse_paths=( external completion modules bin extensions )
directories=( bin )
binaries=( bdsm bdsm-ll smp )
files=( LICENSE VERSION README.md )
aux_paths=( log tmp src )
configs=( user ) # TODO move this to /etc/bdsm/ and/or $HOME/.bdsm/

