#!/bin/sh

#
# traps on exit "command"
#
traps()
{
  typeset _token _signal _code

  while (( $# ))
  do
    _token="$1" && shift
    case "${_token}" in
      (on)
        _signal="$1"
        (( $# )) && shift || __sm.log.fail "A signal must follow keyword 'on'"
        case "${_signal}" in
          (exit|EXIT)
            _code="$*"
            (( $# )) && shift || __sm.log.fail "The code to be run on EXIT must be given after keyword 'EXIT'."
            __sm.traps.on.exit "${_token}" "${_signal}" "${_code}"
            ;;
          (*)
            __sm.log.fail "Unknown signal '${_signal}'"
            ;;
        esac
      (*)
        __sm.log.fail "_unknown command "${_token}
        ;;
    esac
  done
}
