#!/bin/sh

package_extension_setup()
{
  typeset extension module path action
  extension="${1:-}"
  module="${2:-}"
  path="${3:-}"
  true ${language:=shell}
  (( $# )) && shift || __sm.log.fail "Cannot setup package extension; no extension name given."
  (( $# )) && shift || __sm.log.fail "Cannot setup package extension; no module name given."
  (( $# )) && shift || __sm.log.fail "Cannot setup package extension; no path given."

  for action in install uninstall update activate deactivate
  do
    files write append string "${action}=${module}_${action}()" to "${path}/map"
  done
}

