#!/usr/bin/env bash

#core is loaded as BDSM starts
modules=(
  "core/core=builtin/core/modules/shell/core"
  "core/string=builtin/core/modules/shell/string"
  "core/logging=builtin/core/modules/shell/logging"
  "core/modules=builtin/core/modules/shell/modules"
)

for module_def in ${modules[@]}
do
  module_name="${module_def//=*}"
  module_path="${module_def//*=}"
  log_search preload "$module_name" "${module_path}"
done
