#!/usr/bin/env bash

service_extension_setup()
{
  local extension="${1}" module="${2}" path="${3}" ${language:=shell}

  enter "${path}"

  ensure_paths_exist "modules/${language}/${module}" "actions/${module}"

  # Setup modules/shell/package/{dsl,initialize,cli}
  for file in dsl initialize cli
  do
    log '#!/usr/bin/env bash' to "modules/${language}/${module}/${file}"
  done

  log "\n${module}_cli\n" append to "modules/${language}/${module}/cli"

  log '#!/usr/bin/env bash' to "actions/${module}/help"
  chmod_files 0755 "actions/${module}/help"

  log "
description \"Extension for managing ${extension} (${website_url}).\"

action \"service start\" \"Starts ${extension} service.\"
action \"service stop\" \"Stop ${extension} service.\"
action \"service restart\" \"Restarts ${extension} service.\"
action \"service status\" \"Display ${extension} status.\"
action \"service list\" \"List ${extension} master and worker processes.\"

show_help usage
" append to "actions/${module}/help"

  for action in start stop restart status
  do
    log "${action}=package_${action}()" append to "actions/${module}/.actions"
  done
  chmod_files 0755 "actions/${module}/.actions"
}

