#!/usr/bin/env bash

#
# This file contains the functions that compries the BDSM framework DSL.
#

shopt -s extglob # Extended globs must always be on for BDSM.

modules()
{
  local _module _bdsm_module _extension_module

  for _module in "$@" ; do
    _bdsm_module="${scripts_path}/bash/${_module}"
    _extension_module="${extension_scripts_path}/bash/${_module}"

    [[ -s "${_bdsm_module}" ]] && source  "${_bdsm_module}"
    [[ -s "${_extension_module}" ]] && source "${_extension_module}"
  done
}

# Modules that should be available to *all* bdsm extensions.
modules trace logging variables

