#!/usr/bin/env bash

log()  {
  printf "$*\n"
  return $?
}

fail() {
  log "\nERROR: $*\n"
  exit 1
}

# Safely source files and notify the user if they do not exist.
# Recommended to put in /etc/bash.bashrc or ~/.bashrc and be sure
# it is sourced from ~/.bash_profile
source_files()
{
  local file

  for file in "$@" ; do
    file=${file/\~\//$HOME\/} # Expand ~/ to full value of $HOME

    if [[ -s "${file}" ]] ; then
      source "${file}"
    else
      if [[ ! -e "${file}" ]] ; then
        printf "NOTICE: ${file} does not exist, not loading.\n"
      else
        true # simply an empty file, no warning necessary.
      fi
    fi
  done

  return 0
}

# safely source the first file found
nonempty_files()
{
  local file

  for file in "${@}" ; do
    if [[ -s "$file" ]] ; then
      printf "$file"
    fi
  done

  return 0
}

first()
{
  printf "$1"

  return 0
}

ensure_paths_exist()
{
  local _path

  for _path in "$@" ; do
    if [[ -d "${_path}" ]] ; then
      mkdir -p "${_path}"
    fi
  done
}

match()
{
  local value="$1" regex="$2"

  shopt -s extglob

  case "$value" in
    $regex) return 0 ;;
    *)      return 1 ;;
  esac
}

# Source bdsmrc files, cascaded.
bdsmrc()
{
  source_files "/etc/bdsmrc" "$HOME/.bdsmrc"
}

[[ ${trace_flag:-0} -eq 1 ]] && set -o xtrace
[[ ${debug_flag:-0} -eq 1 ]] && set -o verbose

