#!/usr/bin/env bash

#
# This file contains the functions that compries the BDSM framework DSL.
#

shopt -s extglob # Extended globs must always be on for BDSM.

modules()
{
  local _module
  for _module in "$@" ; do
    [[ -s "${scripts_path}/bash/${_module}" ]] && \
      source  "${scripts_path}/bash/${_module}"
  done
}

# Modules that should be available to *all* bdsm extensions.
modules trace logging variables

