#!/usr/bin/env bash

echo -e "
Usage
  $0 {install,setup,start,stop,help}
Actions
  install  - Install the rabbitmq gem.
  setup    - Place the config.rabbitmq template in $current_path/config/config.rabbitmq
  start    - Startup rabbitmq.
  stop     - Stop rabbitmq.
  help     - Display this help text.
"
exit $?
