#!/usr/bin/env bash

# ## archive\_get()
#
#
#
# Code Walkthrough
archive_get() {
  local _uri="${1:-}" _final_target="${2:-}" _package_md5="${3:-${md5:-#}}" \
    _archive="${archives_path}/${_uri##*/}"

  shift || fail "uri must be specified as the first parameter."
  shift || fail "target path must be specified as the second parameter."

  [[ -d "${archives_path}" ]] || mkdir -p "${archives_path}"

  if [[ -f "${_archive}" ]] \
  && ! file_matches_md5 "${_archive}" "${_package_md5}"
  then
    debug vcs "${_uri##*/} does not match MD5 checksum ${_package_md5}; removing and downloading."
    rm -f "${_archive}"
  fi

  if [[ ! -f "${_archive}" ]]
  then
    if [[ -f "${_uri}" ]]
    then
      copy_file --force "${_uri}" to "${_archive}" || \
        fetch_error copy_failed from=${_uri} to=${_archive}
    else
      curl -s -L "${_uri}" -o "${_archive}" || \
        fetch_error download_failed from=${_uri} to=${_archive}
    fi
  fi
  [[ -z "${__vcs_failed}" ]] || return 0

  rm -rf "${_final_target}" || true
  mkdir -p "${_final_target}"
  builtin cd "${_final_target}"

  case "${_uri}" in
    *.tar) # tar
      tar xf "${_archive}" || fetch_error extracting_archive_failed
      ;;
    *.tar.gz|*.tgz) # gzip
      tar zxf "${_archive}" || fetch_error extracting_archive_failed
      ;;
    *github.com/*/tarball/*)
      tar zxf "${_archive}" || fetch_error extracting_archive_failed
      local name_pattern="${_uri#https://github.com/}"
      name_pattern="${name_pattern%tarball/*}"
      name_pattern="${name_pattern//\//-}"
      mv ${name_pattern}*/* .
      rm -rf ${name_pattern}*
      ;;
    *.tar.bz2|*.tbz2) # bzip
      tar jxf "${_archive}" || fetch_error extracting_archive_failed
      ;;
    *.tar.xz) # LZMA
      # TODO: if 'xz' command exists, use that, otherwise use tar J
      tar Jxf "${_archive}" || fetch_error extracting_archive_failed
      ;;
    *.zip)
      unzip "${_archive}" || fetch_error extracting_archive_failed
      ;;
    *)
      #TODO: add detection based on $( file ${_archive} ) type
      fetch_error unknown_archive_format
      ;;
  esac
  [[ -z "${__vcs_failed}" ]] || return 0

  ls -d * &>/dev/null || fetch_error empty_archive

  echo "${_uri}" > "./.uri"
}
