#!/usr/bin/env bash

if [[ ! -z "$HOME/.bashrc" ]] ; then source "$HOME/.bashrc" ; fi

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

cd $current_path
if [[ ! -z ".rvmrc" ]] ; then source ".rvmrc" ; fi

if [[ -s $bdsm_dir/unicorn/templates/unicorn.rb ]] ; then
  echo -e "ERROR: $bdsm_dir/unicorn/templates/unicorn.rb template is missing."
  exit 1
fi

mkdir -p $shared_path/config/

cp $bdsm_dir/unicorn/templates/unicorn.rb $shared_path/config/
exit $?
