#!/usr/bin/env bash

if [[ ! -z "$HOME/.bashrc" ]] ; then source "$HOME/.bashrc" ; fi

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

master_pid="$(ps auxww | grep '[u]nicorn' | grep 'master' | awk '/'${project}'/{print $2}')"

cd $current_path
if [[ ! -z ".rvmrc" ]] ; then source ".rvmrc" ; fi

if [[ "$master_pid" -gt 0 ]] ; then
  echo -e "Unicorns are already running for $project."
else
  unicorn_rails -c $current_path/config/unicorn.rb -E $RAILS_ENV -D
fi
exit $?
