#!/usr/bin/env bash

modules core/array

declare -a help_descriptions
declare -a help_action_names
declare -a help_action_descriptions
declare -a help_notes
declare -a help_dependencies
declare -a help_resources

help_usage="bdsm ${extension} ${namespace:-"[namespace]"} {action} [arguments...]"

