#!/bin/sh

__sm.variables.are.nonempty()
{
  trace_filter variables
  local _variable _variables=("$@")
  shift || fail "Cannot check if variables are nonempty; No variables were given."

  for _variable in "${_variables}"
  do
    eval "[[ -n \"\${${_variable}:-}\" ]]" || return 1
  done
  return 0
}

__sm.variables.are.empty()
{
  trace_filter variables
  local _variable="${1:-}"
  shift || fail "Cannot check if variable is empty, as no variable was given."
  eval "[[ -z \"\${${_variable}:-}\" ]]"
}
