#!/usr/bin/env bash

rvm_install()
{
  curl \
    -s https://rvm.beginrescueend.com/install/rvm \
    -o rvm-installer

  ensure_files_are_executable "rvm-installer"

  ./rvm-installer

  remove_files "rvm-installer"
}

install_gem()
{
  gem install --no-rdoc --no-ri -q "$*"
}

install_gems() {
  local _gem

  for _gem in "$*" ; do
    gem install ${_gem} --no-rdoc --no-ri
  done
}

