#!/usr/bin/env bash

#
# BDSM RVM DSL module functions
#
rvm_install()
{
  curl \
    -s https://rvm.beginrescueend.com/install/rvm \
    -o rvm-installer

  chmod +x rvm-installer

  ./rvm-installer

  rm -f rvm-installer
}

install_gem()
{
  gem install --no-rdoc --no-ri -q "$*"
}

install_gems() {
  local _gem

  for _gem in "$*" ; do
    gem install ${_gem} --no-rdoc --no-ri
  done
}

