#!/usr/bin/env bash

#
# BDSM RVM DSL module functions
#
rvm_install()
{
  enter "${source_path}"
  curl -B http://rvm.beginrescueend.com/install/rvm -o rvm-installer
  chmod +x rvm-installer
  ./rvm-installer
}
