#!/usr/bin/env bash

#
# BDSM RVM module initialization
#
source_files "/etc/rvmrc" "$HOME/.rvmrc"

rvm_files=("$rvm_path/.rvm/scripts/rvm" "$HOME/.rvm/scripts/rvm" "/usr/local/scripts/rvm")
# Attempt to load RVM
files=( $(first $(nonempty_files "${rvm_files[@]}" ) ) )

[[ ${#files[@]} -gt 0 ]] && source_files "$@"

