#!/bin/sh

__sm.ini.parse() {
	local _file
	_file="$1"

	if [[ -f ${_file} ]]
	then
		[[ -s ${_file} ]] || return 0
		# TODO: Replace with sm-ini
		python ${sm_path}/core/internal/python/pini.py -b ${_file}
	else
		log fail "File '${_file}' does not exist."
	fi
}

__sm.ini.load() {
	eval "$(__sm.ini.parse "${1}")"
}

