#!/usr/bin/env bash

read_default()
{
  local key variable token value prefix

  key="${1:-}" ; shift

  [[ -n "${key}" ]] || \
    fail "$extension $action read_default() no arguments passed! "

  while (( $# > 0 )) ; do
    token="$1" ; shift
    case "$token" in
      into|as)
        variable="$1" ; shift
        ;;
      prefix)
        prefix="$1" ; shift
        ;;
      *)
        variable="$token"
        break
      ;;
    esac
  done

  if [[ -z "${variable:-}" ]] ; then
    if [[ -n "${prefix:-}" ]] ; then
      true "${variable:="${prefix:-}_$key"}"
    else
      true "${variable:="$key"}"
    fi
  fi

  value="$(hash_file "${extension_config_path}/defaults" "${key}")"

  eval "${variable}=\"${value}\""
}

