#!/bin/sh

#
# SM Framework Extended Module ~ Service Module
#

ext_service_initialize()
{
  variable_is_nonempty init_scripts_path || init_scripts_path="$(init_scripts_path)"
  variable_is_nonempty confd_path        || confd_path="$(confd_path)"

  # TODO: Account for user service installs...
  # TODO: Merge service_paths and service_root_paths...

  # TODO: determine root_install vs user_install...
  if user is root
  then
    etc_path="/etc"
    var_path="/var"
  else
    etc_path="${packages_path}/active/etc"
    var_path="${packages_path}/active/var"
  fi

  : \
    "${service:="${extension:-${package_name}}"}" \
    "${service_version:="${package_version}"}" \
    "${prefix_path:="${sm_path}/active"}" \
    "${service_bin_path:="${active_path}/bin"}" \
    "${service_sbin_path:="${active_path}/sbin"}" \
    "${service_pid_path:="${var_path}/run/${service}"}" \
    "${service_spool_path:="${var_path}/spool/${service}"}" \
    "${service_config_path:="${etc_path}/${service}"}" \
    "${service_db_path:="${var_path}/db/${service}"}" \
    "${service_data_path:="${var_path}/db/${service}/${package_version}"}" \
    "${service_log_path:="${var_path}/log/${service}"}" \
    "${service_lock_path:="${var_path}/lock/${service}"}" \
    "${service_src_path:="${source_path}/${service}-${package_version}"}" \
    "${service_config_file:="${service_config_path}/${service}.conf"}" \
    "${service_log_file:="${service_log_path}/${service}.log"}" \
    "${service_pid_file:="${service_pid_path}/${service}.pid"}" \
    "${service_lock_file:="${service_lock_path}/${service}.lock"}" \
    "${service_run_as_root_flag:=0}"

  service_paths=(
  "${service_bin_path}"
  "${service_config_path}"
  "${service_pid_path}"
  "${service_spool_path}"
  "${service_data_path}"
  "${service_lock_path}"
  "${service_log_path}"
  )

  service_root_paths=(
  "${var_path}/spool/${service}"
  "${var_path}/log/${service}"
  "${var_path}/run/${service}"
  "${var_path}/lock/${service}"
  "${var_path}/db/${service}"
  )

  if user is root
  then
    if os is darwin
    then
      true "${service_user:="_${service}"}"
    else
      true "${service_user:="${service}"}"
    fi
  else
    true "${service_user:="$USER"}"
  fi

  local _path
  for _path in  "${install_path}/bin" "${install_path}/sbin"
  do
    if paths exist "$_path"
    then
      export PATH="${_path}:$PATH"
    fi
  done

  if variable_is_empty service_binary
  then
    if command exists ${service}
    then
      service_binary="$(command -v ${service})"
    fi
  fi

  service_actions=( start stop restart )
  service_flags=()
  service_start_flags=()
  service_stop_flags=()
  service_restart_flags=()
  service_status_flags=()
  service_reload_flags=()

  export service_paths service_actions service_flags

  if file is empty "${service_pid_file}"
  then
    service_pid=0
  else
    read -r service_pid < "${service_pid_file}"
  fi

  export PATH="/bin:/usr/bin:${prefix_path}/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin:${PATH}"

  service_initialized=1
}

services_avilable()
{
  __sm.extensions.installed module "api/service" "$@"
}

services_list()
{
  local _action="${1:-}" _args

  shift || true

  case "${_action}" in
    (active)
      services_active "$@"
      ;;

    (available)
      services_available "$@"
      ;;

    (installed|*)
      services_installed "$@"
      ;;
  esac
}

services_installed()
{
  # Notify that the services_installed() function has not yet been implemented.
  NIY "Installed services has not yet been implemented."
}

services_available()
{
  # Notify that the services_available() function has not yet been implemented.
  NIY "Installed services has not yet been implemented."
}

service_setup()
{
  (( $# == 0 )) || service_cli $@

  local _path _file

  files source "${extension_path}"/shell/{functions,initialize,cli}

  if user is root
  then
    # TODO: create an 'user_exists' function and use it here.
    user create user "${service_user}" group "${service_user}" >/dev/null 2>&1

    paths create "${service_root_paths[@]}"

    paths chown recursive "${service_user}:${service_user}" "${service_root_paths[@]}"
  fi

  paths create "${service_paths[@]}" "${install_path}"

  for _path in "${service_paths[@]}"
  do
    if variable_is_nonempty _path
    then
      if paths exist "${_path}"
      then
        paths chown recursive "${service_user}:${service_user}" "${_path}"
      else
        warn "While chowning paths it was discovered that '${_path}' is in"\
          "fact nonexistent on the filesystem; this might indicate an error."
      fi
    fi
  done

  ! command exists "${service}_service_setup" || "${service}_service_setup"

  service_install_init_d "${service}"
}

service_uninstall()
{
  NIY "service_uninstall() has not yet been implemented."
  # 1. Remove init scripts.
  # 2. Unload OS service hooks.
  # 3. Deactivate database path.
}

service_start()
{
  (( $# == 0 )) || service_cli $@

  [[ -n "${service}" ]] || fail "To start a service, you must set the 'service' variable."

  if command exists "${service}_start"
  then
    log_step "Starting ${service}..." "${service}_start"
  else
    service_init_start
  fi
}

service_stop()
{
  variable_is_nonempty service ||
    fail "To start a service, you must set the 'service' variable."

  if command exists "${service}_stop"
  then
    log_step "Stopping ${service}..." "${service}_stop"
  else
    service_init_stop
  fi
}

service_reload()
{
  (( $# == 0 )) || service_cli $@

  variable_is_nonempty service ||
    fail "To start a service, you must set the 'service' variable."

  if command exists "${service}_reload"
  then
    "${service}_reload"
  else
    service_init_reload
  fi
}

service_restart()
{
  (( $# == 0 )) || service_cli $@

  variable_is_nonempty service ||
    fail "To start a service, you must set the 'service' variable."

  if command exists "${service}_restart"
  then
    log_step "Restarting ${service}..." "${service}_restart"
  else
    service_init_restart
  fi
}

service_init_restart()
{
  if command exists "${service}_restart"
  then
    log_step "Restarting ${service}..." "${service}_restart"
  else
    log "Restarting ${service}..."
    service_init_stop $@
    service_init_start $@
  fi
}

service_status()
{
  (( $# == 0 )) || service_cli $@

  variable_is_nonempty service ||
    fail "To start a service, you must set the 'service' variable."

  if command exists "${service}_status"
  then
    "${service}_status"
  else
    service_init_status
  fi
}

service_logtail()
{
  (( $# == 0 )) || service_cli $@

  variable_is_nonempty service ||
    fail "To start a service, you must set the 'service' variable."

  if command exists "${service}_logtail"
  then
    "${service}_logtail"
  else
    service_init_logtail
  fi
}

service_info()
{
  (( $# == 0 )) || service_cli $@

  [[ -n "${service}" ]] ||
    fail "In order to get info on a service, the 'service' variable must be set."

  if command exists "${service}_info"
  then
    "${service}_info"
  else
    service_init_info
  fi
}

service_configcheck()
{
  (( $# == 0 )) || service_cli $@

  variable_is_nonempty service ||
    fail "To configcheck a service, the 'service' variable must be set."

  if command exists "${service}_configcheck"
  then
    "${service}_configcheck"
  else
    service_init_configcheck
  fi
}

service_usage() {
  # TODO: Update this for service specific items.
  printf "
Usage:

  $0 [options]

Options:

  --prefix   - specify prefix path
  --src)     - specify source directory
  --user)    - specify user to install as
  --version) - specify version to install
  --licence) - view licence
  --help)    - view this usage information

  "
  return 0
}

service_cli()
{
  local _ignored_args=() _service_args=( $@ ) _token

  number_of_args=${#extension_args[@]}

  for (( index=0 ; index < $number_of_args ; index++ ))
  do
    token="${extension_args[$index]}"

    case "$token" in
      user)
        service_user="${extension_args[$((++index))]}"
        [[ -n "${service_user}" ]] ||
          error "a user name must follow keyword 'user'"
        ;;
      version)
        service_version="${extension_args[$((++index))]}"
        [[ -n "${service_version}" ]] ||
          error "a version number string must follow keyword 'version'"
        ;;
      data)
        service_data_path="${_package_args[$((++index))]}"
        [[ -n "${service_data_path}" ]] ||
          error "a path must follow keyword 'data'"
        ;;
      pid)
        service_pid_path="${_package_args[$((++index))]}"
        [[ -n "${service_pid_path}" ]] ||
          error "a path must follow keyword 'pid'"
        ;;
      log)
        service_log_path="${_package_args[$((++index))]}"
        [[ -n "${service_log_path}" ]] ||
          error "a path must follow keyword 'log'"
        ;;
      config)
        service_config_path="${_package_args[$((++index))]}"
        [[ -n "${service_config_path}" ]] ||
          error "a path must follow keyword 'config'"
        ;;
      lock)
        service_lock_path="${_package_args[$((++index))]}"
        [[ -n "${service_lock_path}" ]] ||
          error "a path must follow keyword 'lock'"
        ;;
      db)
        service_db_path="${_package_args[$((++index))]}"
        [[ -n "${service_db_path}" ]] ||
          error "a path must follow keyword 'db'"
        ;;
      help)
        service_usage
        exit 0
        ;;
      --trace)
        set -o xtrace
        ;;
      *)
        _ignored_args+=("${token}")
        ;;
    esac
  done

  extension_args=( "${_ignored_args[@]}" )

  ext_service_initialize "${extension_args[@]}"
}

service_pid()
{
  local _path="${run_path:="/var/run"}/${service}"
  local _pid=0

  paths create "${_path}"

  if ! file is empty "${_path}/${service}.pid"
  then
    read -r _pid < "${_path}/${service}.pid"
    if os is linux
    then # Sanity check.
      if ! paths exist "/proc/${pid}"
      then
        _pid=0
        rm -f "${_path}/${service}.pid"
      fi
    fi
  fi

  service_pid=${_pid}

  return 0
}

service_load_conf_d()
{
  files source "${confd_path}/${service}.conf"
}

service_install_init_d()
{
  local _service="${1:-}" _version="${2:-${package_version}}"

  variables_must_be_nonempty _service

  paths exist "${init_scripts_path}" ||
    return 0 # No bin/ dir, no need for it to be in the path.

  if user is root
  then
    paths create "/etc/conf.d" "${init_scripts_path}"

    # TODO: Install the service init script...
    if template_exists "${_service}"
    then
      install_template "${_service}" to "${init_scripts_path}/${_service}" \
        mode 0755
    else
      # Use core svc init.d template
      install_template "cli/init.d" \
        to "${init_scripts_path}/${_service}" mode 0755

      seed_template "${init_scripts_path}/${_service}" \
        modules_path "${modules_path}" \
        service "${service}" \
        service_user "${service_user}" \
        service_config_path "${service_config_path}"
    fi

    service_activate "${service}" "${package_version}"

    # TODO: Replace this with install_template + seed_template
    files write \
      string "%s\n" "[ -d \"${prefix_path}/${_service}/active/bin\" ] && " \
      to "/etc/profile.d/${_service}.sh"

    files write append \
      string "%s\n" "PATH=\"\$PATH:${prefix_path}/${_service}/active/bin\" ; export PATH; " \
      to "/etc/profile.d/${_service}.sh"

    files chmod 0755 "/etc/profile.d/${_service}.sh"
  fi
}

service_init_start()
{
  log_step "Starting ${service}..."

  local _result=0 _command=( "${service_binary}" ) _prefix

  if [[ -n "${service_start_flags}" ]]
  then
    _command+=("${service_start_flags[@]}")
  fi

  if [[ -n "${service_flags}" ]]
  then
    _command+=("${service_flags[@]}")
  fi

  if (( service_run_as_root_flag == 1 ))
  then
    user is root || _prefix="sudo"

    if ${_prefix} ${_command[*]}
    then
      true
    else
      error "${service} failed to start."
    fi
  else
    if command run as "${service_user}" "${_command[*]}"
    then
      succeed "${service} successfully started."
    else
      log "${service} failed to start; check ${service_log_file} for details:"
      exec tail -n 50 "${service_log_file}"
      error
    fi
  fi
  log_step success
}

service_init_stop()
{
  (( service_pid > 0 )) || error "Service pid has not been set, or is zero."
  log_step "Stopping ${service}..."
  if command exists "${service}_stop"
  then
    "${service}_stop"
  else
    if kill -QUIT "${service_pid}"
    then
      rm -f "$service_pid_file"
    else
      return $?
    fi
  fi
  log_step success
}

service_init_status()
{
  log "statusing ${service}..."

  local _command=( "${service_binary}" ) _prefix

  if [[ -n "${service_status_flags}" ]]
  then
    _command+=("${service_status_flags[@]}")
  fi

  if [[ -n "${service_flags}" ]]
  then
    _command+=("${service_flags[@]}")
  fi

  if (( service_run_as_root_flag == 1 ))
  then
    user is root || _prefix="sudo"

    if ${_prefix} ${_command[*]}
    then
      true
    else
      error "failed check status of ${service}."
    fi
  else
    if command run as "${service_user}" "${_command[*]}"
    then
      touch "$service_pid_file"
      succeed
    else
      error "failed check status of ${service}."
    fi
  fi
}

service_init_reload()
{
  log "reloading ${service}..."

  local _command=( "${service_binary}" )

  if [[ -n "${service_reload_flags}" ]]
  then
    _command+=("${service_reload_flags[@]}")
  fi

  if [[ -n "${service_flags}" ]]
  then
    _command+=("${service_flags[@]}")
  fi

  if command run as "${service_user}" "${_command[*]}"
  then
    touch "$service_pid_file"
  else
    return $?
  fi
}

service_init_usage()
{
  log "Usage:"
  log "  $0 {start|stop|restart|status|info|logtail}"
}

service_init_logtail()
{
  # TODO: Adjust this to allow for parameter passing.

  tail -n 10 "${service_log_file}"
}

service_init_info()
{
  NIY "service_init_info has not yet been implemented for the service module."
}

service_conf_d()
{
  # TODO: Install a default conf.d template if extension does not define one.
  template_exists "conf.d" || return 0

  install_template "conf.d.template" to "/etc/conf.d/${service}.conf" \
    mode 0644 owner "${service_user}:${service_user}"

  if template_exists "/etc/conf.d/${service}.conf"
  then
    seed_template "/etc/conf.d/${service}.conf" \
      prefix_path "${prefix_path}" \
      init_scripts_path "${init_scripts_path}" \
      modules_path "${modules_path}" \
      confd_path "${confd_path}" \
      extension "${service}" \
      service "${service}"
  fi
}

service_init_action()
{
  local _action="${1:-}"

  service_load_conf_d

  if command exists "${service}_${action}"
  then
    "${service}_${action}"
  else
    if [[ "${service_actions[*]}" = *[[:space:]]${action}[[:space:]]* ]]
    then
      service_init_${action}
    else
      service_init_usage
    fi
  fi

  return $?
}

service_init_d()
{
  service_load_conf_d # Load the configuration file.

  # Sanity checks go here.
  [[ -x "${service_binary}" ]] ||
    fail "Could not find ${service_binary}, or ${service_binary} is not executable."

  service_pid

  service_cli # Parse the script arguments and take action accordingly.

  service_init_action "${service_action}"
}

service_deactivate()
{
  local _service="${1:-"${service}"}"

  [[ -n "${_service}" ]] ||
    fail "A service name must be set or passed in to deactivate a service."

  if files exist "${init_scripts_path}/${_service}"
  then
    chmod_files 0644 "${init_scripts_path}/${_service}"

    if user is root
    then # Add service to system startup
      if os is darwin
      then
        true # TODO: launchctl

      elif command exists rc-update
      then
        rc-update add ${service} default

      elif command exists chkconfig
      then
        chkconfig ${service} on

      #elif command exists svc
      #then
      #  svc ${service} on # TODO: daemontools start on boot

      else # Fall back on rc.local to start redis at system startup.
        if files exist "/etc/rc.local"
        then
          if ! files contain string "${service} start" "/etc/rc.local"
          then
            files write append string "${init_scripts_path}/${service} start" \
              to /etc/rc.local
          fi
        fi
      fi
    fi
  fi
  # TDOO: hook into system's paths.
}

service_activate()
{
  local _service="${1:-"${service}"}"

  [[ -n "${_service}" ]] ||
    fail "The service name must be set or passed in to activate a service."

  local _version="${2:-${package_version}}"

  variables_must_be_nonempty _service _version

  if files are symlinks "${service_db_path}/active"
  then # TODO: use versionedfs to check if a version is active.
    service_deactivate "${_service}"
  fi

  if paths exist "${service_db_path}/${_version}"
  then
    log "Activating service ${_service} version ${_version}."

    files link symbolic force \
      from "${service_db_path}/${_version}" \
      to "${service_db_path}/active"

    if files exist "${init_scripts_path}/${service}"
    then
      chmod_files 0755 "${init_scripts_path}/${service}"

      if os is linux
      then
        if user is root
        then # Add service to system startup
          if command exists rc-update
          then
            rc-update remove ${service} default

          elif command exists chkconfig
          then
            chkconfig ${service} off

            #elif command exists svc
            #then
            #  svc ${service} off
            #  TODO: daemontools remove start on boot

          else # Fall back on rc.local to start redis at system startup.
            if ! files contain string "${service} start" "/etc/rc.local"
            then
              sed -i -e "d#${init_scripts_path}/${service} start#" /etc/rc.local
            fi
          fi
        fi
      elif os is darwin
      then
        true # TODO: launchctl
      else # ::shrug::
        if files exist "/etc/rc.local"
        then
          if ! files contain string "${service} start" "/etc/rc.local"
            # TODO: change this to use replace_content
            sed -i -e "d#${init_scripts_path}/${service} start#" /etc/rc.local
          fi
        fi
      fi
    fi
  fi
}

service_status()
{
  log "${service}:"

  if [[ -s "${service_pid_file}" ]] && (( $(head -1 ${service_pid_file}) > 0 ))
  then
    local pid=$(head -1 ${service_pid_file})
    local ps=$(ps -p ${pid} -ostate,sgi_rss,vsize | tail -1)

    log "  status: running"
    log "  version: ${service_version}"
    log "  process: "
    log "    pid: ${pid}"
    if os is linux
    then
      log "    parent_pid: $(awk  '/^PPid:/{print $2}' /proc/${pid}/status)"
      log "    state: $(printf "$ps" | awk '{print $1}')"
      log "    rss: $(printf "$ps" | awk '{print $2}')"
      log "    vsz: $(printf "$ps" | awk '{print $3}')"
    fi

    if command exists lsof
    then
      local cwd= binary= libraries=() tcp_ports=() udp_ports=() sockets=() \
        logs=() string
      while read -r line
      do
        case "$line" in
          (*[[:space:]]cwd[[:space:]]*)
            cwd="${line##* }"
            ;;
          (*[[:space:]]txt[[:space:]]*)
            binary="${line##* }"
            ;;
          (*/lib/*)
            string="${line%% (*}"
            libraries+=("${string##* }")
            ;;
          (*.log*)
            logs+=("${line##* }")
            ;;
          (*.sock*)
            sockets+=("${line##* }")
            ;;
          (*TCP*)
            string="${line%% (*}"
            tcp_ports+=("${string##* }")
            ;;
          (*)
            true # ignore
          ;;
        esac
      done < <(lsof -U -p ${pid})

      log "    cwd: ${cwd}"
      log "    binary: ${binary}"

      if (( ${#logs[@]} > 0 ))
      then
        log "    logs:"
        array sort asc logs
        array unique logs
        for log in "${logs[@]}"
        do
          printf "      - %s\n" "${log}"
        done
      fi

      if (( ${#libraries[@]} > 0 ))
      then
        log "    libraries:"
        array sort asc libraries
        array unique libraries
        for library in "${libraries[@]}"
        do
          printf "      - %s\n" "${library}"
        done
      fi

      if (( ${#tcp_ports[@]} > 0 ))
      then
        log "    tcp_ports:"
        array sort asc tcp_ports
        array unique tcp_ports
        for tcp_port in "${tcp_ports[@]}"
        do
          printf "      - %s\n" "${tcp_port}"
        done
      fi

      if (( ${#sockets[@]} > 0 ))
      then
        log "    sockets:"
        array sort asc sockets
        array unique sockets
        for socket in "${sockets[@]}"
        do
          printf "      - %s\n" "${socket}"
        done
      fi
    fi
  else
    log "  status: not running."
  fi

  if command exists "${service}_status"
  then # Run the service specific status function, if it exists
    "${service}_status"
  fi
}

service_signal()
{
  local _signal="${1}" _pid="${2:-0}"
  shift || fail "Cannot signal service;"\
    " Signal must be given as the first parameter and be one of:"\
    " {KILL,QUIT,TERM,USR1,USR2,TTIN,TTOU,a digit})."
  shift || fail "Cannot signal service;"\
    " Module name not given as second parameter."

  [[ -n "${_pid}" ]] ||
    fail "pid to signal must be passed in as the second parameter;"\
    " please check your code (see trace below.)"

  case "${_signal}" in
    KILL|QUIT|TERM|USR1|USR2|TTIN|TTOU|WINCH|+([[:digit:]]))
      if (( _pid > 0 ))
      then
        kill -${_signal} ${_pid}
      else
        log "Not sending signal ${_signal} to process, as pid is 0 (process not found/running)."
      fi
      ;;
    *)
      fail "Signal must be one of:"\
        " {KILL,QUIT,TERM,USR1,USR2,TTIN,TTOU,a digit})."
      ;;
  esac
}

