#!/bin/sh

install_initialize()
{
  typeset -ga cleanse_paths directories binaries files aux_paths configs
  cleanse_paths=( external completion modules extensions )
  directories=( bin )
  binaries=( sm sm-ll smp )
  files=( LICENSE VERSION README.md )
  aux_paths=( log tmp src )
  configs=( user ) # TODO move this to /etc/sm/ and/or $HOME/.sm/
}

perform()
{
  paths enter "${sm_path}"
  "$*"
}

prepare_for_installation()
{
  typeset directory _path

  __sm.log.step "Ensuring that installation target path exists (${install_path})"
  paths create "${install_path}"
  paths enter "${install_path}"
  __sm.log.step success

  for directory in "${cleanse_paths[@]}"
  do
    _path="${install_path}/${directory}"
    if paths exists "${_path}"
    then
      __sm.log.step "Removing old sm component path (${_path})"\
        rm -rf "${_path}"
    fi
  done

  __sm.log.step "Creating install path directories (${directories[*]} ${aux_paths[*]})" \
  paths create "${directories[@]}" "${aux_paths[@]}"
}

cleanse_targets()
{
  typeset _path _entity
  _path="$1"
  (( $# )) && shift || __sm.log.fail "Usage:\n\n  cleanse_targets {target} {paths/files under target}"
  for _entity in "$@"
  do
    rm -rf "${_path}/${_entity}"
  done
}

install_core()
{
  typeset _dir

  __sm.log.step "Installing core directories (${directories[*]})"
  cleanse_targets "${install_path}" "${directories[@]}"
  paths copy to "${install_path}/" "${directories[@]}"
  __sm.log.step success

  __sm.log.step "Installing core files (${files[*]})"
  cleanse_targets "${install_path}" ${files[@]}
  files copy to "${install_path}" ${files[@]}
  __sm.log.step success

  __sm.log.step "Installing core extension set"
  cleanse_targets "${install_path}/" "core"
  paths copy to "${install_path}/" "core"
  __sm.log.step success
}

install_configuration_files()
{
  __sm.log.step "Ensuring configuration files exist (${configs[*]})"
  for config_file in "${configs[@]}"
  do
    files create "${install_path}/config/${config_file}"
  done
  __sm.log.step success
}

setup_shell_completion()
{
  typeset _prefix _mode _name completion_prefix
  _prefix="/etc"

  paths exists "${_prefix}/bash_completion.d" || return 0

  completion_prefix="${_prefix}/bash_completion.d"
  _name="sm.bash"
  _mode="0644"

  templates install "install/sm-completion.sh" \
    to "${completion_prefix}/${_name}"

  templates seed "${completion_prefix}/${_name}" \
    sm_path "${install_path}"

  files chmod "${_mode}" "${completion_prefix}/${_name}"
}

setup_profile_d()
{
  typeset _PATH
  _PATH="PATH=\"\${PATH}:${install_path}/bin:${install_path}/pkg/active/bin:${install_path}/pkg/active/sbin\""

  if user is root
  then
    paths create "${profile_d_path}"
    if os is darwin
    then
      if ! files exist "/etc/profile" ||
        ! files contain string "${profile_d_path}" "/etc/profile"
      then
        templates install install/etc_profile to /etc/profile
        templates seed /etc/profile profile_d_path "${profile_d_path}"
      fi
    fi

    if files exist "${profile_d_path}/sm.sh"
    then
      if ! files contain string "${install_path}/pkg/active/sbin" "${profile_d_path}/sm.sh"
      then
        files write string "${_PATH}" to "${profile_d_path}/sm.sh"
      fi
    else
      files write string "${_PATH}" to "${profile_d_path}/sm.sh"
    fi

    files chmod 0755 "${profile_d_path}/sm.sh"
  else
    log "\nNOTE:\n"\
    "Since you are installing as a user ($USER), in order to ensure that the 'sm' "\
    "command is available to you add the following to your startup profile:\n"\
    "    export ${_PATH}\n"\
    "Then either close the current shell or source the profile file.\n"

    # TODO: Provide a way to do this through the cli but outside the install:
    #files create "$HOME/.profile" "$HOME/.bashrc" "$HOME/.bash_profile"

    #if ! files contain string "$HOME/.profile" "$HOME/.bashrc"
    #then
    #  files write appnd \
    #    string "if test -s \"$HOME/.profile\" ; then . \"$HOME/.profile\" ; fi"\
    #    to "$HOME/.bashrc"
    #fi

    #if ! files contain string  "$HOME/.bashrc" "$HOME/.bash_profile"
    #then
    #  files write append \
    #    string "if test -s \"$HOME/.bashrc\" ; then . \"$HOME/.bashrc\" ; fi"\
    #    to "$HOME/.bash_profile"
    #fi

    #if ! files contain string "${profile_d_path}" "$HOME/.profile"
    #then
    #  files write append \
    #    string "\nif test -d '${profile_d_path}' ; then for profile in \"${profile_d_path}\"/*.sh ; do if test -x \"\$profile\" ; then . \"\$profile\" ; fi ; done ; unset profile ; fi" \
    #    to "$HOME/.profile"
    #fi
  fi
}

set_sm_path()
{
  files replace regex "^sm_path=.*" \
    with "sm_path=\"${install_path}\"" \
    "${install_path}/bin/sm"

  files replace regex "^sm_path=.*" \
    with "sm_path=\"${install_path}\"" \
    "${install_path}/bin/smp"

  files replace regex "^saved_sm_path=.*" \
    with "saved_sm_path=\"\${sm_path:-${install_path}}\"" \
    "${install_path}/core/sm/shell/core/initialize"
}

make_binaries_executable()
{
  typeset _binary
  for _binary in "${binaries[@]}"
  do
    file chmod 0755 "${install_path}/bin/${_binary}"
  done
}

set_binaries_shell()
{
  typeset _binary
  for _binary in sm smp
  do
    file replace \
      regex "^#!.*$" \
      with "#!/bin/${sm_shell}" \
      in "${install_path}/bin/${_binary}"
  done
}

create_versionedfs_paths()
{
  versionedfs create \
    path "${install_path}/pkg" strategy fhs method link activate first

  versionedfs create \
    path "${install_path}/sets" strategy name method copy activate first

  versionedfs create \
    path "${install_path}/exts" strategy name method copy activate first
}

install_sm()
{
  log "S{cripting,ystem,tack} Management (SM) Framework (Core) Installation:"

  prepare_for_installation

  perform install_core

  perform create_versionedfs_paths

  perform set_sm_path

  perform install_configuration_files

  set_binaries_shell

  __sm.log.step "Ensuring that binaries are executable" \
    make_binaries_executable

  perform setup_profile_d

  if user is root
  then
    __sm.log.step "Setting up sm shell completion (${completion_prefix}/${_name})" \
      perform setup_shell_completion
  fi

  __sm.log.succeed "S{cripting,ystem,tack} Management (SM) Framework (Core) installed."
}

