#!/usr/bin/env bash

description "${extension} BDSM extension."

actions "  list     - List services installed through BDSM extensions using the service module.
  active     - List active services versions.
  activate   - Activate given package and version.
  deactivate - Deactivate given package."

show_help usage
