#!/usr/bin/env bash

modules()
{
  if (( trace_flag < 2 )) ; then set +o xtrace ; fi

  local _module _bdsm _extension _path _file _modules=("$@")

  (( ${#_modules[@]} > 0 )) || fail "No modules specified to load."

  for _module in "${_modules[@]}"
  do
    if module_is_loaded "${_module}"
    then
      continue # The module has already been loaded, continue to the next one.
    else
      _bdsm="${modules_path}/bash/${_module}"
      _extension="${extension_modules_path}/bash/${_module}"

      for _path in "${_bdsm}" "${_extension}"
      do
        for _file in dsl initialize
        do
          if [[ -s "${_path}/${_file}" ]]
          then
            source "${_path}/${_file}"
          fi
        done
      done
      modules+=("${_module}")
    fi
  done

  if (( trace_flag == 1 )) ; then set -o xtrace ; fi
}

module_load()
{
  local _file _files=("$@")

  for _file in "${_files[@]}" ; do
    source_files "${extension_modules_path:-"$modules_path"}/bash/${_file}"
  done
}

module_is_loaded()
{
  local _name="${1:-}"

  [[ -n "${_name}" ]] ||
    fail "Cannot determine if a module is loaded as no module was given."

  case " ${modules[@]} " in
    (*[[:space:]]${_name}[[:space:]]*)
      return 0
      ;;
    (*)
      return 1
      ;;
  esac
}

