#!/usr/bin/env bash

#
# parse CLI arguments
#
set +o nounset
set +o noclobber

while (( $# > 0 ))
do
  token="$1"
  shift

  case "$token" in
    # TODO: extension detection "did you mean"

    # TODO: Fall back on default actions instead of specifying them here
    #       In case the user has set their default serfice in the environment.

    -*)
      case "$token" in
        --disable-hooks)
          hooks_flag=0
          ;;

        --project)
          project="$1"
          shift
          ;;

        --environment)
          environment="$1"
          shift
          ;;

        --repo|repository)
          repository="$1"
          shift
          ;;

        --revision)
          revision="$1"
          shift
          ;;

        --user)
          user="$1"
          shift
          ;;

        --head)
          head_flag=1
          ;;

        --debug)
          true ${debug_flag:=0} $(( debug_flag++ ))
          enable_debug
          ;;

        --help)
          action="help"
          extension="${1:-core}"
          parse_break=1
          ;;

        -v|--version)
          extension="core"
          action="version"
          ;;

        --trace)
          true ${trace_flag:=0} $(( trace_flag++ ))
          enable_trace
          ;;

        --) extension_args=("$@") # Stop processing arguments.
          ;;
        *)
          error "Unknown flag '${token}'"
          ;;
      esac
      ;;

    *)
      if variable_is_empty extension
      then
        if path_exists "$extensions_path/$token"
        then
          extension="$token"
          continue
        else
          case "$token" in
            list|ls)
              extension="ext"
              action="list"
              extension_args=("$@")
              parse_break=1
              ;;

            bdsmrc)
              extension="core"
              action="$token"
              extension_args=("${action}" "$@")
              parse_break=1
              ;;

            docopen)
              extension="core"
              action="docopen"
              parse_break=1
              ;;

            help)
              action="help"
              extension="${1:-core}"
              parse_break=1
              ;;

            get|version)
              extension="core"
              action="${token}"
              extension_args=("$@")
              parse_break=1
              ;;

            activate|enable)
              extension="ext"
              action="package"
              extension_args=("activate" "$@")
              parse_break=1
              ;;

            deactivate|disable)
              extension="ext"
              action="package"
              extension_args=("deactivate" "$@")
              parse_break=1
              ;;

            add|extend)
              extension="ext"
              action="extend"
              extension_args=("$@")
              parse_break=1
              ;;

            install)
              extension="ext"
              action="extend_and"
              extension_args=(package install "$@")
              parse_break=1
              ;;

            ext|extension|extensions)
              extension="ext"
              action="${1:-help}"
              extension_args=("$@")
              parse_break=1
              ;;

            mod|module|modules)
              extension="mod"
              action="${1:-list}"
              extension_args=("$@")
              parse_break=1
              ;;

            srv|service|services)
              extension="srv"
              action="${1:-list}"
              extension_args=("$@")
              parse_break=1
              ;;

            pkg|package|packages)
              extension="pkg"
              action="${1:-list}"
              extension_args=("$@")
              parse_break=1
              ;;

            edit|open|update|create)
              extension="ext"
              action="${token}"
              extension_args=("$@")
              parse_break=1
              ;;

            *)
              if variable_is_empty extension
              then
                error "Extension '${token}' is not installed."
              fi
              ;;
          esac
        fi
      fi

      if (( parse_break == 1 ))
      then
        break
      fi

      if variable_is_empty action
      then
        if path_exists "${extensions_path}/${extension}/actions/$token"
        then
          namespace="$token"
          extension_args=("$@")
        else
          if variable_is_nonempty namespace
          then
            token="${namespace}/${token}"
          fi
          if file_is_executable "${extensions_path}/${extension}/actions/$token"
          then
            action="$token"
            extension_args=("$@")
            parse_break=1
          fi
        fi
      fi
      ;;
  esac

  if variable_is_nonempty parse_break || variable_is_nonempty error_message
  then
    unset parse_break
    break
  fi
done

# A default action has the same name as the extension.
if variable_is_empty action
then
  if file_is_executable "${extensions_path}/${extension}/actions/${extension}"
  then
    action="${extension}"
  elif symlink_exists "${extensions_path}/${extension}/actions/default"
  then
    action="default"
  else
    action="help"
  fi

  if variable_is_nonempty namespace
  then
    action="${namespace}/${action}"
  fi
fi


