#!/usr/bin/env bash

shopt -s extglob # Extended globs must always be on for BDSM.

# load bdsmrc files, cascaded. Settings in these files trump all.
for file in /etc/bdsmrc "$HOME/.bdsmrc"
do
  if [[ -s "${file}" ]]
  then
    . "${file}"
  fi
done

if [[ -z "${prefix_path:-}" ]]
then
  if (( UID == 0 ))
  then # FHS
    prefix_path="/usr/local"
  else # HOME
    prefix_path="$HOME"
  fi
fi

if [[ -z "${bdsm_path:-}" ]]
then
  if [[ "$prefix_path" = "$HOME" ]]
  then
    bdsm_path="${prefix_path}.bdsm"
  else
    bdsm_path="${prefix_path}/bdsm"
  fi
fi

modules_path="${bdsm_path}/modules"

export prefix_path bdsm_path modules_path initial_pwd


if (( UID == 0 ))
then # FHS
  :\
    "${var_path:="/var"}" \
    "${etc_path:="/etc"}"
else
  :\
    "${var_path:="${bdsm_path}/var"}" \
    "${etc_path:="${bdsm_path}/etc"}"
fi

: \
  "${modules_path:="${bdsm_path}/modules"}" \
  "${extensions_path:="${bdsm_path}/extensions"}" \
  "${templates_path:="${bdsm_path}/templates"}" \
  "${src_path:="${bdsm_path}/src"}" \
  "${tmp_path:="${bdsm_path}/tmp"}" \
  "${bin_path:="${bdsm_path}/bin"}" \
  "${archives_path:="${bdsm_path}/archives"}" \
  "${extensions_src_path:="${src_path}/extensions"}" \
  "${remote:="origin"}" \
  "${branch:="master"}" \
  "${language:="bash"}" \
  "${user:=$USER}" \
  "${keep_releases:=4}" \
  "${hooks_flag:=1}" \
  "${PAGER:="cat -v"}" \
  "${config_path:="${extensions_path}/core/config"}"

# Load module() function and then load core modules.
source "${modules_path}/bash/modules/dsl"
source "${modules_path}/bash/modules/initialize"

modules \
  array trace logging time variables environment filesystem system users extensions

module_load core/dsl

if os_is_solaris
then # custom compilations + g*
  export PATH="/usr/local/bin:/usr/sfw/bin:/usr/sbin:/usr/bin:/opt/local/bin"
fi

# Ensure variables desired to be exported to extensions actually are.
bdsm_exports

