#!/usr/bin/env bash

# Example Usage:
#
# package_definition \
#   name "bash"
#   version "4.2"
#   url "ftp.gnu.org/gnu/bash/"
#
package_definition()
{
  while (( $# > 0 )) ; do
    key="$1" ; shift
    if [[ -n "${1:-}" ]] ; then
      value="$1" ; shift
    else
      if echo "$key" | grep '=' ; then
        fail "Invalid key '${key}'\n => Guess: Most likely the '=' is supposed to be a ' '."
      else
        fail "Value not specified for key '${key}'\n => They tend to come in pairs :)"
      fi
    fi

    case "$key" in
      name)
        package_name="${value}"
        ;;
      version)
        package_version="${value}"
        ;;
      file)
        package_file="${value}"
        ;;
      dir)
        package_dir="${value}"
        ;;
      url)
        package_url="${value}"
        ;;
      base_url)
        package_base_url="${value}"
        ;;
      patches_url)
        package_patches_url="${value}"
        ;;
      md5_url)
        package_md5_url="${value}"
        ;;
      bin_path)
        bin_path="${value}"
        ;;
      prefix_path)
        prefix_path="${value}"
        ;;
      source_path)
        source_path="${value}"
        ;;
      target_path)
        target_path="${value}"
        ;;
      archive_format)
        archive_format="${value}"
        ;;
      # TODO: Simplify into
      #(+([[[:alnum:]]|])_path|name|version|url|md5_url)
      #  eval "${key}=${value}"
      #  ;;
      *)
        fail "Unknown key '${key}' (value: ${value})"
      ;;
    esac
  done
}

package_install()
{
  ensure_nonempty package_name package_version archive_format

  true "${package_dir:="${package_name}-${package_version}"}"

  ensure_paths_exist "${source_path}"

  enter "${source_path}"

  if command_exists "${package_name}_download"
  then
    "${package_name}_download"
  else
    log "Downloading ${package_name} ${package_version}"
    package_fetch
  fi

  if command_exists "${package_name}_extract"
  then
    "${package_name}_extract"
  else
    log "Extracting ${package_name} ${package_version}"
    package_extract
  fi

  enter "${package_dir}"

  if command_exists "${package_name}_patch"
  then
    "${package_name}_patch"
  else
    log "Applying any patches found for ${package_name} ${package_version}"
    package_patch
  fi

  if command_exists "${package_name}_configure"
  then
    "${package_name}_configure"
  else
    log "Configuring ${package_name} ${package_version}"
    package_configure
  fi

  if command_exists "${package_name}_build"
  then
    "${package_name}_build"
  else
    log "Building ${package_name} ${package_version}"
    package_build
  fi

  if command_exists "${package_name}_install"
  then
    "${package_name}_install"
  else
    log "Installing ${package_name} ${package_version}"

    package_make_install

    log "Installed ${package_name} ${package_version}."
  fi

  if command_exists "${package_name}_postinstall"
  then
    "${package_name}_postinstall"
  fi

  package_activate_if_first "${package_name}" "${package_version}"
}

package_fetch_md5()
{
  ensure_nonempty package_name package_version archive_format

  local download_url

  true \
    "${package_file:="${package_name}-${package_version}.${archive_format}"}" \
    "${packge_md5_url:="${package_base_url}/${package_file}.md5"}" \
    "${package_md5:=$( hash_file "${extension_config_path}/md5" "${package_file}" )}"

  if [[ -z "${package_md5}" && -n "${package_md5_url}" ]]
  then
    curl -L "${packge_md5_url}" -o "${package_file}.md5" ||
      error "Fetching md5 from '${package_md5_url}' failed."

    package_md5=$(cat "${package_file}.md5")
  fi
}

file_matches_md5()
{
  local file="$1" md5="$2" file_md5

  [[ -s "${file}" ]] || return 1

  if os_is_linux
  then
    _command="md5sum"
  elif os_is_darwin
  then
    _command="/sbin/md5 -q"
  fi

  file_md5="$($_command "$file")"

  [[ "${file_md5// *}" = "$md5" ]]
}

package_fetch()
{
  ensure_nonempty package_name package_version archive_format

  : \
    "${package_file:="${package_name}-${package_version}.${archive_format}"}" \
    "${package_url:="${package_base_url}/${package_file}"}"

  package_fetch_md5

  file_matches_md5 "${package_file}" "${package_md5}" || {
    log "${package_file} does not match md5 ${package_md5}"

    remove_files "${package_file}"

    curl -L "${package_url}" -o "${package_file}" ||
      error "Downloading ${package_name} from '${package_url}' to '${package_file}' failed "
  }
}

package_extract()
{
  case "${archive_format}" in
    tar.gz|tgz) # gzip
      tar zxf "${package_file}"
      ;;
    xz) # LZMA
      tar Jxf "${package_file}"
      ;;
    tar.bz2) # bzip
      tar jxf "${package_file}"
      ;;
    zip)
      unzip "${package_file}" -C ${source_path}
      ;;
    *)
      error "Unknown archive format for ${package_file}"
      ;;
  esac
}

package_configure()
{
  local _command

  if [[ -n ${configure__command:-} ]]
  then
    _command="${configure__command}"
  else
    export PREFIX="${install_base_path}/${package_version}"

    _command="./configure ${configure_flags[@]:-"--prefix=${install_path:-$prefix_path}"}"

    [[ -x ./configure ]] || {
      log "./configure not found or not executable, skipping configuration step."
      return 0
    }
  fi

  ${_command} > configure.log 2>&1 ||
    error "Configuration of ${package_name} ${package_version} failed, seek help..."

  log "Configuration of ${package_name} ${package_version} successful."
}

package_build()
{
  local _command

  if [[ -n ${make__command:-} ]]
  then
    _command="${make__command}"
  else
    _command="make ${make_flags[@]:-"-j$(os_cpu_count)"}"
  fi

  ${_command} > make.log 2>&1 ||
    error "Compilation if ${package_name} ${package_version} failed! "
}

package_make_install()
{
  local _command

  if [[ -n ${make__command:-} ]]
  then
    _command="${make__command}"
  else
    _command="make ${make_install_flags[@]:-install}"
  fi

  ${_command} > make.install.log 2>&1 ||
    error "Failed to make install of ${package_name} ${package_version} failed! "

  log "Installation of ${package_name} ${package_version} was successful! "
}

package_activate()
{
  local _package="${1:-}" _version="${2:-}"

  ensure_nonempty _package _version

  symlink_exists "${prefix_path}/${_package}/active" &&
    package_deactivate "${_package}"

  log "Activating ${_package} ${_version}"

  link "${prefix_path}/${_package}/${_version}" \
    to "${prefix_path}/${_package}/active"

  package_ldconfig "${_package}"

  package_profile_d "${_package}"

  package_conf_d "${_package}"
}

package_deactivate()
{
  local _package="${1:-}" _file _files

  ensure_nonempty _package

  log "Deactivating ${_package}"

  _files=(
    "${prefix_path}/${_package}/active"
    "/etc/ld.so.profile.d/${_package}.conf"
    "/etc/profile.d/${_package}.sh"
  )

  for _file in $"${_files[@]}"
  do
    if file_exists "${_file}"
    then
      remove_files "${_file}"
    fi
  done
}

package_activate_if_first()
{
  local _package="${1:-}" _version="${2:-}"

  ensure_nonempty _package _version

  symlink_exists "${prefix_path}/${_package}/active" ||
    package_activate "${_package}" "${_version}"
}

package_ldconfig()
{
  local _package="${1:-}" _path _files

  ensure_nonempty _package

  directory_exists "${prefix_path}/${_package}/active/lib" ||
    return 0 # no lib/ directory for activated package, no need to update ldconfig

  # TODO: Figure out if solaris and freebsd have an analog to this?
  if running_as_root
  then
    if os_is_linux
    then
      log "Updating ldconfig for ${_package}"
      ensure_paths_exist "/etc/ld.so.profile.d"

      printf "%s\n" "${prefix_path}/${_package}/active/lib" \
        > "/etc/ld.so.profile.d/${_package}.conf"

      chmod_files 0644 "/etc/ld.so.profile.d/${_package}.conf"

      ldconfig
    elif os_is_darwin
    then # Cluster Fuck.
      true
      # This should be handled by the profile.d?
      # _files=($(find "${prefix_path}/${_package}/active" -mindepth 1 -maxdepth 1 -type d))
      # (( ${#_files[@]} > 0 )) && copy_files_to "${prefix_path}" "${_files[@]}"
    fi
  fi
}

package_profile_d()
{
  local _package="${1:-}"

  ensure_nonempty _package

  directory_exists "${prefix_path}/${_package}/active/bin" ||
    return 0 # No bin/ dir, no need for it to be in the path.

  if running_as_root
  then
    ensure_paths_exist "/etc/profile.d"
    ensure_files_exist "/etc/profile"

    log "Updating shell profile for ${_package}"

    if os_is_darwin
    then
      if ! awk '/\/etc\/profile\.d\//' /etc/profile > /dev/null 2>&1
      then
        printf "%s" 'if [ -d /etc/profile.d ]; then for profile in /etc/profile.d/*.sh ; do ' \
          >> /etc/profile

        printf "%s\n" " [ -x \"\$profile\" ] && . \"\$profile\" ; done ; unset profile ; fi" \
          >> /etc/profile
      fi
    fi

    printf "%s\n" "[ -d \"${prefix_path}/${_package}/active/bin\" ] && " \
      > "/etc/profile.d/${_package}.sh"

    printf "%s" "PATH=\"\$PATH:${prefix_path}/${_package}/active/bin\" ; export PATH; " \
      >> /etc/profile.d/${_package}.sh

    chmod_files 0755 /etc/profile.d/${_package}.sh
  fi
}

package_conf_d()
{
  # TODO: package_conf_d, detect if ext template file exists and put it in place.
  if template_exists "conf.d.template"
  then
    install_template "conf.d.template" to "/etc/conf.d/${extension}.conf" \
      mode 0644 owner "${package_user}:${package_user}"
  fi

  if template_exists "/etc/conf.d/${extension}.conf"
  then
    seed_template "/etc/conf.d/${extension}.conf" \
      confd_path "${confd_path}" \
      extension "${extension}"
  fi
}

package_uninstall()
{
  ensure_nonempty package_name package_version archive_format

  true "${package_dir:="${package_name}-${package_version}"}"

  package_make_uninstall ||
    error "Failed to uninstall ${package_name} from ${prefix_path}."

  log "Uninstalled ${package_name} from ${prefix_path}."
}

package_patch()
{
  local _patches _patch

  directory_exists "${extension_patches_path}" || return 0

  # TODO: Three level hierarchy based on patches/{OS}/{version},
  #       root level as 'global' always installed.

  # TODO: Test each dir for existence and skip if missing
  _patches=($(find "${extension_patches_path}" -mindepth 1 -maxdepth 1 -iname '*.patch' -type f))
  package_apply_patches "${_patches[@]}"

  directory_exists "${extension_patches_path}/$(os_type)" || return 0

  _patches=($(find "${extension_patches_path}/$(os_type)" -mindepth 1 -maxdepth 1 -iname '*.patch' -type f))
  package_apply_patches "${_patches[@]}"

  directory_exists "${extension_patches_path}/$(os_type)/${package_version}" || return 0

  _patches=($(find "${extension_patches_path}/$(os_type)/${package_version}" -mindepth 1 -maxdepth 1 -iname '*.patch' -type f))

  package_apply_patches "${_patches[@]}"
}

package_apply_patches()
{
  local _patch _patches=("$@")

  (( ${#_patches[@]} > 0 )) || fail "Cannot apply patches as no patches were given."

  for _patch in "${_patches[@]}" ; do
    # TODO: apply the patch...
    true
  done
}

package_usage() {
  printf "
  Usage:

  $0 [options]

  options:

  --prefix   - specify prefix path
  --src)     - specify source directory
  --data)    - specify data directory
  --user)    - specify user to install as
  --version) - specify version to install
  --licence) - view licence
  --help)    - view this usage information

  "
  return 0
}

package_cli()
{
  local _ignored_args=()

  number_of_args=${#extension_args[@]}

  for (( index=0 ; index < $number_of_args ; index++ ))
  do
    token="${extension_args[$index]}"

    case "$token" in
      --prefix)
        prefix_path="${extension_args[$((++index))]}"
        ;;
      --src)
        src_path="${extension_args[$((++index))]}"
        ;;
      --data)
        data_path="${extension_args[$((++index))]}"
        ;;
      --user)
        package_user="${extension_args[$((++index))]}"
        ;;
      --version)
        package_version="${extension_args[$((++index))]}"
        ;;
      --base_url)
        package_base_url="${extension_args[$((++index))]}"
        ;;
      --file)
        package_file="${extension_args[$((++index))]}"
        ;;
      --directory)
        package_directory="${extension_args[$((++index))]}"
        ;;
      --archive_format)
        archive_format="${extension_args[$((++index))]}"
        ;;
      --activate|activate)
        # TODO: Throw error if parameter is not specified.
        if (( ${#extension_args[@]} > 0 ))
        then
          package_activate "${extension}" "${extension_args[$((++index))]}"
        else
          error "Cannot activate ${extension}, no version was given."
        fi
        ;;
      --deactivate|deactivate)
        package_deactivate "${extension}"
        ;;
      --md5)
        package_md5="${extension_args[$((++index))]}"
        ;;
      --licence)
        extension_license
        exit 0
        ;;
      --help)
        package_usage
        exit 0
        ;;
      --trace)
        set -o xtrace
        ;;
      *)
        _ignored_args+=("${token}")
        ;;
    esac

    (( ${#_ignored_args[@]} > 0 )) && extension_args=( "${_ignored_args[@]}" )

  done
}
