#!/usr/bin/env bash

modules filesystem system templates

# Ensure that default values are set.
true \
  "${prefix_path:="/usr/local"}" \
  "${archive_format:=tar.gz}" \
  "${package_name:=${extension}}"

true \
  "${bin_path:="${prefix_path}/bin"}" \
  "${source_path:="${prefix_path}/src"}" \

if running_as_root ; then
  true \
    "${log_path:="${prefix_path}/log"}" \
    "${data_path:="/var/db/${package_name}"}" \
    "${log_path:="/var/log/${package_name}"}" \
    "${package_user:="${package_name}"}"

else
  true \
    "${log_path:="${prefix_path}/log"}" \
    "${data_path:="${prefix_path}/.${package_name}"}" \
    "${package_user:="$USER"}"
fi

init_scripts_path="$(init_scripts_path)"

export LDFLAGS="${LDFLAGS:-} -L${prefix_path}/lib"

export package_name prefix_path package_name package_version archive_format package_file package_url package_md5_url prefix_path bin_path source_path

