#!/usr/bin/env bash

modules system array

variable_is_nonempty init_scripts_path || init_scripts_path="$(init_scripts_path)"
variable_is_nonempty confd_path        || confd_path="$(confd_path)"

declare -a service_flags service_actions service_paths

: \
  "${service:="${extension}"}" \
  "${service_user:="${package_user:-"${service}"}"}" \
  "${prefix_path:="/usr/local/${service}/active"}" \
  "${service_binary:="${prefix_path}/bin/${service}"}" \
  "${service_bin_path:="${install_path}/bin"}" \
  "${service_pid_path:="/var/run/${service}"}" \
  "${service_config_path:="/etc/${service}"}" \
  "${service_db_path:="/var/db/${service}"}" \
  "${service_data_path:="/var/db/${service}/${package_version}/data"}" \
  "${service_log_path:="/var/log/${service}"}" \
  "${service_lock_path:="/var/lock/${service}"}" \
  "${service_src_path:="${source_path}/${service}-${package_version}"}" \
  "${service_config_file:="${service_config_path}/${service}.conf"}" \
  "${service_log_file:="${service_log_path}/${service}.log"}" \
  "${service_pid_file:="${service_pid_path}/${service}.pid"}" \
  "${service_lock_file:="${service_lock_path}/${service}.lock"}"

service_paths=(
  "${service_bin_path}"
  "${service_config_path}"
  "${service_pid_path}"
  "${service_data_path}"
  "${service_lock_path}"
  "${service_log_path}"
)

service_actions=( start stop restart )

export service_paths service_actions

if file_is_nonempty "${service_pid_file}"
then
  read -r service_pid < "${service_pid_file}"
else
  service_pid=0
fi

