#!/usr/local/bin bash

modules filesystem system

variable_is_nonempty init_scripts_path || init_scripts_path="$(init_scripts_path)"
variable_is_nonempty confd_path        || confd_path="$(confd_path)"

