#!/bin/sh

ext_steps_initialize()
{
  steps_started=()
}

start_step()
{
  steps_started+=( "$1" )
}

step()
{
  local name="$1"

  shift || __sm.log.fail "Cannot take step as no step name given;"\
    "step [name] <- missing name."

  start_step "$name"

  if __sm.command.exists before_step
  then
    before_step "$name" "$@"
  fi

  "$name" "$@"

  if __sm.command.exists after_step
  then
    after_step "$name" "$@"
  fi
}

steps()
{
  for step in $@
  do
    step "${step}"
  done
}

retreat()
{
  local step

  if [[ -z "${steps_started}" ]]
  then
    steps_started=( "$@" )
  fi

  while [[ -n "${steps_started}" ]]
  do
    array pop steps_started step
    if __sm.command.exists "fail_${step}"
    then
      "fail_${step}"
    fi

    if __sm.command.exists after_step
    then
      after_step "fail_${step}"
    fi
  done
}
