#!/usr/bin/env bash

if [[ ! -z "$HOME/.bashrc" ]] ; then source "$HOME/.bashrc" ; fi

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

master_pid="$(ps auxww | grep '[u]nicorn' | grep 'master' | awk '/'${project}'/{print $2}')"

cd $current_path
if [[ ! -z ".rvmrc" ]] ; then source ".rvmrc" ; fi

if [[ "$master_pid" -le 0 ]] ; then
  echo "There are no unicorns running for $project."
else
  ps auxww | grep '[u]nicorn' | grep master
  echo
  ps auxwww | grep '[u]nicorn' | grep $project | grep $environment | grep worker
fi

exit $?

