#!/usr/bin/env bash

if [[ "$trace_flag" -eq 1 ]] ; then set -x ; fi

master_pid="$(ps auxww | grep '[u]nicorn' | grep 'master' | awk '/'${project}'/{print $2}')"

builtin cd $current_path

if [[ "$master_pid" -le 0 ]] ; then
  echo "Unicorn herd is not running for $project yet."
else
  echo "Signaling herd master for $project $environment to re-execute the running binary."
  kill -USR2 $master_pid
  sleep 5
  $scripts_path/log "info" "Sending QUIT to original herd master for $project $environment."
  kill -QUIT $master_pid
fi

exit $?
