#!/usr/bin/env bash

set +o nounset
set +o noclobber

while (( $# > 0 ))
do
  token="$1"
  case "$token" in

    --help)
      extension_args=("core" "help" "$@")
      break
      ;;

    -v|--version)
      extension_args=("core" "version" "$@")
      break
      ;;

    --trace)
      true ${trace_flag:=0} $(( trace_flag++ ))
      PS4="# \${BASH_SOURCE##\${bdsm_path}\/extensions\/} \${FUNCNAME[0]:+\${FUNCNAME[0]}()} \${LINENO} $ "
      export PS4
      set -x
      ;;

    --debug)
      true ${debug_flag:=0} $(( debug_flag++ ))
      export debug_flag
      ;;

    --)
      shift #end of processing
      extension_args=("$@")
      break
      ;;

    -*)
      error "Unknown flag '${token}'"
      ;;
    *)
      if [[ -f $token ]]
      then
        bdsm_script=$1
      else
        extension_args=("$@")
        break
      fi
      ;;
  esac
  shift
done

if (( $# == 0 )) && [[ -z "$extension_args" ]]
then
  extension_args=()
fi
