#!/usr/bin/env bash

shopt -s extglob # Extended globs must always be on for BDSM.

# load bdsmrc files, cascaded. Settings in these files trump all.
for file in /etc/bdsmrc "$HOME/.bdsmrc"
do
  if [[ -s "${file}" ]]
  then
    . "${file}"
  fi
done

bdsm_path="/usr/local/bdsm"

if (( UID == 0 ))
then # FHS
  true \
    "${var_path:="/var"}" \
    "${etc_path:="/etc"}" \
    "${profile_path:="/etc/profile"}" \
    "${profile_d_path:="/etc/profile.d"}"
else
  true \
    "${var_path:="${bdsm_path}/var"}" \
    "${etc_path:="$HOME/.etc"}" \
    "${profile_path:="$HOME/.profile"}" \
    "${profile_d_path:="$HOME/.profile.d"}"
fi

true \
  "${modules_path:="${bdsm_path}/extensions/builtin/core/modules"}" \
  "${parent_extensions_path:="${bdsm_path}/extensions"}" \
  "${templates_path:="${bdsm_path}/templates"}" \
  "${src_path:="${bdsm_path}/src"}" \
  "${tmp_path:="${bdsm_path}/tmp"}" \
  "${bin_path:="${bdsm_path}/bin"}" \
  "${repos_path:="${bdsm_path}/repos"}" \
  "${archives_path:="${bdsm_path}/archives"}" \
  "${extensions_src_path:="${src_path}/extensions"}" \
  "${remote:="origin"}" \
  "${branch:="master"}" \
  "${language:="shell"}" \
  "${user:=$USER}" \
  "${keep_releases:=4}" \
  "${hooks_flag:=1}" \
  "${PAGER:="less"}" \
  "${config_path:="${parent_extensions_path}/builtin/core/config"}" \
  "${packages_path:="${bdsm_path}/pkg"}" \
  "${active_path:="${packages_path}/active"}" \
  "${extension_args:=""}"

if [[ -d "${active_path}/bin" ]]
then
  export PATH="${active_path}/bin:${active_path}/sbin:${PATH}"
fi

export bdsm_path modules_path initial_pwd

# Load module() function and then load core modules.
source "${modules_path}/shell/modules/dsl"
source "${modules_path}/shell/modules/initialize"

modules variables array trace logging time environment filesystem system users \
  extensions

module_load core/dsl

if os_is_solaris
then # custom compilations + g*
  export PATH="/usr/local/bin:/opt/local/bin:/usr/sfw/bin:/usr/sbin:/usr/bin"
fi

# Ensure variables desired to be exported to extensions actually are.
bdsm_exports

disable_backtrace

if [[ -n "${extension_args[*]}" ]]
then
  if match "${extension_args[0]}" *,*
  then
    array_shift extension_args extensions
    extensions=("${extensions//,/ }")
    exec "${bdsm_path}/bin/bdsm-ll" \{\} ${extension_args[*]} ::: ${extensions[@]}
  else
    extension_action
  fi
fi

