#!/bin/sh

# ## archive\_get()
#
#
#
# Code Walkthrough
archive_get()
{
  typeset _uri _final_target _package_md5 _archive
  _uri="${1:-}"
  _final_target="${2:-}"
  _package_md5="${3:-${md5:-#}}"
  _archive="${archives_path}/${_uri##*/}"
  (( $# )) && shift || __sm.log.fail "uri must be specified as the first parameter."
  (( $# )) && shift || __sm.log.fail "target path must be specified as the second parameter."

  case "${_uri}" in
    # fix github archive names
    (*github.com/*/tarball/*)
      _archive="${_uri#*github.com/}"
      _archive="${_archive%/tarball*}"
      _archive="${archives_path}/${_archive//\//_}_${_uri##*/}.tar.gz"
      __sm.log.debug vcs "github tarball archive name ${_archive}."
      ;;
    (*github.com/*/zipball/*)
      _archive="${_uri#*github.com/}"
      _archive="${_archive%/zipball*}"
      _archive="${archives_path}/${_archive//\//_}_${_uri##*/}.zip"
      __sm.log.debug vcs "github zipball archive name ${_archive}."
      ;;
  esac

  [[ -d "${archives_path}" ]] || mkdir -p "${archives_path}"

  # TOD: shasum default instead
  if [[ -f "${_archive}" && "$(files md5 "${_archive}")" != "${_package_md5}" ]]
  then
    __sm.log.debug vcs "${_uri##*/} does not match MD5 checksum ${_package_md5}; removing and downloading."
    rm -f "${_archive}"
  fi

  if [[ ! -f "${_archive}" ]]
  then
    if [[ -f "${_uri}" ]]
    then
      if ! files copy force from "${_uri}" to "${_archive}"
      then
        fetch_error copy_failed from=${_uri} to=${_archive}
      fi
    else
      if curl -s -L "${_uri}" -o "${_archive}"
      then
        : #Download worked
      else
        case $? in
          (60)
            __sm.log.error "Peer certificate cannot be authenticated with known CA certificates.\n\n\
Please read 'sm man curl' for instructions how to solve this problem.\n"
            ;;
          (*)
            fetch_error download_failed from=${_uri} to=${_archive}
            ;;
        esac
      fi
    fi
  fi

  [[ -z "${__vcs_failed}" ]] || return 0

  rm -rf "${_final_target}" || true
  mkdir -p "${_final_target}"
  builtin cd "${_final_target}"

  case "${_uri}" in
    (*.tar) # tar
      tar xf "${_archive}"  2>&1 | __sm.log.debug vcs -
      (( ${pipestatus[1]} == 0 )) || fetch_error extracting_archive_failed
      ;;
    (*.tar.gz|*.tgz) # gzip
      tar zxf "${_archive}" 2>&1 | __sm.log.debug vcs -
      (( ${pipestatus[1]} == 0 )) || fetch_error extracting_archive_failed
      ;;
    (*github.com/*/tarball/*)
      tar zxf "${_archive}" 2>&1 | __sm.log.debug vcs -
      (( ${pipestatus[1]} == 0 )) || fetch_error extracting_archive_failed
      typeset name_pattern="${_uri#https://github.com/}"
      name_pattern="${name_pattern%tarball/*}"
      name_pattern="${name_pattern//\//-}"
      mv ${name_pattern}*/* .
      rm -rf ${name_pattern}*
      ;;
    (*.tar.bz2|*.tbz2) # bzip
      tar jxf "${_archive}" 2>&1 | __sm.log.debug vcs -
      (( ${pipestatus[1]} == 0 )) || fetch_error extracting_archive_failed
      ;;
    (*.tar.xz) # LZMA
      # TODO: ??? if __sm.command.exists 'xz' - use that, otherwise use tar J
      tar Jxf "${_archive}" 2>&1 | __sm.log.debug vcs -
      (( ${pipestatus[1]} == 0 )) || fetch_error extracting_archive_failed
      ;;
    (*.zip)
      unzip -q "${_archive}" 2>&1 | __sm.log.debug vcs -
      (( ${pipestatus[1]} == 0 )) || fetch_error extracting_archive_failed
      ;;
    (*github.com/*/zipball/*)
      unzip -q "${_archive}" 2>&1 | __sm.log.debug vcs -
      (( ${pipestatus[1]} == 0 )) || fetch_error extracting_archive_failed
      typeset name_pattern="${_uri#https://github.com/}"
      name_pattern="${name_pattern%zipball/*}"
      name_pattern="${name_pattern//\//-}"
      mv ${name_pattern}*/* .
      rm -rf ${name_pattern}*
      ;;
    (*)
      #TODO: add detection based on $( file ${_archive} ) type
      fetch_error unknown_archive_format
      ;;
  esac

  [[ -z "${__vcs_failed}" ]] || return 0

  ls -d * >/dev/null 2>&1 || fetch_error empty_archive

  files write string "${_uri}" to "${_final_target}/.uri"
}

