#!/bin/sh

__sm.extension.path()
{
  local _path extension="${1:-}"
  shift || fail "Cannot process extension path;"\
    " No extension name was given."

  for _path in ${extensions_search_paths[@]}
  do
    if [[ -d "${_path}/${extension}/bin" || -d "${_path}/${extension}/shell" ]]
    then
      extension_path="${_path}/${extension}"
      return 0
    fi
  done
  return 1
}

__sm.extension.is.valid()
{
  local _path="${1:-}"
  shift || fail "No extension path was given to check validity."
  [[ -n "${_path}" ]] || fail "Path to the extension was not given."
  [[ -d "${_path}/bin" || -d "${_path}/shell" ]]
}

__sm.extension.find()
{
  extensions_path="${1:-}" extension="${2:-}"
  shift || fail "Cannot detect extension existence;"\
    " No extension path was given."
  shift || fail "Cannot detect extension existence;"\
    " No extension name was given."
  __sm.extension.is.valid $extensions_path/$extension
}

__sm.extension.sets.iterator()
{
  local _path="$1" _command="$2"
  shift 2
  "${_command}" "${_path}" "$@"
  return 1
}

__sm.extension.iterator()
{
  local _path="$1" _command="$2" _ext_path _ext_paths
  shift 2
  shopt -s nullglob
  _ext_paths=( "${_path}"/* )
  shopt -u nullglob
  for  _ext_path in ${_ext_paths[@]}
  do
    "${_command}" "${_ext_path}" "$@"
  done
  return 1
}
