#!/usr/bin/env bash

actions_for_extension() {
  if [[ ! -z "$1" ]] ; then
    echo "bdsm $1: {$(ls -p $extensions_path/$1/ | awk '/[^\/]$/' | tr "\n" ' ' | sed 's/\s\+/, /g' | sed 's/,\s*$//')}"
  fi
}
