#!/usr/bin/env bash

shopt -s extglob # Extended globs
set -o errtrace
export PS4="+ \${BASH_SOURCE} : \${FUNCNAME[0]:+\${FUNCNAME[0]}()}\n  \${LINENO} > "

[[ -s "/etc/bdsmrc" ]]  && . "/etc/bdsmrc"
[[ -s "$HOME/.bdsmrc" ]] && . "$HOME/.bdsmrc"

true "${prefix:=/usr/local}" "${bindir:=/usr/local/bin}"

if [[ "$prefix" = "$HOME" ]] ; then
  true "${bdsm_path:="${prefix}bdsm"}"
else
  true "${bdsm_path:="${prefix}/bdsm"}"
fi

true \
  "${scripts_path:="${bdsm_path}/scripts"}" \
  "${extensions_path:="${bdsm_path}/extensions"}" \
  "${templates_path:="${bdsm_path}/templates"}" \
  "${config_path:="${bdsm_path}/config"}" \
  "${src_path:="${bdsm_path}/src"}" \
  "${extensions_src_path:="${src_path}/extensions"}" \
  "${tmp_path:="${bdsm_path}/tmp"}" \
  "${bin_path:="${bdsm_path}/bin"}" \
  "${archives_path:="${bdsm_path}/archives"}" \
  "${remote:="origin"}" \
  "${branch:="master"}" \
  "${language:="bash"}" \
  "${user:=$USER}" \
  "${keep_releases:=4}" \
  "${hooks_flag:=1}" \
  "${PAGER:=cat -v}"

true \
  "${releases_url:=$(hash_file "$config_path/bdsm" "releases_url")}" \
  "${extensions_url:=$(hash_file "$config_path/bdsm" "extensions_url")}"\

result=0

# In case bdsm is being called from within a hook for example, we unset these:
unset extension action

if [[ ${trace_flag:-0} -eq 1 ]] ; then
  export trace_flag
  set -o xtrace
elif [[ ${debug_flag:-0} -eq 1 ]] ; then
  export debug_flag
  set -o verbose
fi

export vcs project database_name old_releases bdsm_path current_path previous_path project_path shared_path archives_path bin_path bindir branch config_path extensions_path framework hooks_flag keep_releases prefix remote result scripts_path src_path tmp_path templates_path timestamp user

timestamp="$(date +%m.%d.%Y-%H:%M:%S)"

trap "[[ -e ${tmp_path}/$$ ]] && rm -rf '${tmp_path}/$$' >/dev/null 2>&1" 0 1 2 3 15

