#!/usr/bin/env bash

if [[ "$trace_flag" -eq 2 ]] ; then set -x ; export trace_flag ; fi

if [[ ! -z "$2" ]] ; then level=$1 ; shift ; else level="info" ; fi

message=$1

case "$level" in
  debug) shift ; echo -e "<d> $message "     ;;
  info)  shift ; echo -e "<i> $message "     ;;
  warn)  shift ; echo -e "<w> $message "     ;;
  error) shift ; echo -e "<e> $message " >&2 ;;
  fail)  shift ; echo -e "<f> $message " >&2 ;;
  *) echo -e "$message"
esac

exit 0
