#!/usr/bin/env bash

if [[ "$trace_flag" -eq 2 ]] ; then set -x ; export trace_flag ; fi

if [[ ! -z "$2" ]] ; then level=$1 ; shift ; else level="info" ; fi

message=$1

if [[ -z "$interactive_flag" ]] ; then
  if [[ -z "$TERM" ]] ; then
    case "$level" in
      debug) shift ; echo -e "\n<d> $message </d>\n"     ;;
      info)  shift ; echo -e "\n<i> $message </i>\n"     ;;
      warn)  shift ; echo -e "\n<w> $message </w>\n"     ;;
      error) shift ; echo -e "\n<e> $message </e>\n" >&2 ;;
      fail)  shift ; echo -e "\n<f> $message </f>\n" >&2 ;;
      *) echo -e "$message"
    esac
  else
    case "$level" in
      debug) shift ; echo -e "\n$(tput setaf 5)<d>$(tput sgr0) $message $(tput setaf 5)</d> $(tput sgr0)\n"     ;;
      info)  shift ; echo -e "\n$(tput setaf 2)<i>$(tput sgr0) $message $(tput setaf 2)</i> $(tput sgr0)\n"     ;;
      warn)  shift ; echo -e "\n$(tput setaf 3)<w>$(tput sgr0) $message $(tput setaf 3)</w> $(tput sgr0)\n"     ;;
      error) shift ; echo -e "\n$(tput setaf 1)<e>$(tput sgr0) $message $(tput setaf 1)</e> $(tput sgr0)\n" >&2 ;;
      fail)  shift ; echo -e "\n$(tput setaf 1)<f>$(tput sgr0) $message $(tput setaf 1)</f> $(tput sgr0)\n" >&2 ;;
      *) echo -e "$message"
    esac
  fi
else
  case "$level" in
    debug) shift ; echo -e "\n$(tput setaf 5)$message$(tput sgr0)\n"     ;;
    info)  shift ; echo -e "\n$(tput setaf 2)$message$(tput sgr0)\n"     ;;
    warn)  shift ; echo -e "\n$(tput setaf 3)$message$(tput sgr0)\n"     ;;
    error) shift ; echo -e "\n$(tput setaf 1)$message$(tput sgr0)\n" >&2 ;;
    fail)  shift ; echo -e "\n$(tput setaf 1)$message$(tput sgr0)\n" >&2 ;;
    *) echo -e "$message"
  esac
fi

exit 0
