#!/usr/bin/env bash

if [[ "$trace_flag" -eq 2 ]] ; then set -x ; export trace_flag ; fi

if [[ ! -z "$2" ]] ; then level=$1 ; shift ; else level="info" ; fi

message=$1

case "$level" in
  debug) shift ; echo -e "\n<d> $message\n"     ;;
  info)  shift ; echo -e "\n<i> $message\n"     ;;
  warn)  shift ; echo -e "\n<w> $message\n"     ;;
  error) shift ; echo -e "\n<e> $message\n" >&2 ;;
  fail)  shift ; echo -e "\n<f> $message\n" >&2 ;;
  *) echo -e "$message"
esac

exit 0
