#!/bin/sh

#
# SM Framework Core Module ~ Operating System (os)
#
# API Version: 1.0.0
#
# files *
#
# TODO: Finish this API documentation below
#
# os is <linux|darwin|bsd|solaris|aix>
# os cpu count
# os open {uri}
# os type
# os version
# os version major
# os version minor
# os version patch
# os arch
# os arch capable
#
os()
{
  trace_filter os || set -o xtrace

  typeset _command _subcommand _os _token
  typeset -a _files

  while (( $# > 0 ))
  do
    _token="$1" && shift
    case "${_token}" in
      (is)
        _command="$_token"
        _os="${1}"
        (( $# )) && shift || __sm.log.fail "lowercase operating system name must follow keyword 'os';"\
          "os is <linux|darwin|bsd|solaris|aix>"
        ;;
      (cpu)
        _command=cpu
        _subcommand="$1"
        (( $# )) && shift || __sm.log.fail "A command must follow keyword 'cpu'; one of {count}"
        case "${_subcommand}" in
          (count)
            true # all good.
            ;;
          (*)
            __sm.log.fail "A valid command must follow keyword 'cpu'; one of {count}"
            ;;
        esac
        ;;
      (*)
        if [[ -z "${_command}" ]]
        then
          _command="$_token"
        else
          _files+=("$_token")
        fi
        ;;
    esac
  done

  case "${_command}" in
    (is)
      case "${_os}" in
        (linux|bsd|darwin|solaris|aix)
          if [[ "$OSTYPE" == *${_os}* ]]
          then
            return 0
          else
            return 1
          fi
          ;;
        (*)
          __sm.log.fail "Unhandled os '${_os}'"
          ;;
      esac
      ;;
    (open)
      __sm.os.open "${_files[@]}"
      ;;
    (type)
      __sm.os.type
      ;;
    (version)
      case "${_subcommand}" in
        (major)
          __sm.os.version.major
          ;;
        (minor)
          __sm.os.version.minor
          ;;
        (patch)
          __sm.os.version.patch
          ;;
        (*)
          __sm.os.version
          ;;
      esac
      ;;
    (arch)
      case "${_subcommand}" in
        (capable)
          __sm.os.arch.capable
          ;;
        (*)
          __sm.os.arch
          ;;
      esac
      ;;
    (cpu)
      case "${_subcommand}" in
        (count)
          __sm.os.cpu.count
          ;;
        (*)
      __sm.log.fail "Unknown command for os cpu: '${_subcommand}'; valid commands include {count} "
          ;;
      esac
      ;;
    (*)
      __sm.log.fail "Unknown command for os: '${_command}' "\
        "A os command must be specified as the first parameter: "\
        "{is,}"
      ;;
  esac
}

# TODO: Move this function into internal/os
init_scripts_path()
{
  if (( UID == 0 ))
  then
    case "$OSTYPE" in
      (*darwin*)
        printf "/etc/init.d"
        ;;
      (*linux*|*)
        if [[ -d "/etc/init.d" ]]
        then
          printf "/etc/init.d"
        elif [[ -d "/etc/rc.d" ]]
        then
          printf "/etc/rc.d"
        else
          __sm.log.fail "Unknown init scripts directory (/etc/init.d or /etc/rc.d not found)."
        fi
        ;;
    esac
  else
    printf "$HOME/.init.d"
  fi
}

# TODO: Move this function into internal/os
__sm.os.confd.path()
{
  if (( UID == 0 ))
  then
    echo "/etc/conf.d"
  else
    echo "$HOME/.conf.d"
  fi
}

