#!/usr/bin/env bash

true \
  "${extensions_url:=$(hash_file "$config_path/defaults" "extensions_url")}" \
  "${extensions_repository_url:=$(hash_file "$config_path/defaults" "extensions_repository_url")}" \
  ${remote:="origin"} \
  ${branch:="master"}

modules environment vcs

extensions_src_path="${src_path}/extensions"

