#!/usr/bin/env bash

#
# use default repository wayneeseguin/bdsm-extensions.
# user$ bdsm extend default <uri> <local ext name>
#

extension_uri="${extension_args[0]}"
name="${extension_args[1]}"
extension_identifier="$(scm_identifier "${extension_uri}")"
extension_src_path="${extensions_src_path}/${extension_identifier}"

if variable_is_empty name
then
  fail "\"bdsm extend <name>\" is depracated, all bdsm-extensions are now available by default.\n\
  Use \"bdsm internal update\" to update internal bdsm extensdions."
fi

scm_get "${extension_uri}" "${extension_src_path}"
extension_install "${name}" "${extension_identifier}"
