#!/bin/sh

detect_man()
{
  local _extensions_path=$1 _extension=$2
  shift

  local _man_path _man_name="$*" #include extension in name
  shift

  _man_name="${_man_name:-cli}"
  _man_name="${_man_name// /_}"

  if [[ -n "${man_number}" ]]
  then
    _man_path="${_extensions_path}/${_extension}/man/man${man_number}/${_man_name}.${man_number}"
    if [[ -f "${_man_path}" ]]
    then
      man_file="${_man_path}"
      return 0
    elif [[ -f "${_man_path}.gz" ]]
    then
      man_file="${_man_path}.gz"
      return 0
    fi
    return 1
  fi

  for _man_path in ${_extensions_path}/${_extension}/man/man*/${_man_name}*
  do
    _temp="${_man_path%/*}" #cut out file name - we know it already
    case "${_temp##*/}" in
      man\*)
        continue
        ;;
      *)
        man_file="${_man_path}"
        return 0
        ;;
    esac
  done
  return 1
}

man_display()
{
  local man_path man_params man_number

  if echo $1 | grep -E '^[0-9]+$' >/dev/null
  then
    man_number=$1
    shift
  fi

  if in_search_paths detect_man "$@" ||
    in_cli_path detect_man "$@"
  then
    if man $man_file
    then
      :
    else
      local status=$?
      case $status in
        16)
          #Not found page - ignore
          ;;
        *)
          fail "Man returned unknown status $status"
      esac
    fi
  else
    local _man_name="$*"
    _man_name="${_man_name:-cli}"
    _man_name="${_man_name// /_}"
    log "Could not find man page for ${_man_name}${man_number:+.${man_number}}"
  fi
}

man_list()
{
  NIY
}
