#!/bin/sh

variable() { variables "$@"; }

variables()
{
  trace_filter variables

  local _command _variables=() _type
  local __variables_commands=(
    "is empty=are empty"
    "is nonempty=are nonempty"
    "must be empty"
    "must be nonempty"
  )

  if __sm.command.detect "$*" "${__variables_commands[@]}"
  then
    _command="${__sm_command_dotted}"
    shift "${__sm_command_words}"
  else
    fail "No command given.\nUsage:  \nvariables <command> ..."
  fi

  while (( $# ))
  do
    case "$1" in
      (type)
        case "$2" in
          (log|error|fail)
            _type=$2
            shift 2
            ;;
          ("")
            fail "Variable output type was not given after 'type'. " \
              "Valid types are: log, error, fail"
            ;;
          (*)
            fail "Variable output type '$2' in not valid. " \
              "Valid types are: log, error, fail"
            ;;
        esac
        ;;
      (*)
        _variables+=( "$1" )
        shift
        ;;
    esac
  done

  # TODO: Think through variables more...
  case "${_command}" in
    (are.empty|are.nonempty)
      [[ -n "${_variables[*]}" ]] || error "No variable names given for validation"
      __sm.variables.${_command} "${_variables[@]}"
      ;;
    (must.be.empty|must.be.nonempty)
      [[ -n "${_variables[*]}" ]] || error "No variable names given for validation"
      [[ -n "${_type}" ]] || error "No message type given for validation"
      __sm.variables.${_command} "${_type}" "${_variables[@]}"
      ;;
    (*)
      fail "Unknown variables command '${_command}'"
      ;;
  esac
}

