#!/bin/sh

variables()
{
  trace_filter variables

  local _token _command _variables=()

  while (( $# ))
  do
    _token="$1" && shift
    case "${_token}" in
      (are)
        _command=are
        _subcommand="$1"
        shift || fail "A command must follow keyword 'are' <epty|nonempty>"
        ;;
      (*)
        if [[ -z "${_command}" ]]
        then
          _command="${_token}"
        else
          _variables+=("${_token}")
        fi
    esac
  done

  # TODO: Think through variables more...
  case "${_command}" in
    (are)
      case "${_subcommand}" in
        (empty|nonempty)
          __sm.variables.are.${_subcommand} "${_variables}"
          ;;
        (*)
          fail "A valid command must follow keyword 'are' <empty|nonempty>"
          ;;
      esac
      ;;
    (*)
      fail "Unknown variables command '${_command}'"
      ;;
  esac
}

