#!/usr/bin/env bash

sm_version

case "${extension_args[0]}" in
  -v|-V) # Only echo version information.
    succeed "${sm_version:-"?.?.?"}"
    ;;
  *) # GNU-style extended version information.
    succeed "\nBDSM Framework ${sm_version:-"?.?.?"} https://bdsm.beginrescueend.com/ by Wayne E. Seguin (wayneeseguin@gmail.com)\n"
    ;;
esac
