#!/usr/bin/env bash

#
# ### extension_action()
#
# Load the environment for a given extension action and then call it.
# This is the main function for BDSM.
#
# ##### Input Parameters
#
# One or more extension names.
#
# ##### Stream Outputs
#
# None.
#
# ##### Environmental effects
#
# The current extension's initialize file will be resourced into the current
# environment.
#
# ##### Return Codes
#
# 0 for success
# 1 for failure
#
# ##### Failure Scenarios
#
# Fails if no extension was given.
# Fails if no action was given.
#
# ##### Usage Examples
#
#     $ cat $HOME/test
#     #!/usr/bin/env bash
#     source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#     modules extensions
#     extension_action ext list
#
#     $  $HOME/test
#     bash fossil git libevent nginx p7zip postgresql rails redis srv tig tmux zeromq zlib
#
#
extension_action()
{
  local result=0

  unset extension action

  export extension="${1:-}"

  if [[ -z "${extension}" ]]
  then
    fail "'extension' is not set! Something has gone terribly wrong."
  fi

  shift

  export action="${1:-}"

  if [[ -z "${action}" ]]
  then
    fail "'action' is not set! Something has gone terribly wrong."
  fi

  shift

  if (( ${#extension_args[@]} == 0 ))
  then
    extension_args="$@"
  fi
  export extension_args

  extension_path="$extensions_path/$extension"
  extension_config_path="$extensions_path/$extension/config"
  extension_templates_path="$extensions_path/$extension/templates"
  extension_modules_path="$extensions_path/$extension/modules"
  extension_bin_path="$extensions_path/$extension/bin"
  extension_log_path="$log_path/$extension"

  paths=$(env | awk -F= -v ORS=' ' '/_path/{print $1}')
  flags=$(env | awk -F= -v ORS=' ' '/_flag/{print $1}')

  enter "${extension_path}" ||
    fail "Could not enter the extension directory!\n    (${extension_path})"

  bdsm_exports

  action_file="${extension_path}/bin/${action}"

  file_exists "${action_file}" ||
    fail "Action binary/file ${action} missing for extension ${extension}\n    (${action_file})"

  action_file_type="$(file "$action_file")"

  case "${action_file_type}" in

    *sh[[:space:]]script*|*POSIX[[:space:]]shell*|*Bourne-Again*)
      action_type="bash"
      ;;

    *ASCII*)
      # Launch with helper dsl, if possible.
      extension="${action_file//.}"

      case "${extension}" in
        bash|sh)
          action_type="bash"
          #rb) action_type="ruby"   ;;
          ;;
        *)
          read -r shebang < "${action_file}"

          case "${shebang}" in
            *ruby|*rbx|*jruby|*macruby)
              binary="${shebang##*(#|!)}"
              binary="${binary##* }"
              action_type="ruby"
              ;;
            *)
              if [[ -x "${action_file}" ]] ; then
                action_type="binary"
              else
                action_type="not executable"
              fi
              ;;
          esac
          ;;
      esac
      result=$?
      ;;

    cannot[[:space:]]open)
      action_type="dne"
      ;;

    *)
      if file_is_executable "${action_file}" ; then
        action_type="binary"
      else
        action_type="noexec"
      fi
      ;;
  esac || result=$?

  # Now based on the determined action_type we launch the extension.
  case "${action_type}" in
    bash)
      (
      enable_backtrace
      if [[ "${action}" = "help" ]]
      then # Load the help module also.
        modules core help
      else
        modules core
      fi

      source_files \
        "${extension_modules_path}/bash/dsl" \
        "${extension_modules_path}/bash/initialize" \
        "${extension_modules_path}/bash/cli"

      . "${action_file}"
      ) || result=$?
      return $result
      ;;

    ruby)
      requires=()
      for script in dsl initialize
      do
        requires+=( "-r${modules_path}/ruby/core/${script}.rb" )
      done

      "${binary:-ruby}" -I"${modules_path}/ruby" -I"${extension_modules_path}/ruby" \
        ${requires[@]} "${action_file}"
      ;;
    # python|lua|javascript)
      #   ADD "${modules_path}/${action_type}/" to the lib path so the script can require "bdsm"
      #  "${action_file}"
      #  ;;
    dne|noexec)
      fail "Processing ${action} failed, file type is unknown, file does not exist or file is not executable."
      ;;
    binary|*)
      "${action_file}" "${extension_action}" "${extension_args[@]}"
      ;;
  esac || result=$?

  return $result
}

#
# ### extension_reload()
#
# Reloads (re-sources) the current extension's DSL and initialization files.
#
# ##### Input Parameters
#
# None.
#
# ##### Stream Outputs
#
# None.
#
# ##### Environmental effects
#
# The current extension's DSL and initialization files are re-sourced into the
# calling environment.
#
# ##### Return Codes
#
# 0 for success
#
# ##### Failure Scenarios
#
# No current failure scenarios.
#
# ##### Usage Examples
#
#     user$ extension_reload
#
extension_reload()
{
  local _path="${extension_modules_path}/bash"

  source_files "${_path}/dsl" "${_path}/initialize"
}

#
# ### extension_reinitialize()
#
# Reinitializes the current extension.
#
# ##### Input Parameters
#
# None.
#
# ##### Stream Outputs
#
# None.
#
# ##### Environmental effects
#
# The current extension's initialize file will be resourced into the current
# environment.
#
# ##### Return Codes
#
# 0 for success
#
# ##### Failure Scenarios
#
# No failure scenarios currently.
#
# ##### Usage Examples
#
#     user$ extension_reinitialize
#
extension_reinitialize()
{
  local _path="${extension_modules_path}/bash"

  source_files "${_path}/initialize"
}

#
# ### extension_version()
#
# Outputs the named extension's version
#
# ##### Input Parameters
#
# First parameter must be the name of an extension.
#
# ##### Stream Outputs
#
# The extension-version string for the named extension.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 for success
#
# ##### Failure Scenarios
#
# Fails if the extension name is not given.
#
# ##### Usage Examples
#
#     user$ extension_reinitialize
#
extension_version()
{
  local _extension="${1:-}"

  variable_is_nonempty ||
    fail "Can not retrieve extension version as no extension was given."

  shift
  true ${extension_path:="${extensions_path}/${_extension}"}

  if file_exists "${extension_path}/VERSION"
  then
    read -r extension_version < "${extension_path}/VERSION"
  else
    extension_version="head"
  fi

  log "${extension}-${extension_version}"
}

#
# ### extension_licence()
#
# Emits the extension's license file, if it exists.
#
# ##### Input Parameters
#
# First parameter may optionally be an extension name.
#
# ##### Stream Outputs
#
# If the extension has a LICENSE file then it wil be printed to STDOUT.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 for success.
#
# ##### Failure Scenarios
#
# No failure scenarios currently exist.
#
# ##### Usage Examples
#
#     $ cat $HOME/test
#     !/usr/bin/env bash
#     source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#     modules extensions
#     extension_license postgresql
#
#     $ $HOME/test
#     Copyright (c) 2009-2011 Wayne E. Seguin
#
#     Licensed under the Apache License, Version 2.0 (the \"License\");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an \"AS IS\" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
extension_license()
{
  local _extension="${1:-${extension}}"

  variable_is_nonempty _extension ||
    fail "Can not display extension license as an extension was not given."

  cat -v "${extensions_path}/${_extension}/LICENSE"
}

#
# ### extensions_installed()
#
# Lists the extensions installed on the currently running process's system.
#
# ##### Input Parameters
#
# None.
#
# ##### Stream Outputs
#
# The names of the currently installed non-core extensions are printed to the
# calling environment's STDOUT.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 for success.
#
# ##### Failure Scenarios
#
# No failure scenarios currently.
#
# ##### Usage Examples
#
#     $ cat $HOME/test
#     #!/usr/bin/env bash
#     source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#     modules extensions
#     extensions_installed
#
#     $ $HOME/test
#     bash fossil git libevent nginx p7zip postgresql rails redis tig tmux zeromq zlib
#
extensions_installed()
{
  extensions_in "${extensions_path}"
}

#
# ### extensions_available()
#
# Lists the extensions available to install on the currently running process's
# system.
#
# ##### Input Parameters
#
# None.
#
# ##### Stream Outputs
#
# The names of the available to install non-core extensions are printed to the
# calling environment's STDOUT.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 for success.
#
# ##### Failure Scenarios
#
# No failure scenarios currently.
#
# ##### Usage Examples
#
#      $ cat $HOME/test
#      #!/usr/bin/env bash
#      source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#      modules extensions
#      extensions_available

#      $  $HOME/test
#      ack androidsdk apache bash bcrypt cacti cmake ctags curl deploy erlang fossil freetype ghc ghostscript git god iconv imagemagick jpeg keepalived lcms libevent libpng libwmf libxml2 libxslt logrotate lua memcached mercurial mongodb monit mysql nginx node npm openpkg openssl p7zip passenger pcre perl postgresql r rails rainbows readline redis riak rsync rvm screen sphinx sqlite3 subversion system thin tiff tig tmux unicorn unrar zeromq zlib zsh
#
extensions_available()
{
  extensions_in "${extensions_src_path}"
}

#
# ### extensions_in_development()
#
# Lists the extensions available in the development repository, if set.
#
# ##### Input Parameters
#
# None.
#
# ##### Stream Outputs
#
# The names of the available to install non-core development repository
# extensions are printed to the calling environment's STDOUT, if defined.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 for success.
#
# ##### Failure Scenarios
#
# No failure scenarios currently.
#
# ##### Usage Examples
#
#      $ cat $HOME/test
#      #!/usr/bin/env bash
#      source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#      modules extensions
#      extensions_in_development

#      $  $HOME/test
#      ack androidsdk apache bash bcrypt cacti cmake ctags curl deploy erlang fossil freetype ghc ghostscript git god iconv imagemagick jpeg keepalived lcms libevent libpng libwmf libxml2 libxslt logrotate lua memcached mercurial mongodb monit mysql nginx node npm openpkg openssl p7zip passenger pcre perl postgresql r rails rainbows readline redis riak rsync rvm screen sphinx sqlite3 subversion system thin tiff tig tmux unicorn unrar zeromq zlib zsh
#
extensions_in_development()
{
  true "${extensions_development_path:="${extensions_src_path}"}"

  list_extensions_in "${extensions_development_path}"
}

#
# ### extensions_in()
#
# Lists the extensions in a given directory.
#
# ##### Input Parameters
#
# First parameter is a full path a BDSM extensions directory.
#   (example: /usr/local/bdsm/extensions)
#
# ##### Stream Outputs
#
# The names of the extensions in the given directory are printed to the
# calling environment's STDOUT.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 for success.
#
# ##### Failure Scenarios
#
# No failure scenarios currently.
#
# ##### Usage Examples
#
#     $ cat $HOME/test
#     #!/usr/bin/env bash
#     source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#     modules extensions
#     extensions_in /usr/local/bdsm/extensions
#
#     $  $HOME/test
#     bash fossil git libevent nginx p7zip postgresql rails redis tig tmux zeromq zlib
#
#
extensions_in()
{
  local _path="${1:-}"

  directory_exists "${_path}" ||
    fail "Cannot list extensions in '${_path}' as the directory does not exist."

  _files=($(find "${_path}" -mindepth 2 -maxdepth 2 -name 'VERSION' -type f))

  extensions=()

  for _file in "${_files[@]}"
  do
    extension_source_path="${_file/%\/VERSION}"
    extension_name="${extension_source_path//*\/}"

    case ${extension_name} in
      (core|ext|mod|pkg|srv|svc|[[=.=]]*)
        true # Ignore core extensions, they are updated with BDSM itself.
        ;;

      (*)
        extensions[${#extensions[@]}]="${extension_name//*\//}"
        ;;
    esac
  done

  extensions="${extensions[@]}"

  printf "${extensions}"
}

#
# ### extension_actions()
#
# Lists actions exposed by the named extension.
#
# ##### Input Parameters
#
# First parameter is the name of the extension to list actions for.
#
# ##### Stream Outputs
#
# The names of the extensions in the given directory are printed to the
# calling environment's STDOUT.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 for success.
#
# ##### Failure Scenarios
#
# Fails if no extension name is given.
#
# ##### Usage Examples
#
#      $ cat $HOME/test
#      #!/usr/bin/env bash
#      source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#      modules extensions
#      extension_actions "postgresql"
#
#      $ $HOME/test
#      backup configure help initialize install restart start status stop uninstall upgrade
#
#
#
extension_actions()
{
  local _extension="${1:-}"

  [[ -n "${_extension}" ]] ||
    fail "Cannot list actions for extension as no extension was given."

  local _path="$extensions_path/${_extension}/bin"

  directory_exists "${_path}" || return 0

  local _files=($(find "${_path}" -mindepth 1 -maxdepth 1 -type f))
  local _file _actions=()

  for _file in "${_files[@]}"
  do
    [[ ! -x "${_file}" ]] || _actions+=("${_file//*\/}")
  done

  _actions="${_actions[@]}" # Convert from array to string.

  printf "${_actions}"
}

#
# ### extension_is_installed()
#
# Tests if a given extension is installed.
#
# ##### Input Parameters
#
# First parameter is an extension name.
#
# ##### Stream Outputs
#
# None.
#
# ##### Environmental effects
#
# None.
#
# ##### Return Codes
#
# 0 if the extension is installed.
# 1 if the extension is not installed.
#
# ##### Failure Scenarios
#
# Fails if no extension name is given.
#
# ##### Usage Examples
#
#     $ cat $HOME/test
#     #!/usr/bin/env bash
#     source "/usr/local/bdsm/modules/bash/core/initialize" # Load BDSM framework core.
#     modules extensions
#     extensions_installed
#     echo
#     for extension in postgresql asdf
#     do
#       if extension_is_installed "${extension}"
#       then
#         echo "${extension} is installed! "
#       else
#         echo "${extension} is NOT installed! "
#       fi
#     done
#
#     $  $HOME/test
#     bash fossil git libevent mysql nginx node npm p7zip postgresql rails redis tig tmux zeromq zlib
#     postgresql is installed!
#     asdf is NOT installed!
#
extension_is_installed()
{
  local _name="${1:-}"

  [[ -n "${_name}" ]] ||
    fail "Can not check for an installed extension as no extension name was given."

  local _extensions=" $(extensions_in "${extensions_path}") "

  case "${_extensions}" in
    (*[[:space:]]${_name}[[:space:]]*)
      return 0
      ;;
    (*)
      return 1
      ;;
  esac
}


#
# ### extensions_install()
#
# Installs the given extensions.
#
# ##### Input Parameters
#
# One or more extension names.
#
# ##### Stream Outputs
#
# None.
#
# ##### Environmental effects
#
# The named extensions will be installed to the filesystem in the BDSM
# extensions directory.
#
# ##### Return Codes
#
# 0 for success
#
# ##### Failure Scenarios
#
# Fails if no extensions are passed in to install.
#
# ##### Usage Examples
#
#     user$ extensions_install libevent tmux
#
extensions_install()
{
  local _extension
  local _extensions=("$@")

  if (( ${#_extensions[@]} == 0 ))
  then
    fail "Cannot install extensions as no extensions were given to install."
  fi

  for _extension in "${_extensions[@]}"
  do
    case "${_extension#\/}" in
      ext|srv|pkg|core|mod)
        continue # Skip core extensions.
        ;;
    esac

    if [[ -z "${_extension}" ]]
    then # Skip any empty extensions / 'artifact'.
      continue
    else
      extension_install "${_extension}"
    fi
  done
}

#
# ### extension_install()
#
# Installs the given extension.
#
# ##### Input Parameters
#
# First parameter is the name of the extension to install
#
# ##### Stream Outputs
#
# None.
#
# ##### Environmental effects
#
# The named extension will be installed to the filesystem in the BDSM
# extension directory.
#
# ##### Return Codes
#
# 0 for success
#
# ##### Failure Scenarios
#
# Fails if no extension are passed in to install.
#
# ##### Usage Examples
#
#     user$ extension_install redis
#
extension_install()
{
  local _extension="${1:-}"

  if [[ -z "${_extension}" ]]
  then
    fail "Cannot install an extension as no extension name was given."
  fi

  true "${extension_uri:="${extensions_repository_url:-}"}"

  #################################
  extension_fetch "${extension_uri}"
  #################################


  # TODO: Install extension dependencies?
  if extension_is_valid "${extension_src_path}"
  then
    copy_directories_to "${bdsm_path}/extensions" "${extension_src_path}"
    # TODO: Now record the source of the extension.
    log "${extension_uri:-"${extensions_src_path}"}" > "${bdsm_path}/extensions/${_extension}/.uri"
  else
    error "${extension_src_path} is not a proper extension.
   The named extension is missing VERSION and/or bin/help files.
   Halting installation."
  fi
}

extension_fetch()
{
  local _url="${1:-$extension_uri}"
  local _identifier="${_url//\//_}" # Convert '/' to an invalid url component '_'
  local repo_path="${repos_path}/${_identifier}"

  if [[ -z "${_url}" ]]
  then
    fail "Cannot fetch an extension from a url as no url was given"
  fi

   # TODO: scm fetch vs tarball fetch
  scm_fetch "${_url}"

  scm_update "${_url}"

  extension_src_path="${repo_path}"
}

extension_is_valid()
{
  local _path="${1:-}"

  if [[ -z "${_path}" ]]
  then
    fail "Cannot determine if an extension is valid as the path to the extension was not given."
  fi

  # TODO: Add all extension requirement checks here.
  if [[ -s "${_path}/VERSION" && -x "${_path}/bin/help" ]]
  then
    return 0
  else
    return 1
  fi
}

extension_package()
{
  local _name="${1:-}"

  if [[ -z "${_name}" ]]
  then
    fail "Cannot package an extension as no extension name was given."
  fi

  local _path="${extensions_development_path:-"$extensions_src_path"}"

  enter "${_path}"

  if extension_is_valid "${_path}/${_name}"
  then
    local _version="$(cat "${_name}/VERSION")"
    log "Packaging extension ${_name}"
    log "${_name}-${_version}:"

    for archiver in "gzip" "bzip2 -z" "xz -z"
    do
      if command_exists ${archiver// *}
      then
        if tar cf "${_name}-${_version}.tar" "${_name}/"
        then
          ${archiver} -f -9 "${_name}-${_version}.tar"
        else
          error "There was an error ($?) while trying to create a tar of the '${_name}' directory while packaging."
        fi
      fi

      ensure_paths_exist "${_path}/pkg"
      for file in "${_name}-${_version}".tar.*
      do
        log "  - ${file}"
        file_md5 "${file}" > "${file}.md5"
        log "  - ${file}.md5"
        move_files --force "${file}" "${file}.md5" to "${_path}/pkg"
      done
    done

    log "Packaging complete (packages are located in '${_path}/pkg' )"
  else
    error "Cannot package extension '${_name}' as the extension is not valid."
  fi
}

