#!/usr/bin/env bash

installed_extensions()
{
  version_files=($(
    find "${extensions_path}"/* -mindepth 1 -maxdepth 1 -name 'VERSION' -type f
  ))

  for version_file in ${version_files[@]} ; do
    extension_source_path="${version_file/%\/VERSION}"
    extension_name="${extension_source_path//*\/}"

    case ${extension_name} in
      bdsm|[[=.=]]*)
        true # Ignore for now.
        ;;
      *)
        log "${extension_name//*\//}"
        ;;
    esac
  done
}

available_extensions()
{
  version_files=($(
  find "${extensions_src_path}"/* -mindepth 1 -maxdepth 1 -name 'VERSION' -type f
  ))

  for version_file in ${version_files[@]} ; do
    extension_source_path="${version_file/%\/VERSION}"
    extension_name="${extension_source_path//*\/}"

    [[ -s "$version_file" ]] || continue

    case ${extension_name} in
      bdsm|extension|[[=.=]]*)
        continue
        ;;
      *)
        printf "${extension_name//*\//}\n"
        ;;
    esac
  done
}


