#!/usr/bin/env bash

installed_extensions()
{
  extensions_in "${extensions_path}"

}

available_extensions()
{
  extensions_in "${extensions_src_path}"
}

development_extensions()
{
  true "${extensions_development_path:="${extensions_src_path}"}"

  list_extensions_in "${extensions_development_path}"
}

extensions_in()
{
  (
  path="${1:-}"

  version_files=($(
    find "${path}" -mindepth 2 -maxdepth 2 -name 'VERSION' -type f
  ))

  extensions=()

  for version_file in "${version_files[@]}" ; do
    extension_source_path="${version_file/%\/VERSION}"
    extension_name="${extension_source_path//*\/}"

    case ${extension_name} in
      bdsm|extension|[[=.=]]*)
        true # Ignore for now.
        ;;
      *)
        extensions[${#extensions[@]}]="${extension_name//*\//}"
        ;;
    esac
  done

  extensions="${extensions[@]}"

  printf "${extensions}"
  )
}

