#!/usr/bin/env bash

: ${debug_flags:=""} ${debug_flag:=0} ${trace_flags:="-backtrace"} ${trace_flag:=0}

trace_filter_stack=()

set_ps4

# Do not exit on error
set +o errexit
# Persist error handler
set -o errtrace
# Call backtrace on error
trap "backtrace \"A command has returned an not handled error code (nonzero return value).\"" ERR
# Exit on USR2 (send by backtrace to $APP_PID)
trap 'exit 1' USR2
# Store process pid for closing from backtrace
export APP_PID=$$

# Those two break error handling
unset command_not_found
unset command_not_found_handle
