#!/bin/sh

#
# SM Framework Core Module ~ String (string)
#

string()
{
  trace_filter string

  local _token _command _string _search _regex

  while (( $# ))
  do
    _token="$1" && shift
    case "${_token}" in
      (from)
        _search="$1"
        shift || fail "From source string must follow keyword 'from'"
        ;;
      (to)
        _string="$1"
        ;;
      (contains)
        _command=contains
        _search="$1"
        shift || fail "Search (glob) string must follow keyword 'contains'"
        ;;
      (*)
        if [[ -z "${_string}" ]]
        then
          _string="${_token}"
        elif [[ -z "${_search}" ]]
        then
          _search="${_token}"
        fi
        ;;
    esac
  done

  case "${_command}" in
    (contains)
      if [[ "${_string}" =~ "${_search}" ]] ; then return 0 ; else return 1 ; fi
      ;;
    (append)
      printf "${_string}"
      if ! [[ "${_string}" =~ "${_search}" ]] ; then printf " ${_search}" ; fi
      ;;
    (prepend)
      if ! [[ "${_string}" =~ "${_search}" ]] ; then printf " ${_search}" ; fi
      printf "${_string}"
      ;;
    (remove)
      _string=" ${_string} "               # wrap with spaces.
      _string="${_string// ${_search} / }" # remove second string.
      _string="${_string## }"              # remove spaces from beginning.
      _string="${_string%% }"              # remove spaces from end.
      printf "${_string}"
      ;;
    (truncate)
      printf ""
      ;;
    (*)
      fail "Unknown string command '${_command}'"
      ;;
  esac
}

