#!/bin/sh

#
# SM Framework Core Module ~ Versioned FileSystem (versionedfs)
#
# API Version: 1.0.0
#
# versionedfs \
#   path "{versionedfs root path}" \
#   strategy "{fhs,name}" \
#   method "{link,copy}" \
#   activate "{newest,first}"
#
# Example: (package module)
#
# versionedfs \
#   path /opt/sm/pkg \
#   strategy fhs \
#   method link \
#   activate first
#
# FileSystem structure:
#
# {versionedfs_path}/
#   .versionedfs/
#     strategy # contains one of {fhs,name}
#     method   # contains one of {link,copy}
#     activate # contains one of {newest,first}
#     retain   # contains one of {[[:digit:]],all}
#
#   versions/
#     {name}/{version}/ # For each {name}:{version} pair added.
#
# If strategy is 'fhs' then,
#   active/
#     {bin,sbin,lib,libexec,usr,var,tmp}
#
# If strategy is 'name' then,
#   active/
#     {name} # For each active name.
#
# In both cases if method is 'link' then each entry will be a symlink
# otherwise each entry will be copied files/directories.
#
versionedfs()
{
  local _token _path _paths _source _name _version _strategy _method _activate
  local _action="${1:-}"
  shift || fail "Usage: versionedfs path \"{versionedfs root path}\" "\
    "strategy \"{fhs,name}\" method \"{link,copy}\" activate \"{newest,first}\""

  while (( $# ))
  do
    _token="${1}" ; shift
    case "${_token}" in
      (path)
        _path="${1}"
        shift || fail "versionedfs path must follow keyword 'path'"
        ;;
      (source)
        _source="${1}"
        shift || fail "Source path must follow keyword 'source'"
        ;;
      (name)
        _name="${1}"
        shift || fail "Name must follow keyword 'name'"
        ;;
      (version)
        _version="${1}"
        shift || fail "Version string must follow keyword 'version'"
        ;;
      (strategy)
        _strategy="${1}"
        shift || fail "Strategy string must follow keyword 'strategy'"
        case "${_strategy}" in
          (fhs|name) true ;;
          (*) fail "Strategy must be one of {fhs,name}" ;;
        esac
        ;;
      (method)
        _method="${1}"
        shift || fail "method string must follow keyword 'method'"
        case "${_method}" in
          (link|copy) true ;;
          (*) fail "Method must be one of {link,copy}" ;;
        esac
        ;;
      (activate)
        _activate="${1}"
        shift || fail "activate string must follow keyword 'activate'"
        case "${_activate}" in
          (first|newest) true ;;
          (*) fail "Activate must be one of {first,newest}" ;;
        esac
        ;;
      (keep)
        _keep="${1}"
        shift || fail "keep number must follow keyword 'activate'"
        case "${_keep}" in
          (+([[:digit]]))
            (( _keep > 0)) || fail "Keep must be a positive integer." ;;
          (*) fail "Keep must be an integer." ;;
        esac
        ;;
      (*)
        fail "Unknown parameter '${_token}'"
    esac
  done

  [[ -n "${_path}" ]] || fail "A versionedfs root path must be given."

  [[ "${_action}" == create || -d "${_path}/.versionedfs" ]] ||
    fail "${_path} is not a versionedfs root path; "\
    "Use 'versionedfs create path {path}' to initialize."

  case "${_action}" in
    (create)
      __sm.versionedfs.create "${_path}"
      ;;
    (add)
      [[ -n "${_name}" && -n "${_source}" ]] ||
        fail "Name and Source must be given."
      [[ -n "${_version}" ]] || _version="$(date +"%Y%m%d%H%M%S")"
      __sm.versionedfs.add "${_path}" "${_name}" "${_version}" "${_source}"
      __sm.versionedfs.activate "${_path}" "${_name}" "${_version}"
      ;;
    (remove)
      [[ -n "${_name}" ]]    || fail "Name must be given."
      __sm.versionedfs.remove "${_path}" "${_name}" "${_version}"
      ;;
    (activate)
      [[ -n "${_name}" && -n "${_version}" ]] ||
        fail "Name and Version must be given."
      __sm.versionedfs.activate "${_path}" "${_name}" "${_version}"
      ;;
    (deactivate)
      [[ -n "${_name}" ]]    || fail "Name must be given."
      __sm.versionedfs.deactivate "${_path}" "${_name}" "${_version}"
      ;;
    (versions)
      __sm.versionedfs.list versions "${_path}" "${_name}" "${_version}"
      ;;
    (active)
      __sm.versionedfs.list active "${_path}" "${_name}" "${_version}"
      ;;
    (*)
      fail "Unknown versionedfs action '${_action}'"
      ;;
  esac
}

__sm.versionedfs.create()
{
  local _path="$1"
  mkdir -p "${_path}/"{.versionedfs,versions,active} ||
    fail "Could not create paths ${_path}/{.versionedfs,versions,active}"

  echo "${_strategy}" > "${_path}/.versionedfs/strategy"
  echo "${_method}"   > "${_path}/.versionedfs/method"
  echo "${_activate}" > "${_path}/.versionedfs/activate"

}

__sm.versionedfs.add()
{
  local _path="$1" _name="$2" _version="${3}" _source="$4"

  local _version_path="${_path}/versions/${_name}/${_version}"

  if [[ -d "${_version_path}" ]]
  then
    rm -rf "${_version_path}"
  fi

  mkdir -p "${_version_path}"

  if [[ "${_version_path}" != "${_source}" ]]
  then
    cp -Rf "${_source}"/* "${_version_path}"
  fi
}

__sm.versionedfs.remove()
{
  local _path="$1" _name="${2}" _version="${3}"
  local _version_path="${_path}/versions/${_name}/${_version}"

  __sm.versionedfs.deactivate "${_path}" "${_name}" "${_version}"

  if [[ -d "${_version_path}" ]]
  then
    rm -rf "${_version_path}/"
  fi
}

__sm.versionedfs.activate()
{
  local _path="$1" _name="${2}" _version="${3}" _target
  local _version_path="${_path}/versions/${_name}/${_version}"
  local _active_path="${_path}/active"

  if [[ -L "${_path}/versions/${_name}/active" ]]
  then # Deactivate if active version.
    if [[ "$(readlink "${_path}/versions/${_name}/active")" != "${_version_path}" ]]
    then
      __sm.versionedfs.deactivate "${_path}" "${_name}"
    else
      return 0 # Success if the given name/version is already active.
    fi
  fi

  local _activate _active_version_path _index=0 _count _active_path

  read -r _activate < "${_path}/.versionedfs/activate"

  if [[ -L "${_path}/versions/${_name}/active" ]]
  then
    _active_version_path="$(readlink "${_path}/versions/${_name}/active")"
    case "${_activate}" in
      (first)
        [[ -z "${_active_version_path}" ]] || return 0 # a version is already active
        ;;
      (newest)
        true # continue with activation
        ;;
    esac
  fi

  read -r _strategy < "${_path}/.versionedfs/strategy"
  read -r _method < "${_path}/.versionedfs/method"

  core_log_step "${_name} ${_version}"

  case "${_strategy}" in
    (fhs)
      case "${_method}" in
        (link)
          # TODO: Switch this to using shell globbing builtin?
          _files=($( find "${_version_path}" -type f ))
          _count="${#_files[@]}"
          for _file in "${_files[@]}"
          do
            (( _index++ )) || true
            printf "\r  [ ] ${_name} ${_version} ~ linking (${_index}/${_count})..."
            _target="${_active_path}/${_file##${_version_path}/}"
            [[ -d "${_target%/*}" ]] || mkdir -p "${_target%/*}"
            ln -sf "${_file}" "${_target}"
          done
          printf "\r  [o] %-40s" "${_name} ${_version}"
          ;;
        (copy)
          cp -Rf "${_version_path}"/* "${_active_path}"
          ;;
      esac
      ;;
    (name)
      if [[ -d "${_active_path}/${_name}" ]]
      then
        rm -rf "${_active_path}/${_name}"
      fi
      mkdir -p "${_active_path}/${_name}"
      cp -Rf "${_version_path}"/* "${_active_path}/${_name}"
      ;;
  esac

  core_log_step success

  ln -sf "${_version_path}" "${_path}/versions/${_name}/active"
  # TODO: Add to active 'db'
}

__sm.versionedfs.deactivate()
{
  local _path="$1" _name="${2}" _version="${3:-}"
  local _name_path="${_path}/versions/${_name}"
  local _active_path="${_path}/active"

  [[ -L "${_path}/versions/${_name}/active" ]] || return 0 # No active version

  local _index=0 _count
  local _version_path="$(readlink "${_path}/versions/${_name}/active")"

  if [[ -n "${_version}" && "${_version_path}" == "${_name_path}/${_version}" ]]
  then
    debug package "A different version than the one given is active; Skipping deactivation."
    return 0 #
  fi

  read -r _strategy < "${_path}/.versionedfs/strategy"

  case "${_strategy}" in
    (fhs)
      # TODO: Switch this to using shell globbing builtin?
      _files=($( find "${_version_path}" -type f ))
      _count="${#_files[@]}"
      echo
      for _file in "${_files[@]}"
      do
        (( _index++ ))
        printf "\r  Removing (${_index}/${_count})"
        rm -f "${_active_path}/${_file##${_version_path}}"
      done
      ;;
    (name)
      rm -rf "${_active_path}/${_name}/"
      ;;
  esac

  rm -f "${_path}/versions/${_name}/active"
  # Remove from active metadata
}

__sm.versionedfs.list()
{
  local _method=$1 _path="$2" _name="${3:-}" __path __name __version

  if [[ -n "${_name}" ]]
  then
    _name="${_name//,/ }"
  fi

  for __path in "${_path}"/versions/*/*
  do
    __version="${__path##*/}"
    case "${_method}" in
      (active)
        if [[ "${__version}" == "active" && -L "${__path}" ]]
        then
          __path="$( readlink "${__path}" )"
          __version="${__path##*/}"
        else
          __version=""
        fi
        ;;
      (versions)
        if [[ "${__version}" == "active" ]]
        then
          __version=""
        fi
        ;;
    esac

    if [[ -n "${__version}" ]]
    then
      __name="${__path%/*}"
      __name="${__name##*/}"
      if [[ -n "${_name}" ]] && ! string_contains "${_name}" "${__name}"
      then
        __name=""
      fi

      if [[ -n "${__name}" ]]
      then
        printf "${__name}:${__version}\n"
      fi
    fi
  done
}

