#!/usr/bin/env bash

action="${extension_args[0]}"

case "${action}" in

  head)
    install_remote "wayneeseguin"
    ;;

  version) # x.y.z
    install_release
    ;;

  latest)
    fetch_version
    install_release
    ;;

  *)
    install_remote "${action:-wayneeseguin}"
    ;;
esac

