#!/usr/bin/env bash

case "${extension_action}" in

  version) # x.y.z
    install_release
    ;;

  latest)
    fetch_version
    install_release
    ;;

  *)
    install_remote "${extension_action:-wayneeseguin}"
    ;;
esac

