#!/usr/bin/env bash

# NOTE: This action is *not* to be called directly but instead loaded from
#       the './install' installer script.
#       It is for this reason that this action file is not executable.
#
#       The CLI remaps 'bdsm install X' to 'bdsm ext install X'
#

directories=( bin modules completion )
files=( LICENSE VERSION README.md )
aux=( log tmp src )
extensions_old=( core pkg srv ext mod )
extensions_paths=( builtin internal external )
configs=( user ) # TODO move this to /etc/bdsm/ and/or $HOME/.bdsm/

log "Installing BDSM Framework into ${install_path}\n"

prepare_for_installation

create_auxillary_paths

install_core

install_builtin_extensions

install_internal_extensions

migrate_external_extensions

install_configuration_files

symlink_bdsm

setup_shell_completion

setup_profile_d

setup_bdsmrc

succeed "\nInstallation of BDSM is complete\n"
