#!/usr/bin/env bash

_path="${core_development_path:="$source_path/bdsm"}/${extension_args[0]}"

# TODO: Allow --src flag to modify root behavior.
user_is_not_root || _path="${bdsm_path}/extensions/${extension_args[0]}"

printf "${_path}"

exit 0 # For sanity.
