#!/usr/bin/env bash


extend_from()
{
  # "release" "${extension_args[@]}"
  local _source="${1:-}"
  if variable_is_nonempty _source
  then
    shift
    local _params=($@)
    if array_is_nonempty _params
    then
      case "${_source}" in
        git)
          fetch_git_extension "$1" "$2"
          external_extension_install "$1" "$2"
          ;;
        github)
          fetch_git_extension "$1" "git://github.com/${2}.git"
          external_extension_install "$1" "git://github.com/${2}.git"
          ;;
        help)
          NIY "extend from help"
          ;;
        release)
          NIY "extend from release"
          ;;
        tarball)
          NIY "extend from tarball"
          ;;
        hg)
          NIY "extend from hg repository"
          ;;
        svn)
          NIY "extend from svn repository"
          ;;
        rsync)
          NIY "extend from rsync dirctory url"
          ;;
        scp)
          NIY "extend from scp tarball url"
          ;;
        default|wayneeseguin|*)
          fetch_extensions_repository
          extensions_install "${_params[@]}"
          ;;
      esac
    else
      fail "An extension name must be given."
    fi
  else
    fail "Source must be specified."
  fi
}

