#!/usr/bin/env bash


extend_from()
{
  # "release" "${extension_args[@]}"
  local _source="${1:-}" _params _name
  if variable_is_nonempty _source
  then
    shift
    _name="${1}"
    shift
    _params=($@)

    if variable_is_nonempty _name
    then
      case "${_source}" in
        git)
          NIY "extend from git repository"
          fetch_extensions_git_repository "${_params[${#_params[@]}]}"
          extensions_install "${_name}" "${_params[@]}"
          ;;
        github)
          NIY "extend from github repository"
          ;;
        help)
          NIY "extend from help"
          ;;
        release)
          NIY "extend from release"
          ;;
        tarball)
          NIY "extend from tarball"
          ;;
        hg)
          NIY "extend from hg repository"
          ;;
        svn)
          NIY "extend from svn repository"
          ;;
        rsync)
          NIY "extend from rsync dirctory url"
          ;;
        scp)
          NIY "extend from scp tarball url"
          ;;
        default|wayneeseguin|*)
          fetch_extensions_git_repository
          extensions_install "${_name}" "${_params[@]}"
          ;;
      esac
    else
      fail "An extension name must be given."
    fi
  else
    fail "Source must be specified."
  fi
}

