#!/bin/sh

__sm.traps.on.exit()
{
  typeset _result _command
  _result="$?"
  for _command in "${on_exit_commands[@]}"
  do
    if ! eval "${_command}"
    then
      __sm.log.warn "traps on exit; command failed: '${_command}'"
    fi
  done
  return "${_result}" # Return the original process exit status.
}
