#!/usr/bin/env bash

if [[ ! -w $bdsm_path ]]
then
  scm_path="$HOME/.bdsm/scm"
  archives_path="$HOME/.bdsm/archives"
fi
[[ -d "${scm_path}" ]]      || mkdir -p $scm_path
[[ -d "${archives_path}" ]] || mkdir -p $archives_path

